### ISSUE TITLE
Add Ultimate oscillator

### ISSUE THREAD

**Issue by blahetal** [mementum/backtrader#102]
Hi, can you add Ultimate oscillator to backtrader
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:ultimate_oscillator

thanks

**Comment by mementum** [comment]
http://www.backtrader.com/posts/2016-06-22-ultimate-oscillator/ultimate-oscillator/

Will be automatically included in the next packaged release. You can use the indicator meanwhile directly in your code
