### ISSUE TITLE
Cross section analysis among different instruments in the same asset class

### ISSUE THREAD

**Issue by SeraphicYuan** [mementum/backtrader#104]
Hi mementum,

Thanks for the great job. When experimented with backtrader, I can easily manipulate the single instrument (say one stock). I'm wondering if there's an way (without using too many for loop) to do cross section analysis in each next().

For example, if every month, I want to buy & hold the top10 stocks from a pool of 100 stocks based on certain criteria: say Past 1 Month's return. Currently the way I can think of is to:
1. Add all 100 stocks into Cerebro
2. Define a custom indicator which calculate one month return using close price for each stock and iterate through 100 stocks to find the top10 names
3. Push in order

For 2, I used to merge all 100 stocks by close price, then simply use pandas operation to get monthly return and rank them to output a selection list. Do you know if there's similar way in backtrader?

Minor thing regarding order, without defining size directly, can we define how much cash to allocate among each instrument in a portfolio? Thus won't facing with issues that strategy is slightly out of cash and order are not executed.

Thank you,

seraphic

**Comment by mementum** [comment]
Although I see no problem with the approach, but if you are managing 100 items, you need a for loop somewhere. I wouldn't define the custom indicator.

The custom indicator would place the results of the monthly return calculation in 100 different lines. Moreover: if you decide to add more stocks you need to redefine the indicator to accommodate extra lines. And if you pass less datas, you are wasting memory (in our modern days with GBytes of RAM ... this may be disregarded ... or not)

The most sensible (in the sense of real practicality) which I see is to do the calculation directly in `next` with a for loop in which you pass the data values to Pandas.

You can also do it with an `Analyzer`. There is an analyzer named `TimeReturn` which calculates the return in the chosen timeframe of your strategy.

The same principle can be applied to the datas. The source code is at:

  - https://github.com/mementum/backtrader/blob/master/backtrader/analyzers/timereturn.py

In each `next`you end up with `100` values which you can map to the data indices in the array `self.datas`

> Minor thing regarding order, without defining size directly, can we define how much cash to allocate among each instrument in a portfolio? Thus won't facing with issues that strategy is slightly out of cash and order are not executed.

Not directly, but the basis for implementing it exists. It is called a `Sizer`

  - You only have to subclass from `SizerBase`and redefine: `def _getsizing(self, comminfo, cash, data=None)`

  - The source is at: https://github.com/mementum/backtrader/blob/master/backtrader/sizer.py

    There is already a `SizerFix` defined which is actually what is used if you pass `size=None` to `buy` or `sell`
