### ISSUE TITLE
Order execution logic with current day data

### ISSUE THREAD

**Issue by qqgit** [mementum/backtrader#105]
Hi mementum,
    One order execution logic of backtrader is:
             **"The current data has already happened and cannot be used to execcute an order."** 
    However, in reality the current bar data includes OHLC prices with the open price comes first and close price last. In the current day, I should have got open price and want to use it for my buy/sell decision (without known anything about high/low/close prices). 
    **The question is, how can I create an order that can be executed in current day, with knowledge of current open price** (certainly, the curent high/low/close prices are not used anywhere including in strategy indicator)?
    Thanks!

**Comment by mementum** [comment]
Hi,

Yes the OHLC includes the "opening" price, but this price is no longer available because the bar is evaluated when the bar is "complete"

If you want to execute a strategy to consider a non-closed daily range you have to use intraday data. You can either use it as:

  - Intraday directly

or

  - Replay the data. You get the reconstruction of the daily bar.

Your other option is to break daily bars in two parts:

  - A single tick which is the opening price
  - A second bar-tick which includes the high-low-close prices

If you replay those two "ticks" you get a daily bar but you get the chance to act in between.

**Comment by qqgit** [comment]
Hi mementum,

Thanks for your comments.

The option to break daily bars in opening price part and high-low-close prices part and replay both seems good and practical to me.

However, I haven't understand the "intraday directly" and "Replay the data" options.

For the "intraday directly" option:
- How can I use intraday data directly in backtrader? In prenext? 

and for the "Replay the data" option:
- If I don't have the more detailed data (e.g. minute data), is it possible to replay the daily data and create order after the "opening" price happens?

I think its a natural way to make decisions by using all available known data, especially the most recent data. In practical, when the market is opening, the opening price of current day is known and we can use it in our strategy (or we may adjust our buy/sell strategy since the opening price provides us new info about the market) and create orders that can be executed in the current day.

Could you please add some enhancement in backtrader's order execution logic to support  the usage of most recent available known data like opening price?

Thanks!

**Comment by mementum** [comment]
If you use intraday data directly, you can then operate close to the opening. If you have *minute* resolution bars you can operate 1 minute after the opening, and this should give you a good entry point close to the opening. You also operate in `next` as a rule of thumb.

`prenext` is called before all indicators are delivering meaningful data. In the simple case of a single moving average, `prenext` is called the n-1 periods before the average produces a data. After that `next` is called.

Data Replay needs smaller resolution data to give you larger resolution data. You can go from minutes to days. But you cannot go from day to day.

Hence the suggestion to simulate intraday data by breaking your daily bars into `open` + `high-low-close` bars and *replay* those 2 ticks.

**Comment by qqgit** [comment]
Got it. 
Thanks for your suggestions!

**Comment by mementum** [comment]
A day to "day in steps" filter which alleviates the need for intraday data by breaking a "daily" bar in 2 bars (an opening bar and the rest), which allows for introduction of orders upon seeing the opening price. See this:

  - http://www.backtrader.com/posts/2016-07-13-day-in-steps/day-in-steps/
