### ISSUE TITLE
Include a Portfolio

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#108]
Hi,

I think a new feature could be included to complete this amazing project: a portfolio to store our trades, risk management, money management, calculate performance... Pyfolio could be an option.

Thanks a lot

**Comment by dafyddd** [comment]
I'm not sure I understand what you're asking. Can you describe what you're thinking of?

**Comment by junajo10** [comment]
Hi,

Pyfolio is a Python library for performance and risk analysis of financial portfolios.
https://github.com/quantopian/pyfolio

The portfolio order management system is a complex component of an backtesting system. Its role is to keep track of all current market positions as well as the market value of the positions.

In addition to the positions and holdings management the portfolio must also be aware of risk factors and position sizing techniques in order to optimise orders that are sent to a brokerage or other form of market access.

Rgds,

JJ

**Comment by mementum** [comment]
This is an interesting idea but it's obviously not going to happen overnight. Looking at this from the `pyfolio` tutorial running with `zipline`

> returns, positions, transactions, gross_lev = pf.utils.extract_rets_pos_txn_from_zipline(results)

It's obvious that `pyfolio` and `zipline` have common caretakers that know the intimate details of each other.

In this case a function which returns compatible objects (`returns`, `positions`, `transactions` and `gross_lev`) would be needed and that for sure means peeking inside both `pyfolio` and `zipline`.

Will be looked into.

**Comment by mementum** [comment]
Blog entry with the pyfolio charts here: http://www.backtrader.com/posts/2016-07-17-pyfolio-integration/pyfolio-integration/
