### ISSUE TITLE
IB Historical Data pacing violation

### ISSUE THREAD

**Issue by remroc** [mementum/backtrader#110]
Hello DRo,

Thanks for this great fwk. 

Quick questions related to IB Historical data through the ibtest.py sample.

I have tried to collect histo data for following timeframe/compression : Minutes/1 since 2016-01-01 and received following message after 18773 retrieved lines :  
`errorMsg=Historical Market Data Service error message:Historical data request pacing violation`

1/ Could it be related to IB's contraint  ?

https://www.interactivebrokers.com/en/software/api/apiguide/tables/historical_data_limitations.htm

> The following conditions can cause a pacing violation:
> 
> Making identical historical data requests within 15 seconds;
> Making six or more historical data requests for the same Contract, Exchange and Tick Type within two seconds.
> Also, observe the following limitation when requesting historical data:
> 
> Do not make more than 60 historical data requests in any ten-minute period.
> If the whatToShow parameter in reqHistoricalData() is set to BID_ASK, then this counts as two requests and we will call BID and ASK historical data separately.

2/ One more thing, could you precise how to retrieve the histo data of real trading hour by using useRTH ?
https://www.interactivebrokers.com/en/software/api/apiguide/java/reqhistoricaldata.htm

3/ Finally, what is your recommandation to store those histo data in a CSV file as buffering/storing first within a panda dataframe might overload system memory ?

Many thanks again for your answers !!! :+1: 

Rgds,

Remi

**Comment by mementum** [comment]
1. It is. This is not meant a as historical data downloader from ib. To be it should implement data pacing constraints, which given the rules laid out by ib, would lead to the minimum common denominator of wait 10 seconds after each request.

The Data feed is meant to be a real-data feed and because it implements backfilling it allows you to do also do historical download. But if you want MUCH data ... it may be IB is not your best bet.

2. "RTH" is NOT "Real Trading Hour" but "REGULAR Trading Hours". The definition of what is actually "real" trading is open and each trader/broker sees it differently.

It is simple:
```
data = bt.feeds.IBData(dataname='TWTR', useRTH=True)  # the default for useRTH is False
```

**Comment by remroc** [comment]
Wow quick answer. Thanks !

Thanks for clarifications of REGULAR Trading Hours and how to set it :+1: 

Ok for Question 1.
Retrieving the histo data with IB are indeed constraintfull. But as I don't want to plug to another data provider for the moment, I will go with a sleep(10) if you agree...

Regarding storing the results in a file, I am thinking of appending the text in an open CSV file. 

Do you have any recommandations for those ideas ?

Remi

**Comment by mementum** [comment]
As you may have seen most data feeds in *backtrader* use CSV (except the ones that would read from a Pandas DataFrame and the 3 online-feeds)

Unless several different data sets are being managed, csv files should be enough. HDF5 would be a good option if moving up the scale.
