### ISSUE TITLE
Trying the IB - Bracket Order 

### ISSUE THREAD

**Issue by remroc** [mementum/backtrader#112]
Hello DRo,

I am trying to execute a bracket order through BackTrader. I am passing correct params in the orders as they can be executed individually.

But it seems it is not possible to execute those orders together. 

Thank you for your feedback.

Cheers,

Remi

Here is the updated code of the samples/ibtest.py for the next() :

`        `if self.datastatus and not self.position and len(self.orderid) < 1:

            
            self.order = self.buy(size=self.p.stake,
                                  exectype=bt.Order.Limit,
                                  price=self.data0.close[0] + 1,
                                  transmit=False)

            self.orderid.append(self.order)

            self.orderSTPLOSS = self.sell(size=self.p.stake,
                                          exectype=bt.Order.Stop,
                                          price = self.data0.close[0],
                                          valid=self.p.valid,
                                          transmit = False,
                                          parentId=self.order)

            self.orderid.append(self.orderSTPLOSS)
            
            self.orderSTPWIN = self.sell(size=self.p.stake,
                                         exectype=bt.Order.Stop,
                                         price = self.data0.close[0] + 2,
                                         valid=self.p.valid,
                                         transmit = True,
                                         parentId=self.order)

            self.orderid.append(self.orderSTPWIN)`

**Comment by remroc** [comment]
For info, you can find a working example of Bracket Order here :
https://groups.google.com/forum/#!topic/ibpy-discuss/PrTQf2kH1Cc

IB documentation:
https://www.interactivebrokers.com/en/software/api/apiguide/java/order.htm

Attaching Order in IB:
http://ibkb.interactivebrokers.com/node/1043

**Comment by remroc** [comment]
Ooh by the way DRo are you living in Germany ? A lot of courage for those terrorist attacks...

**Comment by remroc** [comment]
Hello DRo, 

I have succeeded into executing a bracket order. Hoping you are ok.

Cheers,

Remi

**Comment by mementum** [comment]
Hi. Everything ok.

Glad to you know you've been able to make a *bracket order*.
