### ISSUE TITLE
Removing Classes

### ISSUE THREAD

**Issue by Immortalin** [mementum/backtrader#113]
Is it possible to use this without having to create a class for every strategy?

**Comment by mementum** [comment]
*Metaclasses* are at the core foundation of **this** to make it as easy as possible to use it and transparently control many aspects of the machinery.

In any case you can have a master strategy which by means receiving `callables` as parameters, would always keep the same structure.

In any case you need to define any indicators/on-the-spot-lines during the `__init__` phase and be ready to receive different notifications and most important to be called with `next`.

You seem to be looking for a very specific scenario. Be it so, the answer may be somehow more accurate with some more details about the target scenario.

**Comment by mementum** [comment]
Signals don't remove the classes but imho greatly simplify the usage of the platform. You may want to check the docs regarding this functionality which was introduced after this issue:

 - http://backtrader.readthedocs.io/en/latest/signal_strategy/signal_strategy.html

**Comment by Immortalin** [comment]
@mementum thanks, I will take a look at it
