### ISSUE TITLE
PIP3 cannot install the latest backtrader package

### ISSUE THREAD

**Issue by 4ever911** [mementum/backtrader#114]
Everything works perfectly good for Python2/Pip2

But the backtrader package cannot be installed by using: pip3 install backtrader

It only installs a very old version like 1.x

Cannot install the WHL file for pip3 either.

So, I have to install it manually by using the tarball source file.

**Comment by mementum** [comment]
Hi, I have recreated the wheel version with --universal and tested the installation directly with

`pip install backtrader`

(on a Python 3.5 installation)

with success. Let me know if it doesn't work.

**Comment by 4ever911** [comment]
Great! It works now!
