### ISSUE TITLE
Observing the close & other forms of lookahead bias

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#119]
Hi,

I have read this article:
http://blog.quantopian.com/9-mistakes-quants-make-that-cause-backtests-to-lie-by-tucker-balch-ph-d/

I would like to know your opinion about the point 3 and how backtrader could cover it.

3. Observing the close & other forms of lookahead bias

In this failure mode, the quant assumes he can observe market closing prices in order to compute an indicator, and then also trade at the close. As an example, one might use closing price/volume to calculate a technical factor used in the strategy, then trade based on that information.

This is a specific example of lookahead bias in which the strategy is allowed to peek a little bit into the future. In my work I have seen time and again that even a slight lookahead bias can provide fantastic (and false) returns.

Other examples of lookahead bias have to do with incorrect registration of data such as earnings reports or news. Assuming for instance that one can trade on the same day earnings are announced even though earnings are usually announced after the close.

Solution: Don’t trade until the open of the next day after information becomes available.

**Comment by mementum** [comment]
*backtrader* disallows execution of a ``Close`` order during the same bar when using daily bars. Of course if you use intraday data and the order is issued before the end of the session, the order will go in.

This was discussed in ticket #105 but with regards to the ``Open`` price.

This gave birth to a filter which breaks the data in 2 parts:

  - `Open` + `HLC`

    This allows using daily data to do the following: see the ``Open`` and issue an order, which may or may not be matched with the `HLC` values. This blog post discusses it: http://www.backtrader.com/posts/2016-07-13-day-in-steps/day-in-steps/

Recently the other use case was also added (there will be a documentation update with the filters documented), in which the bar is broken in two parts like this:

  - `OHL` + `Close`

In this case 2 filters are presented, one which acts alone and the preferred solution which is combined with `replaydata`. The blog post discussing it: http://www.backtrader.com/posts/2016-07-29-pinkfish-challenge/pinkfish-challenge/

In this case and observing the `OHL` values a `Close` order may be issued which will be evaluated during the `Close` which has not yet been seen.

There is a corner case in all this bar-splitting process in which for example if the `Close` happens to be the `High` or the `Low` of the day, the price is already known before issuing the order. In practical terms the expected change from a previous value to the `Close` being the `high`/`low` should be marginal in absolute terms, given it is the last tick, which implies that the assumptions made by looking at `OHL` are good enough.

**Comment by junajo10** [comment]
Thanks, It is clear. 

Another key point could  be model the **slippage**, for example we can use the link to develop this feature.

"Be sure to anticipate that price will move against you at every trade. For trades that are a small part of overall volume, a rule of thumb is about 5 bps for S&P 500 stocks and up to 50 bps for more thinly traded stocks. It depends of course on how much of the market your strategy is seeking to trade."
