### ISSUE TITLE
strategy performance?

### ISSUE THREAD

**Issue by xingjianpan** [mementum/backtrader#12]
Hi, 

Is it any plan to include strategy performance metrics (i.e return, Sharp, draw down, etc.)?  

I think backtrader keep tracks of the daily cash/portfolio value somewhere, is there a way to export those into a csv? 

Thanks,
Xingjian

**Comment by mementum** [comment]
Yet another thing which is there to be documented. The support to keep track of things like "cash/value" (or drawdown) and any other statistics is generic and already implemented.

Already some versions ago drawdown got implemented.

Do the following:

````python
    import backtrader as bt
    import backtrader.observers as btobservers

    # many other things

    cerebro = bt.Cerebro()
    cerebro.addobserver(btobs.DrawDown)

    # some other things

    cerebro.run()

    cerebro.plot()
````

As for keeping track of it in a CSV file, that's doable ... but if you for example add statistics for trades, you start adding a large amount of columns.

I would write it down to a file from the "next" method of the strategy.

Hopefully I will have the time this week to document statistics/observers

**Comment by mementum** [comment]
Additional note ... if you want to write down the cash and portfolio values at each point in time, you'd  do the following to access the values

````python
    import backtrader as bt
    import backtrader.observers as btobs

    # ssome things

    class MyStrategy(bt.Strategy):
        # init and other methods
        def next(self):
            print('cash at this point in time is %.2f' % self.stats.broker.cash[0])
            print('value at this point in time is %.2f' % self.stats.broker.value[0])
            print('drawdown at this point in time is %.2f' % self.stats.drawdown.drawdown[0])
            print('maxdrawdown at this point in time is %.2f' % self.stats.drawdown.maxdrawdown[0])

    cerebro = bt.Cerebro()
    cerebro.addobserver(btobs.DrawDown)

    # some other things

    cerebro.run()

    cerebro.plot()
````

**Comment by xingjianpan** [comment]
I see. Thanks!

**Comment by mementum** [comment]
Documentation post for the topic with charts and code (automatic saving to a file is a tbd enhancement)

http://www.backtrader.com/posts/2015-08-12/observers-and-statistics/

**Comment by mementum** [comment]
Besides the aforementioned observers (which track in real-time) there is support for for adding post-run analyzers like for example "SharpeRatio"

The development branch contains the code and the SharpeRatio (and AnnualReturn) analyzer

Some code (removing most bells and whistles)

The newly automated support script bt-run.py also contains support to execute Analyzers and print the result out

````python

import backtrader.analyzers as btanalyzers

cerebro = bt.Cerebro()

cerebro.addanalyzer(btanalyzers.SharpeRatio, _name='mysharpe')

thestrats = cerebro.run()
thestrat = thestrats[0]
print('Sharpe Ratio:' thestrat.analyzers.mysharpe.get_analysis())

````

**Comment by xingjianpan** [comment]
Noted, thanks!

**Comment by mementum** [comment]
The Analyzers are now part of the main release (starting with 1.1.3.88) including SharpRatio and AnnualReturn.

They are also supported by the automation script bt-run.py included (and installed) in the distribution

**Comment by xingjianpan** [comment]
Thanks for the update!
