### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by sirinath** [mementum/backtrader#122]
Wondering if you are willing to change the license to a more permissive license like ASL 2.0, MIT or BSD?

**Comment by mementum** [comment]
For the sake of if I just counted the number of lines in the *backtrader* repository:

  - in `py` files in the distribution: `25442`
  - in `py` files in the documentation: `4159`
  - in `rst` files in the documentation: `20798`

For a grand total of: `50399` lines

The count could also include the extras in the blog, but who cares, 

If having over *50K* lines of code and documentation at your disposal for the cost of 0 monetary units, whatever yours happens to be, is not *permissive* enough for you, you may always write your own platform. It's free.

You may always make an offer to buy a commercial license of the platform for your own proprietary use and distribution to others (the goal of having any of the above licenses)
