### ISSUE TITLE
Bitcoin broker

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#126]
I think  bitcoin is a good choice to use backtrader:spread, liquidity and regulation

Here we can find some brokers 
http://www.forexnews.com/bitcoin-brokers/
I have reviewed some of them and maybe bitstamp and btc-e are the best.

Do you have this feature in your roadmap? I would like to know your opinion about criptocurrencies in general.

Also i think bitcoin is the best option to use a smart order routing between several brokers.

Rgds,

Jj

**Comment by mementum** [comment]
Cryptocurrencies with regards to *backtrader* are just another type of asset which can be traded. Nothing special about them.

Nothing is planned.

**Comment by junajo10** [comment]
Thanks, i will keep an eye on your updates. 

Also, i am thinking about SOR . Now you specify the broker:
cerebro.setbroker(broker)

I think a good idea is not to fix the broker, you define several brokers and you define the logic to decide where to operate and depend on several factors such as liquidity, asset class, comission model... Dynamically  send the order to the most suitable broker in each moment.(method next could evaluate logic where to operate)

For example setbrokers(oanda, ib), and you could choose oanda for forex and ib for eq and futures.

it seems to me that could be a good idea .

Rgds,

Jj

**Comment by mementum** [comment]
This was an original part of the plan and some of the initial internal api/methods can actually copy with more than one broker. Having been discarded to avoid extra complexities and having looked at the actual implementation of some methods (especially what refers to *notifications*), the introduction of multiple brokers for a single strategy would break many existing methods.

A rewrite/consolidation of some other internals would be of greater use for further extensions of the framework and later the introduction of such feature.

Given the above, it will not be happening any time soon in this series of versions
