### ISSUE TITLE
Error with some Yahoo! tickers 

### ISSUE THREAD

**Issue by dsalomoni** [mementum/backtrader#127]
Hi,

I am trying to download tickers from Yahoo! using YahooFinanceData and some of them are giving errors. An example is FTSEMIB.MI. Running the sample yahoo-test.py script gives

`Davides-MacBook-Pro-2:yahoo-test davide$ ./yahoo-test.py -p -f 2016-01-01 -t 2016-06-30 -d FTSEMIB.MI
Traceback (most recent call last):
  File "./yahoo-test.py", line 105, in <module>
    runstrat()
  File "./yahoo-test.py", line 62, in runstrat
    cerebro.run()
  File "/Users/davide/anaconda2/lib/python2.7/site-packages/backtrader/cerebro.py", line 624, in run
    runstrat = self.runstrategies(iterstrat)
  File "/Users/davide/anaconda2/lib/python2.7/site-packages/backtrader/cerebro.py", line 711, in runstrategies
    self._runonce(runstrats)
  File "/Users/davide/anaconda2/lib/python2.7/site-packages/backtrader/cerebro.py", line 839, in _runonce
    strat._once()
  File "/Users/davide/anaconda2/lib/python2.7/site-packages/backtrader/lineiterator.py", line 254, in _once
    indicator._once()
  File "/Users/davide/anaconda2/lib/python2.7/site-packages/backtrader/lineiterator.py", line 254, in _once
    indicator._once()
  File "/Users/davide/anaconda2/lib/python2.7/site-packages/backtrader/lineiterator.py", line 274, in _once
    self.oncestart(self._minperiod - 1, self._minperiod)
  File "/Users/davide/anaconda2/lib/python2.7/site-packages/backtrader/lineiterator.py", line 284, in oncestart
    self.once(start, end)
  File "/Users/davide/anaconda2/lib/python2.7/site-packages/backtrader/indicators/basicops.py", line 266, in once
    dst[i] = math.fsum(src[i - period + 1:i + 1]) / period
IndexError: array assignment index out of range
Davides-MacBook-Pro-2:yahoo-test davide$ `

If I query tickers such as AAPL, CSCO (or even FCA.MI), no issues. The relevant page for FTSEMIB.MI on finance.yahoo.com would be http://finance.yahoo.com/quote/FTSEMIB.MI/?p=FTSEMIB.MI; on ichart, it should be http://ichart.yahoo.com/table.csv?s=FTSEMIB.MI.

Also other tickers such as http://finance.yahoo.com/quote/EURUSD=X/?p=EURUSD=X throw an exception. Is there a special syntax to use for these cases?

Using Python 2.7 and backtrader 1.8.6.93.

**Comment by mementum** [comment]
This an execution using the built-in `btrun` with the same dates used above

```
===============================================================================
Id,FTSEMIB,len,datetime,open,high,low,close,volume,openinterest,Strategy,len,Broker,len,cash,value,BuySell,len,buy,sell,Trades,len,pnlplus,pnlminus
===============================================================================
Cerebro:
...
```

And this is an execution with `--fromdate 2016-08-15` and `-todate 2016-08-21`

```
===============================================================================
Id,FTSEMIB,len,datetime,open,high,low,close,volume,openinterest,Strategy,len,Broker,len,cash,value,BuySell,len,buy,sell,Trades,len,pnlplus,pnlminus
1,FTSEMIB,1,2016-08-16 23:59:59,16793.0,16793.0,16793.0,16793.0,0.0,0.0,Strategy,1,Broker,1,10000.0,10000.0,BuySell,1,,,Trades,1,,
2,FTSEMIB,2,2016-08-18 23:59:59,16673.6,16673.6,16673.6,16673.6,0.0,0.0,Strategy,2,Broker,2,10000.0,10000.0,BuySell,2,,,Trades,2,,
3,FTSEMIB,3,2016-08-19 23:59:59,16310.1,16310.1,16310.1,16310.1,0.0,0.0,Strategy,3,Broker,3,10000.0,10000.0,BuySell,3,,,Trades,3,,
===============================================================================
Cerebro:
...
```

Trying to fetch values from 1 year ago ...

```
Id,FTSEMIB,len,datetime,open,high,low,close,volume,openinterest,Strategy,len,Broker,len,cash,value,BuySell,len,buy,sell,Trades,len,pnlplus,pnlminus
===============================================================================
Cerebro:
...
```

This seems to be a limitation set by Yahoo given that the values from last week can be downloaded but not those from June 2016 or August 2015. And other tickers return values back to at least 1994-1995 ...

**Comment by dsalomoni** [comment]
Right, that must be it. I've just checked with ystockquote trying to get historical prices and yes, FTSEMIB.MI (for example) is only available for recent dates (not sure what the details of the limitation is):

<pre>
Davides-MacBook-Pro-2:yahoo-test davide$ python -c 'import ystockquote; print(ystockquote.get_historical_prices("FTSEMIB.MI", "2016-01-01", "2016-08-31").keys())'
['2016-08-18', '2016-08-19', '2016-08-10', '2016-08-16', '2016-08-11']
Davides-MacBook-Pro-2:yahoo-test davide$ python -c 'import ystockquote; print(len(ystockquote.get_historical_prices("FTSEMIB.MI", "2016-01-01", "2016-08-31")))'
5
Davides-MacBook-Pro-2:yahoo-test davide$ python -c 'import ystockquote; print(len(ystockquote.get_historical_prices("ORCL", "2016-01-01", "2016-08-31")))'
160
Davides-MacBook-Pro-2:yahoo-test davide$
</pre>

Thank you anyway for your help and for writing backtrader, now going back to strategies and indicators.

**Comment by mementum** [comment]
With regards to "EURUSD=X" the server replies with a `404 NOT FOUND"

This *StackOverflow* answer http://stackoverflow.com/questions/12114754/programmatically-access-currency-exchange-rates-from-yahoo-finance-by-date?rq=1 says:

> To retrieve historical data of currency exchange rates, you can't use Yahoo Finance. Their API only offers historical data of stocks. For example for APPLE between April the 1st 2003 and July, 30:

Getting the actual *rate* seems possible over *download.finance.yahoo.com*, but not the historical prices

**Comment by mementum** [comment]
And `pandas-datareader` seems to have the same issue with `EURUSD=X` - https://github.com/pydata/pandas-datareader/issues/167

It seems another server side Yahoo limitation
