### ISSUE TITLE
Tracking highest high and lowest low

### ISSUE THREAD

**Issue by jvdeepak** [mementum/backtrader#128]
Hi mementum, 

I am a newbie and trying to adapt the example with my own strategy. I need to track highest high and lowest low to identify if a new high or low has been made. If time permits can you help with the code please?

So far my attempt has been this....

```python
def __init__(self):
        self.dayhigh = self.datas[0].high
        self.daylow = self.datas[0].low
        print('First time Day high set to %.2f ' % self.dayhigh[1])
        print('First time Day low set to %.2f ' % self.daylow[1])
	# Not sure why I have to print self.dayhigh[1] to get the low of the first bar.
		
def next(self):
	if self.datas[0].high > self.dayhigh[0]:
	    print('New high made')
	    self.dayhigh[0] == self.datas[0].high
	    print('New Day High, %.2f' % self.dayhigh[0])
```

But the if condition never executes.

Thanks in advance

-Deepak

**Comment by mementum** [comment]
I think you are missing several of the concepts in *backtrader*

1. you access index `1` and this is the future. If the data has been preloaded (the default to speed up things) you can do that, but this is wrong.

2. During `__init__`  you don't access the `[]` operator of lines. There is no data there yet (preloading is only an artifact to speed things up)

3. During `__next__` the condition never executes because: `self.datas[0].high` and `self.dayhigh[0]` point to the same object and therefore hold the same value. (You have made `self.dayhigh = self.datas[0].high` during `__init__`)

*backtrader* includes a `Highest` indicator.

```python
def __init__(self):
    self.highesthigh = bt.indicators.Highest(self.data.high(-1), period=10)

def next(self):
    if self.data.high[0] > self.highesthigh[0]:
        print('new high')
```

`self.data.high(-1)` gives you the `high` prices delayed 1 period. In this case this excludes the current (`0`) price from `self.highesthigh`

I would recommend going over the documentation to get familiarized with the concepts in *backtrader*

**Comment by jvdeepak** [comment]
I really appreciate your response, will go over the documentation agian to understand the concepts.

**Comment by jvdeepak** [comment]
Hi mementum,

Sorry for my so trivial question...... but i am struggling to understand this....

I am struggling to understand the line iterator with respect to init() and next(). My understanding is that init() run once when the strategy starts and next() runs on every iteration ie., for each row of the data read from the csv file. Is this correct ? 

I want to get highest high at particular time of the day and use that high to calculate the order entry & exit. But all my attempts have failed. If possible can you show me an example please? 

This is what i have tried....

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import datetime  # For datetime objects


import backtrader as bt
import backtrader.feeds as btfeeds

class MyOHLC(btfeeds.GenericCSVData):

      params = (
              ('fromdate', datetime.datetime(2016, 8, 1)),
              ('todate', datetime.datetime(2016, 8, 2)),
              ('nullvalue', 0.0),
              ('dtformat', ('%Y-%m-%d')),
              ('tmformat', ('%H:%M:%S')),
              ('datetime', 1),
              ('time', 2),
              ('open', 3),
              ('high', 4),
              ('low', 5),
              ('close', 6),
              ('volume', 7),
              ('openinterest', -1)
      )



class TestStrategy(bt.Strategy):
    
    params = (
        ('starttimeparam', "9, 29, 59"),
        ('printlog', True),
    )

    def log(self, txt, dt=None, bartime=None, doprint=True):
        ''' Logging function for this strategy'''
        if self.params.printlog or doprint:
            dt = dt or self.datas[0].datetime.date(0)
            bartime = bartime or self.datas[0].datetime.time(0)
            print('%s, %s, %s, %s' % (datafile._name, dt.isoformat(), bartime.isoformat(), txt))
            
    def __init__(self):

        self.highesthigh = bt.indicators.Highest(self.datas[0].high)

    def next(self):
        
        self.log('High, %.2f' % self.data.high[0])
        # Converting time param from string to datetime format
        starttimewithdatefrmt = datetime.datetime.strptime(self.params.starttimeparam, "%H, %M, %S")
        # Reformating datetime format to just time
        starttime = datetime.datetime.time(starttimewithdatefrmt)
        
        if self.datas[0].datetime.time(0) == starttime:
            print('Highesthigh at 09:29:59 %.2f' % self.highesthigh[0])
            print('Current bar high at 09:29:59 %.2f' % self.data.high[0])

if __name__ == '__main__':

    # Create a cerebro entity
    cerebro = bt.Cerebro()

    # Add a strategy
    cerebro.addstrategy(TestStrategy)

    datafile = MyOHLC(dataname='BNF_data_1min_sample.csv')
    # Add the Data Feed to Cerebro
    cerebro.adddata(datafile, name="BNF")
    
    # Set our desired cash start
    cerebro.broker.setcash(100000.0)

    # Add a FixedSize sizer according to the stake
    cerebro.addsizer(bt.sizers.FixedSize, stake=2)

    # Set the commission - 0.1% ... divide by 100 to remove the %
    cerebro.broker.setcommission(commission=0.000)

    # Run over everything
    cerebro.run()

And the data is in this format

BNF_data_1min_sample.csv
Ticker,Date,Time,Open,High,Low,Close,Volume,OpenInterest 
BANKNIFTY-I,2016-08-01,9:15:59,19045,19160,19010,19155.9004,46200,1729120
BANKNIFTY-I,2016-08-01,9:16:59,19150.1504,19180,19146.0508,19146.0508,49680,1729120
BANKNIFTY-I,2016-08-01,9:17:59,19146.5508,19149.9492,19105.5996,19106.1504,42880,1729120
BANKNIFTY-I,2016-08-01,9:18:59,19106,19129.9492,19102.1504,19120,30280,1772680
BANKNIFTY-I,2016-08-01,9:19:59,19120,19129,19116.1992,19129,37640,1772680
BANKNIFTY-I,2016-08-01,9:20:59,19124.5996,19145,19124.5996,19135.75,35880,1772680
BANKNIFTY-I,2016-08-01,9:21:59,19131.9492,19131.9492,19096.0996,19111.9492,30000,1801800
BANKNIFTY-I,2016-08-01,9:22:59,19113.1992,19127.9004,19110,19122.9492,9760,1801800
BANKNIFTY-I,2016-08-01,9:23:59,19121.0996,19126.9492,19110.1992,19110.1992,13760,1801800
BANKNIFTY-I,2016-08-01,9:24:59,19110.1992,19125,19110.1992,19125,11480,1821160
BANKNIFTY-I,2016-08-01,9:25:59,19121.1992,19126.3496,19115.1504,19123.0508,6480,1821160
BANKNIFTY-I,2016-08-01,9:26:59,19123.0508,19127.9492,19122,19126.5,8720,1821160
BANKNIFTY-I,2016-08-01,9:27:59,19125,19129,19122,19129,8440,1828360
BANKNIFTY-I,2016-08-01,9:28:59,19124.4004,19136,19123,19129.4492,9880,1828360
BANKNIFTY-I,2016-08-01,9:29:59,19129.4492,19153.9492,19128.5996,19148.9004,28480,1828360
BANKNIFTY-I,2016-08-01,9:30:59,19149.4492,19159.9004,19149.4492,19150,16760,1833240
BANKNIFTY-I,2016-08-02,9:15:59,18898.5,18898.5,18809.4004,18824.8496,29640,1891200
BANKNIFTY-I,2016-08-02,9:16:59,18822.0996,18862.25,18822.0996,18857.0508,23480,1891200
BANKNIFTY-I,2016-08-02,9:17:59,18858.9492,18861.1992,18832.6992,18837.75,12320,1891200
BANKNIFTY-I,2016-08-02,9:18:59,18835.9492,18869.5996,18835.9492,18869.0508,14240,1892440
BANKNIFTY-I,2016-08-02,9:19:59,18870,18950,18869.4004,18933.9004,68320,1892440
BANKNIFTY-I,2016-08-02,9:20:59,18935,18962.0508,18930.3008,18934,53200,1892440
BANKNIFTY-I,2016-08-02,9:21:59,18934.0996,18942.5508,18930.75,18938.8008,17840,1883240
BANKNIFTY-I,2016-08-02,9:22:59,18935.0508,18938.8008,18920.0996,18920.0996,17640,1883240
BANKNIFTY-I,2016-08-02,9:23:59,18922.3008,18922.8008,18908,18908.5996,12480,1883240
BANKNIFTY-I,2016-08-02,9:24:59,18910,18924.9492,18905,18906.4004,15800,1879640
BANKNIFTY-I,2016-08-02,9:25:59,18906.4004,18921,18905.5,18913.5,8920,1879640
BANKNIFTY-I,2016-08-02,9:26:59,18912.3008,18912.3008,18900.0996,18909.0996,11040,1879640
BANKNIFTY-I,2016-08-02,9:27:59,18906.25,18913.8008,18888,18888,16760,1892440
BANKNIFTY-I,2016-08-02,9:28:59,18887.8008,18898,18887.8008,18895,8800,1892440
BANKNIFTY-I,2016-08-02,9:29:59,18896,18900,18883.5996,18887.9004,6840,1892440
BANKNIFTY-I,2016-08-02,9:30:59,18888.5,18889.3496,18862.5996,18870.1504,10240,1893400


The output is..............
BNF, 2016-08-01, 09:15:59, High, 19160.00
BNF, 2016-08-01, 09:16:59, High, 19180.00
BNF, 2016-08-01, 09:17:59, High, 19149.95
BNF, 2016-08-01, 09:18:59, High, 19129.95
BNF, 2016-08-01, 09:19:59, High, 19129.00
BNF, 2016-08-01, 09:20:59, High, 19145.00
BNF, 2016-08-01, 09:21:59, High, 19131.95
BNF, 2016-08-01, 09:22:59, High, 19127.90
BNF, 2016-08-01, 09:23:59, High, 19126.95
BNF, 2016-08-01, 09:24:59, High, 19125.00
BNF, 2016-08-01, 09:25:59, High, 19126.35
BNF, 2016-08-01, 09:26:59, High, 19127.95
BNF, 2016-08-01, 09:27:59, High, 19129.00
BNF, 2016-08-01, 09:28:59, High, 19136.00
BNF, 2016-08-01, 09:29:59, High, 19153.95
Highesthigh at 09:29:59 19153.95
Current bar high at 09:29:59 19153.95
BNF, 2016-08-01, 09:30:59, High, 19159.90

I am struggling to understand why highesthigh and current bar high (self.data.high[0]) is same.

Hopefully once i understand the basics it should get easier.

**Comment by mementum** [comment]
`self.highesthigh = bt.indicators.Highest(self.datas[0].high)`

You have specified no `period`, and the default value is `1`. The indicator is only looking at the last `high`and that's why the current `high` is the same as the `highesthigh`

From the online manua (http://backtrader.readthedocs.io/en/latest/indautoref.html)

```
Highest

Calculates the highest value for the data in a given period

Formula:
    highest = max(data, period)

Lines:

    highest

Params:
    period (1)

PlotInfo:
    subplot (True)
    plot (True)
    plotskip (False)
    plotname ()
    plotforce (False)
    plotyhlines ([])
    plothlines ([])
    plotabove (False)
    plotymargin (0.0)
    plotlinelabels (False)
    plotmaster (None)
    plotyticks ([])

PlotLines:
    highest:
```
