### ISSUE TITLE
Float datatype for money?

### ISSUE THREAD

**Issue by bofm** [mementum/backtrader#13]
Why not decimal or something else designed for financial data? Weren't there problems with floats when it's necessary to round results to perform exact comparison or to print numbers?

**Comment by mementum** [comment]
Decimal would add overhead and performance, but furthermore I don't think the benefit of "absolute" precision is something which is really needed.

Indicators are the parts which rely on calculations and so far when I have validated against other tools the results have been accurate. I checked up to 4 decimals and in that sense it seems many others arrived at the same conclusion about whether to use Decimal-like types or rather use IEEE floating point types.

The latter seems to suffice for the task at hand using double precision.

**Comment by bofm** [comment]
Decimals must be faster on Python 3.3+ in general and more memory efficient. Division with decimals is faster in any python version.

I believe there is no problem with floats is the tool satisfies the needs. However, some people would not even check out a money related util knowing that it stores money in floats.
