### ISSUE TITLE
Thanks DRo

### ISSUE THREAD

**Issue by remroc** [mementum/backtrader#130]
Hello DRo,

Just wanted to say thank you.

The more I use backtrader, the more I like it.

Cheers,

Remi

**Comment by remroc** [comment]
Hello DRo,

1 question related to sequence of signal.

How to execute an order after making sure sequence of signals was performed ?

For example, I would like to buy if the price < sma for the last 15 bars and price > bband(period=15, sd=1).bot.

Many thanks for your help.

Cheers,

Remi

**Comment by mementum** [comment]
Hi,

Thanks. I simply tried to make generic what I built for myself.

1) The *signals* functionality cannot be so smart and implement those conditional rules. It's the responsibility of the signals to implement them themselves.

The example should actually not be that difficult. A signal that is `True` if any of the previous `15` bars is `True`.  Some other things may be a bit more elegant, but the thing is about getting the job done ...

```python
class Condition1(bt.Signal):
    def __init__(self)
        realsignal = self.data < bt.indicators.BollingerBands(period=15)
        last15 = bt.indicators.Sum(realsignal, period=15)
        self.lines.signal = last15 > 0.0
```

2/ The `SQN` analyzer is not *timeframe* dependent. It works by counting *trades* (not *orders*) A *trade* is closed when the *size* of a position goes back to `0` or crosses `0`

**Comment by remroc** [comment]
Many thanks for your time and answer.

It helps a lot.

It worked and I was able to trade with these new features. 👍 

Are you looking for some help in the development of the framework ? 

Cheers DRo :) ,

Remi

**Comment by mementum** [comment]
The latest release got new *function* aliases which should have been obvious before.

The previous code is a bit more elegant when expressed as:

```python
class Condition1(bt.Signal):
    def __init__(self)
        realsignal = self.data < bt.indicators.BollingerBands(period=15)
        self.lines.signal = bt.indicators.AnyN(realsignal, period=15)
```

Here `AnyN` serves the same purpose as the built-in `any`. It carries the suffix `N` to indicate the need to have a period.

There is also a `backtrader.Any` which is meant to be used during initialization with several lines objects.

**Comment by remroc** [comment]
Many thanks DRo :D

**Comment by remroc** [comment]
Hello DRo,

I have updated to bt 1.8.13.99 and tried AnyN but I receive :  
`AttributeError: 'module' object has no attribute 'AnyN'`

Do you have any idea what I should correct ?

For info, the code : 
`self.condition1_long = bt.indicators.AnyN(self.Highest - self.data.low > self.paramOne, period=self.params.period*3, plot=False, plotname='condition1_long')`

Many thanks,
Remi
