### ISSUE TITLE
[request] Sizer for portfolio rebalancing

### ISSUE THREAD

**Issue by cnimativ** [mementum/backtrader#134]
Dro,

Looking at the sizer portion of the documentation, what is the best way to implement a periodic rebalancing algorithm; i.e., say, periodic dividend reinvestment, or rolling the whole portfolio from SPY+QQQ into TLT+GLD?

For Quantopian/Zipline, there's a function `order_target_percent`.  What would be the equivalent on backtrader?

Thanks again for the great work!

HCL

**Comment by mementum** [comment]
*Sizers* have a different target which is auto-staking for `buy` and `sell`

*Rebalancing* as expressed above and in consonance with `order_target_percent` requires determining the current *position* and/or *portfolio value* to decide what to do (`buy` or `sell`) and the amount.

This is not the 1st time this is requested, so a small `zipline`-like API for this purpose is in the works.

**Comment by mementum** [comment]
This is now in the development branch. The sample seems to indicate it works ...

**Comment by mementum** [comment]
http://www.backtrader.com/posts/2016-09-02-target-orders/target-orders/
