### ISSUE TITLE
Modifying PandasData Class

### ISSUE THREAD

**Issue by dafyddd** [mementum/backtrader#136]
Hello, I'm having an issue with something that seems like it should be very simple. I have a Pandas dataframe that has the columns open, high, low, close, volume and vwap. I am having a hard time making the PandasData accept vwap. I always get the error AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_Abst' object has no attribute 'vwap'

I have tried many things, but I'm not able to get it to work. Do I need to modify the lines object within PandasData to accept lines that are not OHLC? 

Any help is appreciated. Currently I'm just using the openinterest line to put vwap, but I'd also like to add ask and bid lines which I can't do if I'm limited to only 6 lines. It was much simpler when I was trying to add arbitrary lines from a CSV file.

**Comment by mementum** [comment]
You would need the following:

  - Subclass `PandasData`
  - Add a `vwap` line with: `lines = ('vwap',)`
  - Add a `param` like `params = (('vwap', -1),)`

    `-1` tells the feed to auto find the actual location of `vwap`in the dataframe

  - Extend the `datafields` class attribute with `vwap` like: datafields = PandasData.datafields + ['vwap']`

The rest should be hopefully automated ...

**Comment by mementum** [comment]
Closed due to inactivity
