### ISSUE TITLE
Sharpe ratio too high?

### ISSUE THREAD

**Issue by drSeeS** [mementum/backtrader#137]
A very useful piece of software you are creating, well layed out, please keep up with this very good work!

I got a bit flabbergasted by looking at the actual values of sharpe ratios being calculated by cerebro. For example, in the docs (section 'Analyzer' / 'A Quick example') the sharpe ratio of the SMA_crossover strategy is reported as 11.64. Since this value is very high (anything above 4 might mean you found a holy grail), I decided to do a manual recap of the strategy, calculated actual holdings and the SR. My value for the annual sharpe ratio is 1.3 (still good, the years 2005/06 were good years for this asset. If you want to check and review my calculation please advise).

To rule out I got something wrong with the SMA strategy and the holdings, I caluclated a simple buy and hold strategy for this particular dataset using cerebro, yielding a SR of 9.26. Again, doing manual calculations I got an annual sharpe of 1.93 (using an annual risk free rate of 1% like you), which seems resonable.

Please bear with me since I was not able to fully get my head around the code in sharpe.py, but possibly the time scale of the return does not match the one of the volatility? (possibly returns of the entire period (>1 year) are divided by daily vola, hence vola is not scaled with the square root of time?).

(see for scaling, the use of log returns and also potential problems f.e. https://www.quantstart.com/articles/Sharpe-Ratio-for-Algorithmic-Trading-Performance-Measurement and http://quant.stackexchange.com/questions/7290/computing-the-sharpe-ratio)

**Comment by mementum** [comment]
The calculations inside *backtrader* may be wrong, but they seem to be right.

From the *quanstart* link:

> The ratio compares the mean average of the excess returns of the asset or strategy with the standard deviation of those returns. Thus a lower volatility of returns will lead to a greater Sharpe ratio, assuming identical returns

I have extracted the calculation from *backtrader* and put it isolated in a small sample which allows modifying the `riskfreerate`, the annual returns and should allow for a more easily read of the formulas.

```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
###############################################################################
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import itertools
import math
import operator
import sys


if sys.version_info.major == 2:
    map = itertools.imap


def average(x):
    return math.fsum(x) / len(x)


def variance(x):
    avgx = average(x)
    return list(map(lambda y: (y - avgx) ** 2, x))


def standarddev(x):
    return math.sqrt(average(variance(x)))


def run(pargs=None):
    args = parse_args(pargs)

    returns = [args.ret1, args.ret2]
    retfree = args.riskfreerate

    print('returns is:', returns, ' - retfree is:', retfree)

    # Directly from backtrader
    retfree = itertools.repeat(retfree)
    ret_free = map(operator.sub, returns, retfree)  # excess returns
    ret_free_avg = average(list(ret_free))  # mean of the excess returns
    print('returns excess mean:', ret_free_avg)
    retdev = standarddev(returns)  # standard deviation
    print('returns standard deviation:', retdev)
    ratio = ret_free_avg / retdev  # ratio of excess returns mean and std deviation
    print('Sharpe Ratio is:', ratio)


def parse_args(pargs=None):
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='Sample Sharpe Ratio')

    parser.add_argument('--ret1', required=False, action='store',
                        type=float, default=0.023286,
                        help=('Annual Return 1'))

    parser.add_argument('--ret2', required=False, action='store',
                        type=float, default=0.0257816485323,
                        help=('Annual Return 2'))

    parser.add_argument('--riskfreerate', required=False, action='store',
                        type=float, default=0.01,
                        help=('Risk free rate (decimal) for the Sharpe Ratio'))

    if pargs is not None:
        return parser.parse_args(pargs)

    return parser.parse_args()


if __name__ == '__main__':
    run()
```

The annual returns are the annual returns of the sample from the quickstart: 0.023286 (2.32826%) and 0.0257816485323 (2.57816485323%)

A sample run:

```
$ ./sratio.py
returns is: [0.023286, 0.0257816485323]  - retfree is: 0.01
returns excess mean: 0.0145338242661
returns standard deviation: 0.00124782426615
Sharpe Ratio is: 11.6473326096
```

The standard deviation between 0.0232 and 0.0257 is so small that it bumps the Sharpe Ratio to `11.64`

If one imagined that in those years it was possible to get a `3%` from the banks:

```
$ ./sratio.py --riskfreerate 0.03
returns is: [0.023286, 0.0257816485323]  - retfree is: 0.03
returns excess mean: -0.00546617573385
returns standard deviation: 0.00124782426615
Sharpe Ratio is: -4.38056534252
```

Suddenly the sky rocketing Sharpe Ratio has fallen through the floor.

The sample allows to specify the annual returns. If we pass `5` an `0.5`:

```
$ ./sratio.py --riskfreerate 0.03 --ret1 5.0 --ret2 0.5
returns is: [5.0, 0.5]  - retfree is: 0.03
returns excess mean: 2.72
returns standard deviation: 2.25
Sharpe Ratio is: 1.20888888889
```

We have a bumping 500% in year 1 and only 50% in year 2. But the standard deviation is enormous and the result is a good Sharpe Ratio of `1.20` but well below the `11.64`.

Another more realistic example going back to a `1%` risk free rate and `7%` and `0.5%` returns.

```
$ ./sratio.py --riskfreerate 0.01 --ret1 0.07 --ret2 0.005
returns is: [0.07, 0.005]  - retfree is: 0.01
returns excess mean: 0.0275
returns standard deviation: 0.0325
Sharpe Ratio is: 0.846153846154
```

This example wins more than the original example, but it has a `0.84` Sharpe Ratio because the standard deviation between `0.07` and `0.05` is huge in comparison with that of `0.0232` and `0.0257`.

As far as I understand the Sharpe Ratio this is not about the size of the winnings but about measuring if the winnings are achieved on a regular basis. That is: if you make every year exactly `2.5%` you would have a standard deviation of `0.0` and your Sharpe Ratio would be **INFINITE**. Someone else making a series of `0.10`, `0.15`, `0.50`, `0.05` would make far more money ... but would have a finite and low Sharpe Ratio because of the volatility of the winnings.

**Comment by drSeeS** [comment]
As you state correctly, if there was no variability in returns (the 2.5% flat every year), sharpe ratio would approach infinity (bad, but still not so bad because, at the same time, our idea of having a ‘risk adjusted’ return measure would be rendered useless, since there would simply be nothing in the equation being ever close to ‘risky’).
Sharpe Ratio measures the ‘risk adjusted excess return’, i.e., how much we make (in excess of the risk free rate) per one unit of risk we take. No risk, no measure.

I think I got the code (thanks to your bitesize chunks), so here are my two cents:

* Averaging returns *
If you have ‘typical’ returns, measured over a discrete period, and you want to average/cumulate them over time you would need to use the geometric mean in order to arrive at the appropriate average (i.e. . (1+r_avg) = (1+i_1)*(1+i_2)…), nasty stuff..). Simple averaging will not do (winning +50% and then loosing -50% will give you a total performance of -25%, not 0%).
To make life easier, use continuously compounded (or log) returns! This has a number of advantages:
One assumption underlying the sharpe ratio as a risk adjusted measure is normality of returns (although it would at least be defined for any return distribution). Log returns are closer to normally distributed and hence better suited. 
Normality is further crucial for being able to properly scale returns/std dev in time (we do it although it comes with a price tag attached, see the often cited paper by Lo (2002) The statistics of sharpe ratios, http://edge-fund.com/Lo02.pdf. Just never stop questioning ourselves).
And finally, who would have thought, those log returns have a nice property: cumulating or averaging returns over time simplifies to adding or arithmetically averaging individual returns. 

* Estimating standard deviation  *
from only two annual values like it is done in this example has two hefty caveats:
Firstly, results will be statistically extremely weak, ideally you should use 30 or more data points. Secondly, by compressing the time frame so radically before the actual calculation, you lose all the inter-year information about the actual movements of the asset, basically wiping out any of the up-and-then-down-moves (which very exactly leaves you with such small values for sd). Why throw all this information away?
Better calculate std dev from monthly or daily returns and then annualize it. If they are normally distributed, we can do so by multiplying with the square root of the time scaling factor (there are 252 trading days in one year: -> ann. Std. dev. =  daily std dev. * sqrt(252) ) 

* Estimating standard deviation 2 *
a small thing indeed but still there: while estimating the standard deviation you should not divide by N but by N-1 (why not use built-in functions anyway?)

I am unclear how you arrive at the annual returns you state from the quick start cross-over example (since mine, calculated manually, being 14.89% (2005) and 5.05% (2006) but I might have made mistakes in the SMA cross-over).
For a manual calculation, for the sake of simplicity, let’s just consider a simple buy and hold strategy (i.e., we look at the asset itself)

import pandas as pd
import numpy as np

data = pd.read_csv('Z:/.../backtrader/datas/2005-2006-day-001.txt', index_col=0, parse_dates=True)

#risk free rate, converted to log return
rf = 0.01
rf_log = np.log(1 + rf)

# daily discrete return
ret_d = data.Close / data.Close.shift(1) - 1

# transform to daily log returns
logret_d = np.log(1 + ret_d)

# to get the total return of the strategy, just add them (yeah, we know, no problem with log rets) 
logret_sum = logret_d.cumsum()

# last value: total cumulated return over the entire period
logret_total = logret_sum[-1] 

# scale it to annual (assuming 252 trading days a year) 
logret_annual = logret_total * np.sqrt(252 / len(logret_sum))

# standard deviation of daily log returns ...
stddev_d = logret_d.std() 

# ... scaled to annual
stddev_a = stddev_d * np.sqrt(252)

# sharpe ratio
SR = (logret_annual - rf_log) / stddev_a


SR here comes out with 1.7068 which, while looking at the chart, seems quite reasonable.

This sharp ratio we just calculated is on an annual basis. Since we can scale returns and std dev in time, why should we not be able to do the same with the entire sharpe ratio? With which factor? Well, since we used N for (log!!) returns and sqrt(N) for sd, it must be sqrt(N) (since N divded by sqrt(N) is again sqrt(N)).


This is also a nice piece I just stumbled across, on general issues with the SR:
https://www.crystalbull.com/sharpe-ratio-better-with-log-returns/

One other suggestion you could consider: in using the sharpe ratio we accept the standard deviation as a measure of the risk we exposure ourselves to. This means that we not only punish large downward movements, but also large moves upward. This is somewhat counter intuitive since we actually like up-moves (very much actually, much more than downward movements). For the SR both is equally bad. Therefore, an interesting measure which deals with this flaw could be the Sortino ratio which is basically equal to the SR, just any upward returns are set to zero before calculation, basically removing any positive jumps from the std dev calculation.

**Comment by mementum** [comment]
> -  estimating standard deviation 2 *
>     a small thing indeed but still there: while estimating the standard deviation you should not divide by N but by N-1 (why not use built-in functions anyway?)

This would apply (Bessel's correction) if the *returns* were a sample of the population. But in this case the population is complete. Two years and 2 returns.

> (why not use built-in functions anyway?)

You may be referring to the *statistics* module that as far as I know is available first with Python `3.4`. Unfortunately the way chosen by *Python* to move people away from `2.7` is to not make things available. Hence the need for home-cooked equivalents.

> I am unclear how you arrive at the annual returns you state from the quick start cross-over example (since mine, calculated manually, being 14.89% (2005) and 5.05% (2006) but I might have made mistakes in the SMA cross-over)

The `SharpeRatio` analyzer internally uses the `TimeReturn` analyzer Those values are the ones returned by the `TimeReturn` analyzer. (in the next comment there is a modified sample which has an independent `TimeReturn` and prints the values of the analyzer and the actual portfolio value each day.

  - 2005 Start: 10000.00 End: 10232.86 -> Return: 0.023286
  - 2006 Start: 10232.86 End: 10496.68 -> Return: 0.025782

Which are the same values returned by the `TimeReturn` analyzer

> Estimating standard deviation *
> from only two annual values like it is done in this example has two hefty caveats:
> Firstly, results will be statistically extremely weak, ideally you should use 30 or more data points. Secondly, by compressing the time frame so radically before the actual calculation, you lose all the inter-year information about the actual movements of the asset, basically wiping out any of the up-and-then-down-moves (which very exactly leaves you with such small values for sd). Why throw all this information away?

The documentation shows how to simply apply the `SharpeRatio` which is configured by default to use `TimeFrame.Years` as the default and the data sample only has 2 years. The documentation is not seeking the best possible `SharpeRatio`. It is obvious that a large sample is needed for a better statistic and evaluation.

No information is lost: the sample is explicitly requesting yearly returns. You can also tell the `SharpeRatio` to use `TimeFrame.Daily` and it will then consider then daily returns for the calculation.

> Better calculate std dev from monthly or daily returns and then annualize it. If they are normally distributed, we can do so by multiplying with the square root of the time scaling factor (there are 252 trading days in one year: -> ann. Std. dev. = daily std dev. * sqrt(252) )

The code in `SharpeRatio` tries already this if you tell `convertrate=False`. In this case the *returns* will be annualized, instead of downgrading the ratio to the given timeframe. This is possibly not the best naming convention.

All other points seem to refer to a *modernized* version of the `SharpeRatio` and not to the original definition which uses the arithmetic mean.

This doesn't grant modifying the `SharpeRatio` itself. A `SharpeRatioModern` can be added to avoid false expectations about what the `SharpeRatio` is returning.

**Comment by mementum** [comment]
```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-
###############################################################################
#
# Copyright (C) 2015, 2016 Daniel Rodriguez
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import datetime

import backtrader as bt


def runstrat(pargs=None):
    args = parse_args(pargs)

    # Create a cerebro
    cerebro = bt.Cerebro()

    if args.cash is not None:
        cerebro.broker.set_cash(args.cash)

    # Get the dates from the args
    fromdate = datetime.datetime.strptime(args.fromdate, '%Y-%m-%d')
    todate = datetime.datetime.strptime(args.todate, '%Y-%m-%d')

    # Create the 1st data
    data = bt.feeds.BacktraderCSVData(
        dataname=args.data,
        fromdate=fromdate,
        todate=todate)

    cerebro.adddata(data)  # Add the data to cerebro

    # Add the strategy
    cerebro.addstrategy(bt.strategies.SMA_CrossOver)

    tframes = dict(
        days=bt.TimeFrame.Days,
        weeks=bt.TimeFrame.Weeks,
        months=bt.TimeFrame.Months,
        years=bt.TimeFrame.Years)

    # Add the Analyzers
    cerebro.addanalyzer(bt.analyzers.TimeReturn,
                        timeframe=tframes[args.tframe])
    cerebro.addanalyzer(bt.analyzers.SharpeRatio,
                        timeframe=tframes[args.tframe])

    # Add a writer to get output
    cerebro.addwriter(bt.WriterFile, csv=args.writercsv, rounding=4)

    cerebro.run()  # And run it

    # Plot if requested
    if args.plot:
        pkwargs = dict(style='bar')
        if args.plot is not True:  # evals to True but is not True
            npkwargs = eval('dict(' + args.plot + ')')  # args were passed
            pkwargs.update(npkwargs)

        cerebro.plot(**pkwargs)


def parse_args(pargs=None):
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='TimeReturns and SharpeRatio')

    parser.add_argument('--data', '-d',
                        default='../../datas/2005-2006-day-001.txt',
                        help='data to add to the system')

    parser.add_argument('--cash', default=None, type=float, required=False,
                        help='Starting Cash')

    parser.add_argument('--fromdate', '-f',
                        default='2005-01-01',
                        help='Starting date in YYYY-MM-DD format')

    parser.add_argument('--todate', '-t',
                        default='2006-12-31',
                        help='Starting date in YYYY-MM-DD format')

    parser.add_argument('--writercsv', '-wcsv', action='store_true',
                        help='Tell the writer to produce a csv stream')

    parser.add_argument('--tframe', default='years', required=False,
                        choices=['days', 'weeks', 'months', 'years'],
                        help='TimeFrame for the Returns/Sharpe calculations')

    # Plot options
    parser.add_argument('--plot', '-p', nargs='?', required=False,
                        metavar='kwargs', const=True,
                        help=('Plot the read data applying any kwargs passed\n'
                              '\n'
                              'For example:\n'
                              '\n'
                              '  --plot style="candle" (to plot candles)\n'))

    if pargs is not None:
        return parser.parse_args(pargs)

    return parser.parse_args()


if __name__ == '__main__':
    runstrat()
```

```
 $./sma_crossover2.py --writercsv | less
===============================================================================
Id,2005-2006-day-001,len,datetime,open,high,low,close,volume,openinterest,SMA_CrossOver,len,Broker,len,cash,value,B
uySell,len,buy,sell,Trades,len,pnlplus,pnlminus
1,2005-2006-day-001,1,2005-01-03 23:59:59,2952.29,2989.61,2946.8,2970.02,0.0,0.0,SMA_CrossOver,1,Broker,1,10000.0,1
0000.0,BuySell,1,,,Trades,1,,
...
257,2005-2006-day-001,257,2005-12-30 23:59:59,3616.09,3616.09,3572.16,3578.93,0.0,0.0,SMA_CrossOver,257,Broker,257,6653.93,10232.86,BuySell,257,,,Trades,257,,
258,2005-2006-day-001,258,2006-01-02 23:59:59,3578.73,3605.95,3578.73,3604.33,0.0,0.0,SMA_CrossOver,258,Broker,258,6653.93,10258.26,BuySell,258,,,Trades,258,,
...
512,2005-2006-day-001,512,2006-12-29 23:59:59,4130.12,4142.01,4119.94,4119.94,0.0,0.0,SMA_CrossOver,512,Broker,512,
6376.74,10496.68,BuySell,512,,,Trades,512,,
...
          - Params: None
      *************************************************************************
      - Analyzers:
        .......................................................................
        - Value:
          - Begin: 10000.0
          - End: 10496.68
        .......................................................................
        - TimeReturn:
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          - Params:
            - timeframe: 7
            - compression: None
            - data: None
            - firstopen: True
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          - Analysis:
            - 2005-12-31: 0.0233
            - 2006-12-31: 0.0258
...
```

**Comment by drSeeS** [comment]
Thanks, I would very much like to play with this as well. Unfortunately, next two weeks from right now we will be out on vacation. If ok just leave this issue open (or maybe someone else wants to give his own two cents as well).

Unfortunately, we will never be able to observe the complete population of a return series, no matter how many observations you have (it would involve just any possibly generated outcome, parallel universes, future series ever existing). That's why this 'estimator' business and why this goddamn bloody overfitting problem even in long series. Hence, Bessel is a good appropriate choice (here the famous what-was-that-again-sentence: you only have n-1 independent residuals, hence max n-1 degrees of freedom).

**Comment by mementum** [comment]
Entire population when referring to the timeframe and available number of samples. They match in this scenario.

One of the targets of adding the declarative `params` to all classes in *backtrader* was to have easily add parameters to cover such case and have them clearly separated from the code.

Dividing by `N` or `N -1` can be worked out. It is for sure not a time critical operation.

**Comment by drSeeS** [comment]
Thanks for tackling this! Two more things possibly worth considering:

1) Scaling with the square root of time is obviously only defined for log returns, whereas the calculation in place scales the ratio and hence the geometric returns used therein (agreed that for small returns the difference is only of academic interest. But it will become quite substantial for larger returns and larger time period transformations).

If you want to stick to geometric returns for the SR calculation, you could follow the procedure mentioned by benjaminmgross at [stackexchange](http://quant.stackexchange.com/questions/7290/computing-the-sharpe-ratio) (giving 5 precise steps in his comment below answer 1, Feb 16 '13 at 12:45). Also not computationally expensive.

2) make sure enough data points are used for meaningful std dev and hence a meaningful SR
 - use daily (ar at least monthly) returns instead of annual returns as default input ([Sharpe (1994)](http://web.stanford.edu/~wfsharpe/art/sr/SR.htm#Sharpe75) stated himself: "To maximize information content, it is usually desirable to measure risks and returns using fairly short (e.g. monthly) periods. For purposes of standardization it is then desirable to annualize the results.")
 - allow calculating the SR only if at least a certain number of data points is available (possibly 15)

**Comment by drSeeS** [comment]
Thanks for tackling this! Two more things possibly worth considering:

1) Scaling with the square root of time is obviously only defined for log returns, whereas the calculation in place scales the ratio and hence the geometric returns used therein (agreed that for small returns the difference is only of academic interest. But it will become quite substantial for larger returns and larger time period transformations).

If you want to stick to geometric returns for the SR calculation, you could follow the procedure mentioned by benjaminmgross at [stackexchange](http://quant.stackexchange.com/questions/7290/computing-the-sharpe-ratio) (giving 5 precise steps in his comment below answer 1, Feb 16 '13 at 12:45). Also not computationally expensive.

2) make sure enough data points are used for meaningful std dev and hence a meaningful SR
 - use daily (ar at least monthly) returns instead of annual returns as default input ([Sharpe (1994)](http://web.stanford.edu/~wfsharpe/art/sr/SR.htm#Sharpe75) stated himself: "To maximize information content, it is usually desirable to measure risks and returns using fairly short (e.g. monthly) periods. For purposes of standardization it is then desirable to annualize the results.")
 - allow calculating the SR only if at least a certain number of data points is available (possibly 15)

**Comment by drSeeS** [comment]
Thanks for tackling this! Two more things possibly worth considering:

1) Scaling with the square root of time is obviously only defined for log returns, whereas the calculation in place scales the ratio and hence the geometric returns used therein (agreed that for small returns the difference is only of academic interest. But it will become quite substantial for larger returns and larger time period transformations).

If you want to stick to geometric returns for the SR calculation, you could follow the procedure mentioned by benjaminmgross at [stackexchange](http://quant.stackexchange.com/questions/7290/computing-the-sharpe-ratio) (giving 5 precise steps in his comment below answer 1, Feb 16 '13 at 12:45). Also not computationally expensive.

2) make sure enough data points are used for meaningful std dev and hence a meaningful SR
 - use daily (ar at least monthly) returns instead of annual returns as default input ([Sharpe (1994)](http://web.stanford.edu/~wfsharpe/art/sr/SR.htm#Sharpe75) stated himself: "To maximize information content, it is usually desirable to measure risks and returns using fairly short (e.g. monthly) periods. For purposes of standardization it is then desirable to annualize the results.")
 - allow calculating the SR only if at least a certain number of data points is available
