### ISSUE TITLE
Rounding data feeds

### ISSUE THREAD

**Issue by drSeeS** [mementum/backtrader#138]
Another question is about rounding prices of datafeeds. In the 'quickstart' it says 'The Data Feed provided by backtrade rounds the values down to 2 decimals after applying the adjusted close...' 

It is unclear to me if all feeds attached to cerebro generally will be rounded to 2 decimals? Or this was just the case with the files you are providing through github? In case this is a general feature: how should one deal f.e. with options on T-bill futures, which are quoted in 1/64 of a unit (rounding to two decimals would preserve the ordinal rank obviously, but would render calculating any positional values kind of obscure).

Again and still, nice piece, thanks for sharing!

**Comment by mementum** [comment]
This is only true for the `YahooFinanceCSVData` feed:

```
$ grep round *.py
yahoo.py:            self.lines.open[0] = round(self.lines.open[0] / adjfactor, 2)
yahoo.py:            self.lines.high[0] = round(self.lines.high[0] / adjfactor, 2)
yahoo.py:            self.lines.low[0] = round(self.lines.low[0] / adjfactor, 2)
yahoo.py:            self.lines.close[0] = round(adjustedclose, 2)
yahoo.py:            self.lines.volume[0] = round(self.lines.volume[0] / adjfactor, 2)
```

Which is the data feed referenced in the example. Being this from the very beginnings of *backtrader* it could be well worth to add a parameter to the data feed to decide whether to apply rounding and be it the case ... how many digits to keep.
