### ISSUE TITLE
OrderObserver  - TypeError:a float is required

### ISSUE THREAD

**Issue by xingjianpan** [mementum/backtrader#14]
Hi, 

I followed this [tutorial](http://www.backtrader.com/posts/2015-08-12/observers-and-statistics/#custom-orderobserver) and try to add OrderObserver to my strategy. And then I got an error when i run the script that says:

```shell
 TypeError:a float is required
```

it looks like order.created.price is None when the code was running. 
```python

            if order.status in [bt.Order.Accepted, bt.Order.Submitted]:
                print('Created Price %r' % order.created.price)
                self.lines.created[0] = order.created.price

            elif order.status in [bt.Order.Expired]:
                self.lines.expired[0] = order.created.price

```

In the strategy code, if i change it from 
```python
                        self.order = self.buy()
```

to 
```python
                        self.order = self.buy(price=self.data.close[0] * 1.0)
```
then the there will be no errors. 

I am using latest version of backtrader.(1.1.2.88)

Also i think there below  code 
```python
class MyStrategy(bt.Strategy):

    def start(self):

        mystats = open('mystats.csv', 'wb')
        mystats.write('datetime,drawdown, maxdrawdown\N')


    def next(self):
        mystats.write(self.data.datetime.date(0).strptime('%Y-%m-%d'))
        mystats.write(',%.2f' % self.stats.drawdown.drawdown[-1])
        mystats.write(',%.2f' % self.stats.drawdown.maxdrawdown-1])
        mystats.write('\n')
``` 
needs to be changed to 

```python
class MyStrategy(bt.Strategy):

    def start(self):

        self.mystats = open('mystats.csv', 'wb')
        self.mystats.write('datetime,drawdown, maxdrawdown\n')


    def next(self):
        self.mystats.write(self.data.datetime.date(0).strftime('%Y-%m-%d'))
        self.mystats.write(',%.2f' % self.stats.drawdown.drawdown[-1])
        self.mystats.write(',%.2f' % self.stats.drawdown.maxdrawdown-1])
        self.mystats.write('\n')
```
the changes are:
* strptime->strftime
* \N ->\n
* mystats->self.mystats

**Comment by mementum** [comment]
The typos will be corrected.

But the: "order.created.price" has the expected behavior.

If you issue a "Market" order, which you do when calling self.buy() with default parameters, the price is not set (i.e set to None), because the price is going to be 100% determined by the market.

Even if you set a price it will only be a reference for yourself, because the incoming data will be the one determining the price.

Your best bet: self.lines.created[0] = order.created.price or order.data.close[-1]

**Comment by xingjianpan** [comment]
Thanks!

 Below line works for me
```python
self.lines.created[0] =  order.data.close[-1]
````
when 
```python
  self.order = self.buy()
````
You might want to also include this change in the tutorial. 


however, do you think this is an issue for backtrader.order.Order class?
look at below code, it looks self.created.price will be None unless user set price in the code (ie. self.order = self.buy(price=self.data.close[0] * 1.0) ).  should self.created.price be given some default value like close price?

```python
    def __init__(self):
        self.ref = next(self.refbasis)

        if self.params.exectype is None:
            self.params.exectype = Order.Market

        self.status = Order.Submitted
        if not self.isbuy():
            self.params.size = -self.params.size
        self.created = OrderData(dt=self.data.datetime[0],
                                 size=self.params.size,
                                 price=self.params.price,
                                 pricelimit=self.params.pricelimit)

```

**Comment by mementum** [comment]
Release 1.1.3.88 sets the close price as reference for an order if no price was specified. This still plays no role in Market/Close orders and therefore should not be relied upon.
