### ISSUE TITLE
AnyN

### ISSUE THREAD

**Issue by remroc** [mementum/backtrader#144]
Hello DRo,

I have upgraded bt to 1.8.13.99 and tried AnyN ([described here](https://github.com/mementum/backtrader/issues/130)) but I receive :

**AttributeError: 'module' object has no attribute 'AnyN'**

Same for AllN. But SumN does work.

Do you have any idea what I should correct ?

For info, the code : 
```
self.condition1_long = bt.indicators.AnyN(some code here, period=15, plot=False, plotname='condition1_long')
```
Many thanks,
Remi

**Comment by mementum** [comment]
Rather than running against the current development code, `1.8.13.99` was checked out and the indicators are there. This code has worked as expected:

```
bt.indicators.AnyN(self.ppo < -2.75, period=20, plotname='zz', plot=False)
```

May the update didn't work as expected

**Comment by remroc** [comment]
It is my mystake DRo !

I was using bt samples after unzipping master-branch. As it was an older version without the AnyN, the imports were using the basicops.py of the unzipped folders and therefore were not finding the new features. After renaming the unzipped folder backtrader, the code can now use the new version which was correctly installed through pip. Sorry for that...

Please close this issue and thanks again for your time.

Remi
