### ISSUE TITLE
Plot with Minutes for 1 year data depth

### ISSUE THREAD

**Issue by remroc** [mementum/backtrader#148]
Hello DRo,

Is it possible to precise the DateFormatter of the plot. To be more precise, I am backtesting for 1 year a data with 1 minute bars. When looking at the plot, the x axis shows only the day : 
1 1 1 1 July 2 2 2 2.

Is it possible to change this format to : 1 July 15:30 1 July 15:35 1 July 15:40 ?

Many thanks for your help.

Cheers,

Remi

**Comment by mementum** [comment]
One of the most time consuming parts was to even get something sensible being displayed.

It it really a (long term) desire that improve that formatting for all timeframes. But at the moment some other priorities will not make this happen.

**Comment by mementum** [comment]
Plotting has been reworked for some other reasons and now the ticks will be automatically found by matplotlib. A format string can now be specified (which would fulfill the target from above).

For example:

```python
cerebro.plot(fmt_x_ticks='%H:%M:%S.%f'
```

http://backtrader.readthedocs.io/en/latest/plotting/plotting.html

**Comment by remroc** [comment]
Thanks DRo :)
