### ISSUE TITLE
Sharpe ratio too high

### ISSUE THREAD

**Issue by drSeeS** [mementum/backtrader#149]
Sorry for opening a new issue on that. Am unsure whether you saw the latest comment in #137 since the issue had been closed before adding it, I am not allowed to reopen it.

Btw, junajo10's comment in #147 points in the same direction (and concerning ratios, plenty had been implemented in empyrical, also the aforementioned 'Sortino ratio', f.e. :) )

Thanks mementum!

**Comment by mementum** [comment]
The messages are all read and ack'ed. Some of the *concerns* in #147 have already been covered with the  release of the `Returns` analyzer.

**Comment by mementum** [comment]
Managing in #147 if needed be
