### ISSUE TITLE
Pandas dataframe error: list index out of range

### ISSUE THREAD

**Issue by lxrz777** [mementum/backtrader#150]
Thank you for your awesome software shared with the community.  I have a little issue using pandas dataframe

When I try to execute the code from documentation with my dataframe I get the error:

Traceback (most recent call last):
  File "C:/MyProjects/Python/my_projects/PythonTrading/TradingPy/backtrader/examples/example2.py", line 122, in <module>
    data = bt.feeds.PandasData(dataname=ldf)
  File "C:\Soft\Dev\Python\Anaconda3\lib\site-packages\backtrader-1.8.14.99-py3.5.egg\backtrader\metabase.py", line 87, in __call__
  File "C:\Soft\Dev\Python\Anaconda3\lib\site-packages\backtrader-1.8.14.99-py3.5.egg\backtrader\metabase.py", line 77, in doinit
  File "C:\Soft\Dev\Python\Anaconda3\lib\site-packages\backtrader-1.8.14.99-py3.5.egg\backtrader\feeds\pandafeed.py", line 192, in __init__
IndexError: list index out of range

My data frame has 800 lines , here are the first two lines: 

Traceback (most recent call last):
                        open      low     high    close  volume
datetime                                                       
2016-04-11 00:05:00  2041.00  2038.50  2041.00  2039.25    2817
2016-04-11 00:10:00  2039.25  2039.25  2040.50  2040.00     757

Here the whole code I try to execute :+1: 

import datetime  # For datetime objects
import pandas as pd
import pandas.io.data as web
import datetime
import backtrader as bt
from data.data_handler import DataHandler
import datetime  # For datetime objects
import os.path  # To manage paths
import sys  # To find out the script name (in argv[0])

class TestStrategy(bt.Strategy):
    params = (
        ('exitbars', 20),
    )

    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close

        # To keep track of pending orders and buy price/commission
        self.order = None
        self.buyprice = None
        self.buycomm = None

    def notify_order(self, order):
        if order.status in [order.Submitted, order.Accepted]:
            # Buy/Sell order submitted/accepted to/by broker - Nothing to do
            return

        # Check if an order has been completed
        # Attention: broker could reject order if not enougth cash
        if order.status in [order.Completed, order.Canceled, order.Margin]:
            if order.isbuy():
                self.log(
                    'BUY EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                    (order.executed.price,
                     order.executed.value,
                     order.executed.comm))

                self.buyprice = order.executed.price
                self.buycomm = order.executed.comm
            else:  # Sell
                self.log('SELL EXECUTED, Price: %.2f, Cost: %.2f, Comm %.2f' %
                         (order.executed.price,
                          order.executed.value,
                          order.executed.comm))

            self.bar_executed = len(self)

        # Write down: no pending order
        self.order = None

    def notify_trade(self, trade):
        if not trade.isclosed:
            return

        self.log('OPERATION PROFIT, GROSS %.2f, NET %.2f' %
                 (trade.pnl, trade.pnlcomm))

    def next(self):
        # Simply log the closing price of the series from the reference
        self.log('Close, %.2f' % self.dataclose[0])

        # Check if an order is pending ... if yes, we cannot send a 2nd one
        if self.order:
            return

        # Check if we are in the market
        if not self.position:

            # Not yet ... we MIGHT BUY if ...
            if self.dataclose[0] < self.dataclose[-1]:
                # current close less than previous close

                if self.dataclose[-1] < self.dataclose[-2]:
                    # previous close less than the previous close

                    # BUY, BUY, BUY!!! (with default parameters)
                    self.log('BUY CREATE, %.2f' % self.dataclose[0])

                    # Keep track of the created order to avoid a 2nd order
                    self.order = self.buy()

        else:

            # Already in the market ... we might sell
            if len(self) >= (self.bar_executed + self.params.exitbars):
                # SELL, SELL, SELL!!! (with all possible default parameters)
                self.log('SELL CREATE, %.2f' % self.dataclose[0])

                # Keep track of the created order to avoid a 2nd order
                self.order = self.sell()

if __name__ == '__main__':
    dt_hd = DataHandler()
    dt_hd.load_data("ES")

    # Create a cerebro entity
    cerebro = bt.Cerebro()
    # Add a strategy
    cerebro.addstrategy(TestStrategy)

    ldf = dt_hd.df
    ldf.drop(['id', 'symbol', 'up', 'down'], axis=1, inplace=True)
    ldf.rename(columns={'time': 'datetime'}, inplace=True)
    ldf=ldf.set_index('datetime')
    #ldf.reset_index(level=0, inplace=True)
    print(ldf)

    data = bt.feeds.PandasData(dataname=ldf)

    # Add the Data Feed to Cerebro
    cerebro.adddata(data,dataname='datetime')

    # Set our desired cash start
    cerebro.broker.setcash(100000.0)
    # Add a FixedSize sizer according to the stake
    cerebro.addsizer(bt.sizers.FixedSize, stake=10)
    # Set the commission - 0.1% ... divide by 100 to remove the %
    cerebro.broker.setcommission(commission=0.001)

    # Print out the starting conditions
    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

    # Run over everything
    cerebro.run()

    # cerebro.plot(style='bar')

    # Print out the final result
    print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

**Comment by lxrz777** [comment]
I've just tried this one and it's the same issue:

df1 = pd.DataFrame({'Date': ['2016-04-11', '2016-04-12', \
                   '2016-04-13','2016-04-14', '2016-04-15', \
                   '2016-04-16'],
                   'Open': [1.1, 2.7, 5.3,2,2,2], 
                   'High': [3.3, 5.4, 1.5,2,2,2],
                   'Low': [4, 7, 15,2,2,2],
                   'Close': [2, 10, 9,2,2,2],                    
                   'Volume': [4, 7, 15,2,2,2],  
                   })
    df1.set_index('Date',inplace=True)
    print(df1)        
        
    data= bt.feeds.PandasData(dataname=df1)

**Comment by mementum** [comment]
The problem is that your *dataframe* has no `openinterest` field and you are not telling that to the data feed.

Quoted here from the docs at: http://backtrader.readthedocs.io/en/latest/dataautoref.html

>     '''
>     Uses a Pandas DataFrame as the feed source, using indices into column
>     names (which can be "numeric")
> 
>     This means that all parameters related to lines must have numeric
>     values as indices into the tuples
> 
>     Note:
> 
>       - The ``dataname`` parameter is a Pandas DataFrame
> 
>       - Values possible for datetime
> 
>         - None: the index contains the datetime
>         - -1: no index, autodetect column
>         - >= 0 or string: specific colum identifier
> 
>       - For other lines parameters
> 
>         - None: column not present
>         - -1: autodetect
>         - >= 0 or string: specific colum identifier
>     '''
> 

You would have to: ```data= bt.feeds.PandasData(dataname=df1, openinterest=None)```

**Comment by lxrz777** [comment]
Thank you momentum! I it works well with this param
