### ISSUE TITLE
python.exe crashes on one of the examples

### ISSUE THREAD

**Issue by kszynkar** [mementum/backtrader#151]
Hi,

Hopefully I'm not doing something stupid here, but python.exe crashes when I try the code in the "Visual Inspection: Plotting" of the Quickstart section in the manual. I get a python.exe has stopped working message from Windows. The line it crashes on is the "cerebro.plot()" line. All the examples before this in the Quickstart section worked perfectly fine. I'm running Python 3.4.5 and have matplotlib installed.

Thanks

**Comment by kszynkar** [comment]
My matplotlib version is 1.5.1

**Comment by kszynkar** [comment]
upgrading to 1.5.3 seems to have resolved the issue

**Comment by mementum** [comment]
Most tests are being run with `1.5.0` (under Python `2.7`) or `1.5.2` (under Python `3.5`). A crash of the `python` interpreter is well beyond push of the pure python usage of matplotlib made by `backtrader`

Following the resolution via an update to `1.5.3` can only indicate that something is wrong with `1.5.1`

Glad to know it works for you
