### ISSUE TITLE
LinePlotterIndicator

### ISSUE THREAD

**Issue by remroc** [mementum/backtrader#156]
Hello DRo,

I hope you are well...

I would like to use the LinePlotterIndicator function but I can't find it in the code.

Thanks for your help...

Have a good week end,

Rémi

**Comment by mementum** [comment]
This one got under the radar. It was included in a development stage and somehow missed making it into the code (even if the doc did)

An old test for it has been located. Some cleaning and it will go in (it will first be posted here as a snippet)

**Comment by remroc** [comment]
Many thanks DRo

Have a great week end :)

**Comment by mementum** [comment]
```python
class MetaLinePlotterIndicator(bt.Indicator.__class__):
    def donew(cls, *args, **kwargs):
        lname = kwargs.pop('name')
        name = cls.__name__

        lines = getattr(cls, 'lines', bt.Lines)
        cls.lines = lines._derive(name, (lname,), 0, [])

        plotlines = bt.AutoInfoClass
        newplotlines = dict()
        newplotlines.setdefault(lname, dict())
        cls.plotlines = plotlines._derive(name, newplotlines, [], recurse=True)

        # Create the object and set the params in place
        _obj, args, kwargs =  \
            super(MetaLinePlotterIndicator, cls).donew(*args, **kwargs)

        _obj.owner = _obj.data.owner._clock
        _obj.data.lines[0].addbinding(_obj.lines[0])

        # Return the object and arguments to the chain
        return _obj, args, kwargs


class LinePlotterIndicator(bt.with_metaclass(MetaLinePlotterIndicator,
                                             bt.Indicator)):
    pass
```

It will be reachable as `backtrader.LinePlotterIndicator` in the upcoming release. A sample (which will also be included) Most of the sample simply takes care of parsing the arguments to the script.

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import datetime

import backtrader as bt


class St(bt.Strategy):
    params = (
        ('ondata', False),
    )

    def __init__(self):
        if not self.p.ondata:
            a = self.data.high - self.data.low
        else:
            a = 1.05 * (self.data.high + self.data.low) / 2.0

        b = bt.LinePlotterIndicator(a, name='hilo')
        b.plotinfo.subplot = not self.p.ondata


def runstrat(pargs=None):
    args = parse_args(pargs)

    cerebro = bt.Cerebro()

    dkwargs = dict()
    # Get the dates from the args
    if args.fromdate is not None:
        fromdate = datetime.datetime.strptime(args.fromdate, '%Y-%m-%d')
        dkwargs['fromdate'] = fromdate
    if args.todate is not None:
        todate = datetime.datetime.strptime(args.todate, '%Y-%m-%d')
        dkwargs['todate'] = todate

    data = bt.feeds.BacktraderCSVData(dataname=args.data, **dkwargs)
    cerebro.adddata(data)

    cerebro.addstrategy(St, ondata=args.ondata)
    cerebro.run(stdstats=False)

    # Plot if requested
    if args.plot:
        pkwargs = dict(style='bar')
        if args.plot is not True:  # evals to True but is not True
            npkwargs = eval('dict(' + args.plot + ')')  # args were passed
            pkwargs.update(npkwargs)

        cerebro.plot(**pkwargs)


def parse_args(pargs=None):
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='Fake Indicator')

    parser.add_argument('--data', '-d',
                        default='../../datas/2005-2006-day-001.txt',
                        help='data to add to the system')

    parser.add_argument('--fromdate', '-f',
                        default=None,
                        help='Starting date in YYYY-MM-DD format')

    parser.add_argument('--todate', '-t',
                        default=None,
                        help='Starting date in YYYY-MM-DD format')

    parser.add_argument('--ondata', '-o', action='store_true',
                        help='Plot fake indicator on the data')

    parser.add_argument('--plot', '-p', nargs='?', required=False,
                        metavar='kwargs', const=True,
                        help=('Plot the read data applying any kwargs passed\n'
                              '\n'
                              'For example:\n'
                              '\n'
                              '  --plot style="candle" (to plot candles)\n'))

    if pargs is not None:
        return parser.parse_args(pargs)

    return parser.parse_args()


if __name__ == '__main__':
    runstrat()
```

**Comment by remroc** [comment]
Many Thanks DRo for the release :+1: 

I wanted to use LinePlotterIndicator as an alternative solution to plot a variable which is calculated in the next part of the strategy. This variable takes value 0 and 1. I was not able to initialize it as an indiator because I need to reinit this pseudo-indicator based on performance of actual indicators : begining of trading session, when other indicator are themselves activated, etc

How to use PlotLineIndicator within the next part ?

For the moment I receive following error :

`  File "C:\Dev\Anaconda2\lib\site-packages\backtrader\indicator.py", line 53, in __call__
    return super(MetaIndicator, cls).__call__(*args, **kwargs)
  File "C:\Dev\Anaconda2\lib\site-packages\backtrader\metabase.py", line 85, in __call__
    _obj, args, kwargs = cls.donew(*args, **kwargs)
  File "C:\Dev\Anaconda2\lib\site-packages\backtrader\indicator.py", line 156, in donew
    _obj.owner = _obj.data.owner._clock
  File "C:\Dev\Anaconda2\lib\site-packages\backtrader\lineseries.py", line 426, in __getattr__
    return getattr(self.lines, name)
AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_Abst' object has no attribute 'owner'`

Many thanks for your help,

Rémi

**Comment by mementum** [comment]
A *variable* is not a *line* and hence the error, because `LinePlotterIndicator` is meant to wrap a single lazily evaluated `line` object and make it look like something which resemples a *data feed*/*indicator*, which is meant to be plotted.

With regards to the *variable*, it may be possible to wrap it in an Indicator (saying this without knowing the actual use case/scenario):

  - Create an indicator that takes a callable
  - This callable puts the value of the variable in the `line` defined inside the indicator

At the beginning `NaN` or maybe `0.0` may be returned.

Why a callable? Take into account that if the variable is of numeric type, the indicator will simply get the value. A `dict` or a `list` could also do the trick, because the indicator would keep a reference to the object.

**Comment by mementum** [comment]
Closing after 10 days. Add a message if needed be.
