### ISSUE TITLE
example code in the documentation directory

### ISSUE THREAD

**Issue by OpenTrading** [mementum/backtrader#16]
There are a number of problems with the example code in the
documentation directory, which is a pity because it's a logical
place for someone to start when they're learning the package:
```
cd docs
```

1) Some of the paths to the data files are wrong:
```
grep '\.\./datas/' *py \
   | sed -e 's/:.*//' | uniq |while read file;do \
   mv -i $file $file.dst; \
   sed -e 's@\.\./datas/@../samples/datas/@' < $file.dst > $file ; \
   done
```

2) The data file goog.fd is not checked in:
```
grep goog.fd *.py
find .. -type f -name goog.fd
```
3) I'm getting 3 different errors in the plotting using matplotlib-1.3.1

You can easily test the documentation examples with this incantation:
```
grep '__main__' *py | \
    sed -e 's@:.*@@' | \
    while read file ; do \
    python $file ; \
    echo $file ; \
    done
```

**Comment by mementum** [comment]
1) The ".py" files in the documentation directory were intended for documentation purposes by means of literal inclusion (partial or complete) in the corresponding .rst files. Making them directly callable is a plus.

2) Can't do. Won't do. The goog.fd file belongs to the VisualChart package and I have no license for the distribution of those files. The corresponding documentation bit is meant as an example of how to develop a binary data source. VisualChart can be downloaded free of charges.

3) The documentation states that matplotlib >= 1.4.1 is needed.

http://www.backtrader.com/posts/2015-08-24/data-multitimeframe/
