### ISSUE TITLE
Data-dependent minimum periods for indicators?

### ISSUE THREAD

**Issue by jkleint** [mementum/backtrader#165]
Is it possible to create an indicator which does not know in advance how many warm-up bars it will need?  For instance, say you wanted to take a simple moving average of the last 20 upticks only; is this possible?  So for each bar, you only add the close to the SMA if the close was greater than the previous close.  Since you don't know when upticks will come in advance (and in fact you may never get enough upticks to create the indicator), it's not really possible to say when the indicator will be ready.  

Separate but related question: If you have several indicators with different minimum periods, but you want to start getting data out of them (having `next()` called) when *any* indicator has data, rather than *all* are ready, is this possible?  (The others would output NaN or something.)

**Comment by mementum** [comment]
The warm-up phase, or minimum period, is meant as a safeguard to avoid having a strategy kicking in too early. This is pre-calculated for the indicators and passed on to the strategy, which will first call its `next` method when all indicators are ready.

In the case of the described indicators, last 20 upticks, the period is undetermined. There are two options for this:

  - Wait until `backtrader` comes up with an integrated approach for such indicators.

or

  - Develop the indicator with a minimum period of `1` (the default actually)

    In this case the indicator will, most likely, produce an initial streak of `NaN` values and the strategy needs an initial check in `next` to bail out if the given indicator hasn't yet produced a non-`NaN` value (check with either `math.isnan` or with `variable != variable`.

> Separate but related question: If you have several indicators with different minimum periods, but you want to start getting data out of them (having next() called) when any indicator has data, rather than all are ready, is this possible? (The others would output NaN or something.)

Yes. The strategy (just like indicators) has a `prenext` method which is called until the time comes to call `next`. It is the place to get those values. Or you may simply call `next` from `prenext`
