### ISSUE TITLE
Enumerate open orders?

### ISSUE THREAD

**Issue by jkleint** [mementum/backtrader#168]
Is there a method to get all open orders, or at least get the most current status for a given order, or must you track their status manually?

**Comment by mementum** [comment]
There is no specific order management API.

The internal broker has a member attribute named: `pending` which contains the orders which are still alive and pending complete execution.

Such an API would probably be a good idea (will have to be compatible with the actual live brokers)

The `buy`, `sell`, `close` and `order_target_xxx` methods all return the created order.

**Comment by mementum** [comment]
In a strategy use: `openorders = self.broker.get_orders_open()`

**Comment by mementum** [comment]
will be in next release
