### ISSUE TITLE
numpy.bool_ error in bbroker.py

### ISSUE THREAD

**Issue by JoonHRo** [mementum/backtrader#170]
Hi mementum, 
Running codes via backtrader time to time yield in a type error in bbroker.py:
```TypeError: __bool__ should return bool, returned numpy.bool_```

I have no idea why this is not the case for every run but usually when the starting cash is on the lower end. 
I am pasting the error messages in whole in below for your reference. Do you think there's a workaround to avoid such errors? 

```
     85     # Run over everything
     86     cerebro.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio')
---> 87     results = cerebro.run()
     88     strat = results[0]
     89     pyfoliozer = strat.analyzers.getbyname('pyfolio')

C:\Anaconda3\lib\site-packages\backtrader\cerebro.py in run(self, **kwargs)
    787             # let's skip process "spawning"
    788             for iterstrat in iterstrats:
--> 789                 runstrat = self.runstrategies(iterstrat)
    790                 self.runstrats.append(runstrat)
    791         else:

C:\Anaconda3\lib\site-packages\backtrader\cerebro.py in runstrategies(self, iterstrat, predata)
    900                 self._runonce_old(runstrats)
    901             else:
--> 902                 self._runonce(runstrats)
    903         else:
    904             if self.p.oldsync:

C:\Anaconda3\lib\site-packages\backtrader\cerebro.py in _runonce(self, runstrats)
   1226                     self._plotfillers[i].append(slen)
   1227 
-> 1228             self._brokernotify()
   1229             if self._event_stop:  # stop if requested
   1230                 return

C:\Anaconda3\lib\site-packages\backtrader\cerebro.py in _brokernotify(self)
    967         notification to the strategy
    968         '''
--> 969         self._broker.next()
    970         while True:
    971             order = self._broker.get_notification()

C:\Anaconda3\lib\site-packages\backtrader\brokers\bbroker.py in next(self)
    724 
    725             # futures change cash every bar
--> 726             if pos:
    727                 comminfo = self.getcommissioninfo(data)
    728                 self.cash += comminfo.cashadjust(pos.size,

TypeError: __bool__ should return bool, returned numpy.bool_
```

**Comment by mementum** [comment]
This is for sure not *in* bactrader. The error is: `TypeError: __bool__ should return bool, returned numpy.bool_`

And there is no usage of `numpy` in backtrader. 

The actual code in `bbroker.py`

```
C:\Anaconda3\lib\site-packages\backtrader\brokers\bbroker.py in next(self)
    724 
    725             # futures change cash every bar
--> 726             if pos:
    727                 comminfo = self.getcommissioninfo(data)
    728                 self.cash += comminfo.cashadjust(pos.size,
```

And the responsible code in `Position` is:

```python
    def __bool__(self):
        return self.size != 0

    __nonzero__ = __bool__
```

If we assume that `pos` is still a `Position` instance, then the logical conclusion is that something has overwritten the `size` member attribute with `numpy.bool_` and apparently a `self.size != 0` comparison returns a `numpy.bool_` rather than a `bool`

**Comment by mementum** [comment]
Notice the error indicates `numpy.bool_` and not `numpy.bool`. Subject changed accordingly.

**Comment by JoonHRo** [comment]
Thanks for the quick response. There's part of the code that I use numpy's functions and I am wondering if somehow the default for boolean variables becomes numpy's? Not sure if this is a possibility... surely, I have not tried to mend the characteristics of the size member of the position instance in my code.

**Comment by mementum** [comment]
`self.size` may have been overwritten with something similar like `numpy.int_` and hence the return of a `numpy.bool_` in the comparison

This could be a chain of events in which `buy` and/or `sell` are getting a `numpy.int_` as the stake and each and every arithmetic calculation inside the platform is yielding a `numpy.int_`.

Until Python complains that it is expecting a `bool` in `__bool__`

**Comment by JoonHRo** [comment]
I see - that makes awfully good sense. Will re-assess my codes with that in mind. I think I may have over used the int() and round() simultaneously...

**Comment by mementum** [comment]
In relase 1.9.9.99 there is commit to force a bool out of the comparison `self.size != 0`. This should correct  the situation

**Comment by mementum** [comment]
Should it not alleviate the situation add a comment to this same issue.
