### ISSUE TITLE
Potential bug: UnboundLocalError 

### ISSUE THREAD

**Issue by kizzx2** [mementum/backtrader#174]
This line seems to be referencing `slen` before it is defined.

https://github.com/mementum/backtrader/blob/7323e5c406cfe48c6fdfc5c36fedebf7996653db/backtrader/cerebro.py#L1143

For reproduction step see https://github.com/mementum/backtrader/issues/172#issuecomment-254991126

**Comment by mementum** [comment]
This is already mentioned in the discussion in #172 as the bug related to plotting, leftover from the data synchronization change from `1.8.x` to `1.9.x`
