### ISSUE TITLE
Problem with new release

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#176]
I have updated to new release, and now my code is showing this message:

I am using Pivot Point indicator and the attributte; `cerebro.run(runonce=False)`
```
Traceback (most recent call last):
  File "FxPivotPoint.py", line 432, in <module>
    results = cerebro.run(runonce=False)
  File "build\bdist.win-amd64\egg\backtrader\cerebro.py", line 788, in run
  File "build\bdist.win-amd64\egg\backtrader\cerebro.py", line 906, in runstrate
gies
  File "build\bdist.win-amd64\egg\backtrader\cerebro.py", line 1185, in _runnext

  File "build\bdist.win-amd64\egg\backtrader\cerebro.py", line 1089, in _next_wr
iters
  File "build\bdist.win-amd64\egg\backtrader\strategy.py", line 379, in getwrite
rvalues
  File "build\bdist.win-amd64\egg\backtrader\strategy.py", line 379, in <lambda>

  File "build\bdist.win-amd64\egg\backtrader\linebuffer.py", line 162, in __geti
tem__
IndexError: array index out of range
```

**Comment by junajo10** [comment]
I have had to set : cerebro = bt.Cerebro(runonce=False,oldsync=True)    

I am using Pivot Point yesterday : resampling 1 day
 o = self.data.open(-1)
        h = self.data.high(-1)  # current high
        l = self.data.low(-1)  # current high
        c = self.data.close(-1)  # current high

And normal data resampling 240 min

If i don´t set runonce=False,oldsync=True. The code doesn´t work.

How can i update to the new Data Synchronization to cover my case?

Rgds,
JJ

**Comment by mementum** [comment]
Using `runonce=False` is a *MUST* when mixing timeframes and indicators.

  - http://backtrader.readthedocs.io/en/latest/mixing-timeframes/indicators-mixing-timeframes.html?highlight=pivotpoint

And `PivotPoint` is an indicator which by definition mixes timeframes.

The `mixing-timeframes.py` sample still works (it needs full indicator coupling for plotting though). This sample was long before any data synchronization changes where done and works flawlessly. The sample uses of course the already, long ago, built-in `PivotPoint` indicator.

It is unclear what this means:

> ```
> o = self.data.open(-1)
> h = self.data.high(-1)  # current high
> l = self.data.low(-1)  # current high
> c = self.data.close(-1)  # current high
> ```

And what exactly

> Pivot Point yesterday resampling 1 day*

also means

**Comment by junajo10** [comment]
Hi,

Sorry for my former message.
Pivot Point yesterday si:
class PivotPoint1(bt.Indicator):
    lines = ('p', 's1', 's2', 'r1', 'r2',)

    def __init__(self):
        **h = self.data.high(-1)  # previous high
        l = self.data.low(-1)  # previous low
        c = self.data.close(-1)  # previous close**

        self.lines.p = p = (h + l + c) / 3.0

        p2 = p * 2.0
        self.lines.s1 = p2 - h  # (p x 2) - high
        self.lines.r1 = p2 - l  # (p x 2) - low

        hilo = h - l
        self.lines.s2 = p - hilo  # p - (high - low)
        self.lines.r2 = p + hilo  # p + (high - low)

Resampling 1 day is that i have resampled my tick data to bars 1 day:
Tick data:
#RIC	Dat	Time	Type	Open	High	Low	Last	Volume	Open Interest
XX	11/9/2013	1:47:11	Trade	97	97	97	97	1	0
XX	11/9/2013	2:33:54	Trade	99.9	99.9	99.9	99.9	0.1	0
XX	11/9/2013	2:34:29	Trade	99.9	99.9	99.9	99.9	0.1	0
XX	11/9/2013	5:22:38	Trade	98.2	98.2	98.2	98.2	0.1	0
XX	11/9/2013	6:50:23	Trade	96.91	96.91	96.91	96.91	0.5	0
XX	11/9/2013	6:50:23	Trade	96.9	96.9	96.9	96.9	0.5	0
XX	11/9/2013	9:41:11	Trade	96.8	96.8	96.8	96.8	0.25	0
XX	11/9/2013	11:22:34	Trade	96.75	96.75	96.75	96.75	0.5	0
XX	13/09/2013	13:16:36	Trade	96	96	96	96	0.01	0
XX	13/09/2013	13:17:15	Trade	96.99	96.99	96.99	96.99	0.00987833	0
XX	13/09/2013	13:18:33	Trade	96	96	96	96	0.011	0

to:
XX 13/09/2013 Trade ......


I am going to review the example mixing-timeframes.py

Thanks a lot

Rgds,
JJ

**Comment by mementum** [comment]
The `-1` (or yesterday as indicated above) was only a sample `PivotPoint` indicator during the development given the confusion in the description of the actual formulas.

The actual `PivotPoint` used the current prices and the indicator is in the list of built-in indicators.

In any case and should this have had anything to do with it, check the newest release `1.9.10.99` which has added extra considerations for the case in which multiple timeframes are mixed (especially when resampling/replaying)

**Comment by junajo10** [comment]
I have updated the newest release 1.9.10.99. It is working well. 
My advice is to use PivotPoint with data of yesterday and mixed with others indicators calculated with today intraday data (15min,30min....)

Rgds,
JJ
