### ISSUE TITLE
Data Clone feed between 1.9.12.99 and 1.9.13.102 because of replay change

### ISSUE THREAD

**Issue by joequant** [mementum/backtrader#181]
I have some filters that are breaking between 1.9.12.99 and 1.9.13.102

Just figured out that this was the problem and am trying to figure out what is broken.  Where there any intentional breaking changes?

**Comment by joequant** [comment]
This system that is breaking is github joequant/sptrader and the specific filter that seems to be behaving badly is 

https://github.com/joequant/sptrader/blob/master/sptrader/jitter.py
The filter rounds things off to the nearest minute.

Any information that you can provide could be useful.  Sorry for not putting together a proper bug report, but I've got a trader breathing down my neck.  I'm setting up a package to use 1.9.12.99 to make him happy, and then I'll dig deeper.

**Comment by joequant** [comment]
The issue appears to be 

https://github.com/mementum/backtrader/commit/77ce17a7e47abbc15d76da439488c9e5ab9e9dfb

I have a custom feed which either pulls in a static file or scans it for updates

https://github.com/joequant/sptrader/blob/master/sptrader/spfeed.py

and it is pulling data through

https://github.com/joequant/sptrader/blob/master/sptrader/jitter.py

That commit somehow changes things so that it doesn't quite work.  Would appreciate any ideas on how to fix.

**Comment by mementum** [comment]
The aforementioned commit is a *last minute* check to catch datas which may have gotten a filter added which *replays* but doesn't do it through the standard call `cerebro.replaydata`.

An example of such filter is `DayStepsFilter` (which replays a bar in 2 parts: `OHL` + `C`)

If `_doreplay` is set to `True` this happens:

```python
        if self._doreplay:
            # preloading is not supported with replay. full timeframe bars
            # are constructed in realtime
            self._dopreload = False
```

Which simply disables preloading.

Additionally

```python
                strat.qbuffer(self._exactbars, replaying=self._doreplay)
```

which ends up adding an extra position to the internal buffers to allow replaying (and only has effect when `exactbars != 0`)

A quick inspection of the code pointed to you in the links shows no traces of `replaying` being set to `True` in the data feed, i.e.: the pointed commit shouldn't have any effect in your code.

In any case and without knowing how the filter is *breaking* it is rather difficult to understand what could be causing the trouble

**Comment by joequant** [comment]
Thanks.  That was very helpful.  Just knowing that it's not supposed to change anything is useful.  I'll put a lot of debug code to see what the feed is doing that's causing things to change.

**Comment by joequant** [comment]
OK.  I'm starting to see what is happening.

My algorithm has two feeds.  One is a tick feed, and another uses DataClone to do resampling, and compares the current tick price with various candles.

Before the change, _doreplay was not activated, but it's seeing a "replaying" flag in the DataClone.  At that point it turns _doreplay on and you end up with bad behavior.

Also, is this the right way of doing this?  What I'm doing is to look at the 5 minute candles which sets up trigger prices for the ticks.  I have two data feeds.  One tick feed, and one DataClone feed.

**Comment by mementum** [comment]
It seems that the `resampling` flag in the feed is being set manually during the creation of the `DataClone`. Because `DataClone` does not do it by itself. And this data clone is being used to manually implement resampling rather than going through the standard `cerebro.resampledata`

Without knowing in detail what's actually going wrong, resampling is not the same thing as replaying, and they seemed to be mixed in the explanation above.

In any case and if you really need the `resampling` flag you could disable `resampling` in your custom Data Feed and reactivate it during the `start` method of the feed. This prevents `Cerebro` from evaluating the feed as one that needs to disable *preloading*

**Comment by joequant** [comment]
OK.  Thanks.  I'll look at this in more detail.  I suspect that I'm not
calling the arguments correctly.

So to step back.

I have a tick data feed.  I want to generate candles for that data feed at
5 minute intervals, and then compare the candles with the ticks.  What's
the correct way of doing this?

**Comment by mementum** [comment]
This???
````
cerebro.resampledata(data, timeframe=backtrader.TimeFrame.Minutes, compression=5)
```

*"compare the candles with the ticks"* is a broad expression.

  - Compare 1 bar with 5000 ticks?
  - What's is actually being compared?
  - What is the purpose of the comparison?

Those questions can only be answered by the one comparing the two.

**Comment by joequant** [comment]
You take a look at the two previous five-minute bars, and the high and low
prices of those bars.  You then come up with an equation that comes up with
a range and then execute an order if the ticks move outside the range which
is calculated from the high-low values of the two previous bars.

**Comment by mementum** [comment]
Why can't you do that in the `next` method of the strategy? The resampled data is there and the tick data is also there.

**Comment by joequant** [comment]
I am doing the comparison in the next method of the strategy, but I'm
giving the strategy two data feeds.  One contains the tick data, and the
other contains the tick data that has be resampled to five minute bars.

This might not be the right way of doing this.

**Comment by mementum** [comment]
Sorry, but the problem seems to originate because you are manually using a `DataClone` and setting the `replaying` flag (why?). Addtionally you modify the timestamp of the feed in the filter above which seems to have nothing to do with resampling actually.

It is obvious from that that you are not using `cerebro.resampledata` to end up with 5-minutes bars. The docs already contain information on how to work with resampled. For example:

  - http://backtrader.readthedocs.io/en/latest/data-resampling/data-resampling.html?highlight=resampledata
  - http://backtrader.readthedocs.io/en/latest/mixing-timeframes/indicators-mixing-timeframes.html?highlight=resampledata

**Comment by joequant** [comment]
Gotcha.  That seems to be the right way of doing it.  Thanks!!!

**Comment by joequant** [comment]
Also the reason everything is messy has to do with the nature of the data.
For production we use tick data fields, but for testing we have a file that
contains upsampled data which has already been aggregated.  However, it
turns out that the historical data has time stamps that can be off by a few
seconds.

**Comment by mementum** [comment]
Should you need professional support for BitQuant I suggest you drop a message at www.backtrader.com. You wouldn't be the first.
