### ISSUE TITLE
Multiple data error

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#182]
Hi,

I have this case:
1. Tick data 
cerebro.adddata(data,name='data')
2. Indicator 1 resample 240 min
cerebro.adddata(data2,name='data2')
3. Indicator 2 resample 1 day
cerebro.adddata(data1,name='data1')

How can i retrieve data2?
  File "build\bdist.win-amd64\egg\backtrader\lineseries.py", line 426, in __geta
ttr__
AttributeError: 'Lines_LineSeries_LineIterator_DataAccessor_Strateg' object has
no attribute '_data2'

Rgds,
JJ

**Comment by mementum** [comment]
http://backtrader.readthedocs.io/en/latest/strategy.html?highlight=byname#backtrader.Strategy.getdatabyname

http://backtrader.readthedocs.io/en/latest/quickstart/quickstart.html?highlight=inserted#our-first-strategy

**Comment by junajo10** [comment]
Thansk!!!!
