### ISSUE TITLE
Enormous overhead ending with OOM on 1M data set

### ISSUE THREAD

**Issue by val-rog** [mementum/backtrader#184]
Hi! I've implemented simple empty strategy following quickstart guide. For datafeed I've loaded to memory 1M simple lines (1 min - bars for 2 years for certain ticker).

When I run this _empty_ strategy on _preloaded_ data feed on my Lenovo T410s (core i5, 8 GB RAM, Win 10 x64), memory consumption lineary increases until it throws OOM at 2 GB limit after 5-10 minutes of work!!

Either I am doing something completely wrong, or there is some big performance problem there.

Here is my code. When I uncomment "if self.__index >= 100000:" line to limit data with 100K elements, it consumes smth like 200-300MB RAM and finishes in 1 minute (for me it also seems very slow).

```
class SimpleStrategy(backtrader.Strategy):
    def __init__(self):
        # Keep a reference to the "close" line in the data[0] dataseries
        self.dataclose = self.datas[0].close

    def next(self):
        pass

class BackTraderFeed(backtrader.DataBase):
    __index = 0

    def __init__(self, bars):
        super().__init__()
        self.__bars = bars

    def _load(self):
        # if self.__index >= 100000:
        if self.__index >= len(self.__bars):
            return False
        dt, o, h, l, c, v = self.__bars[self.__index]
        self.lines.datetime[0] = dateintern.date2num(dt)
        self.lines.open[0] = o
        self.lines.high[0] = h
        self.lines.low[0] = l
        self.lines.close[0] = c
        self.lines.volume[0] = v
        self.lines.openinterest[0] = 0.0
        self.__index += 1
        return True

if __name__ == '__main__':
    cerebro = backtrader.Cerebro()
    cerebro.addstrategy(SimpleStrategy)
    _bars = # 1 M bars loaded here into memory
    data = BackTraderFeed(_bars)
    cerebro.adddata(data)
    cerebro.broker.setcash(10.0)
    logger.info('Starting Portfolio Value: %.2f', cerebro.broker.getvalue())
    cerebro.run(exactbars=1, runonce=True) # tried to experiment with perf params here, nothing helps
    logger.info('Final Portfolio Value: %.2f', cerebro.broker.getvalue())
```

IMHO an empty strategy on only 1M lines should work in several seconds (strategy has no operations - so cerebro has only to iterate) and consume smth like 1M x 100 bytes = 100 MB (alright, maybe 500 MB, but no more). My "bars" list is like 150-200mb large.

Please help me to solve these performance problems. Thank you!

**Comment by mementum** [comment]
One of the original, and still valid, goals of *backtrader* was to remain as pure Python as possible, to be able to run there where Python is available. This goal had in mind live trading (even if far into the future back then) from embedded platforms where things like a pre-compiled `numpy` package may not be available and the compilation of the package may not be deemed feasible.

The chosen storage with that in mind is the built-in `array.array`, which is *slow* and reallocates memory frequently. It may be, just a conjecture, that the de-allocated memory has not yet been returned to the system by the garbage collector (reference cycle) built into the Python guts.

*backtrader* offers the possibility to try to reduce the buffers to the absolute needed minimum with the parameter `exactbars` passed to `cerebro`. See here:

  - http://backtrader.readthedocs.io/en/latest/memory-savings/memory-savings.html?highlight=exactbars

and here:

  - http://backtrader.readthedocs.io/en/latest/cerebro.html?highlight=exactbars#backtrader.Cerebro

Setting `exactbars=True` or `exactbars=1` would be your target

**Comment by val-rog** [comment]
I don't mind live trading - I simply want to run strategy on reasonable amount of data :)

Also exactbars is set to 1 in my code (line before last) and it does not help.

Is there at least any workaround? Split data set into portions?

**Comment by mementum** [comment]
Missed the `exactbars=1` in your code (screen here is rather small)

Tested under Python 2.7 and 3.5, the system here:

  - Processes 10,000 bars/second (100 seconds for 1 million bars or 1 minute 40 seconds)
  - Consumes a constant RAM amount of 31.6 Mbytes (Python 3.5) and 74.5 Mbytes (Python 2.7)
  - The system (as expected) switches from `array.array` to a `collection.deque` with `maxlen=1` (because nothing is requesting the data buffers to buffer anything else)

  - Adding the indicators the system runs at 5000 bars/second

Your code slightly rewritten for better readability (matter of opinion, of course) and command line arguments

With `exactbars=1`, the internal mechanisms do automatically disable `preload`  and `runonce`, because both need full length buffers and this is not possible with `exactbars`. The `runonce` command line option is provided for verification. There are no changes to the memory consumed when the option is passed (nor changes to the execution time)

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import datetime

import backtrader as bt
import backtrader.utils.flushfile


class SimpleStrategy(bt.Strategy):
    params = dict(indicators=False)

    def __init__(self):
        if self.p.indicators:
            bt.ind.SMA()
            bt.ind.SMA(period=50)
            bt.ind.MACD()


class BackTraderFeed(bt.DataBase):
    params = (
        ('limit', None),
        ('bars', None),
        ('nbars', 10**6),
    )

    def start(self):
        if self.p.bars is None:
            self.p.bars = [[0.0] * self.size()] * self.p.nbars

    def _load(self):
        if len(self) > (self.p.limit or len(self.p.bars)):
            return False

        dt, o, h, l, c, v, oi = self.p.bars[len(self) - 1]
        self.lines.datetime[0] = bt.date2num(datetime.datetime.now())
        self.lines.open[0] = o
        self.lines.high[0] = h
        self.lines.low[0] = l
        self.lines.close[0] = c
        self.lines.volume[0] = v
        self.lines.openinterest[0] = oi
        return True


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='Sample for ...')

    parser.add_argument('--nbars', required=False, action='store', type=int,
                        default=10**6, help=('Numbers of bars to generate'))

    parser.add_argument('--limit', required=False, action='store', type=int,
                        default=None, help=('Stop after x bars'))

    parser.add_argument('--runonce', required=False, action='store_true',
                        help=('Try to control runcone (has no effect)'))

    parser.add_argument('--indicators', required=False, action='store_true',
                        help=('Add indicators to the strategy'))

    args = parser.parse_args()

    cerebro = bt.Cerebro()
    cerebro.addstrategy(SimpleStrategy, indicators=args.indicators)
    data = BackTraderFeed(nbars=args.nbars, limit=args.limit)
    cerebro.adddata(data)
    print('Start:', datetime.datetime.now())
    cerebro.run(exactbars=1, runonce=args.runonce)
    print('Stop:', datetime.datetime.now())
```

**Comment by mementum** [comment]
Should you still experience any issue, please add a comment to this entry.
