### ISSUE TITLE
Question:auction + close position

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#188]
Hi,

1. What is the best way not to consider auction trading timetable in my backtesting?

Opening Auction	From 8:30 h to 9:00 h
Closing Auction	From 17:30 h to 17:35 h
I only want to consider market open:  9:00 h to 17:30 h

Now I am filtering my timeserie using a mask, but maybe a cerebro parameter could be a good idea?

2. What is the best way to close my positions when the market open finishes?
I am checking the timestamp data and comparing with market open limit, but i would like to add this comparation in my trading rules.  For example:
IF CLOSE>10 AND TIMESTAMP < 17:30  THEN BUY 
ELSE IF CLOSE >10 AND TIMESTAMP > 17:30 THEN CLOSE
ELSE NOTHING

I would like to know your opinion about both topics: auctions and rule time.

Rgds,
JJ

**Comment by kizzx2** [comment]
Can't you just implement all of that in your strategy's `next`?

**Comment by mementum** [comment]
`cerebro` is not there to decide when a data has an auction period or to filter out ticks from the data.

Skipping the auction times may be done with a filter which removes the bars belonging to the auction. If the bars are needed for the indicators, the logic has to be implemented by yourself.

**Comment by junajo10** [comment]
Thanks!!! i will continue filtering my timeserie using a mask
