### ISSUE TITLE
What does `lookahead` option in `Cerebro` do?

### ISSUE THREAD

**Issue by kizzx2** [mementum/backtrader#197]
https://github.com/mementum/backtrader/blob/6753f86890ae17880fe6f194a77d83f4d21f3611/backtrader/cerebro.py#L230

Quick glance at the code seems like this is an internal option but it is a `Cerebro` level option?

**Comment by mementum** [comment]
It is/was intended to support things lie `Ichimoku`, which plot things into the future.

But the combination of and workarounds to support the many different use cases may not make it a reality.
