### ISSUE TITLE
Question: add two tick timeseries

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#201]
Hi,

I want to check a pair trading strategy, and i would like to know if i add two tick timeseries, one per asset, backtrader will run correctly.

Rgds,
JJ

**Comment by mementum** [comment]
The platform doesn't know they are *ticks*. The input is a series of `OHLC` bars which get processed.

It would be recommended in any case to set `runonce=False` to avoid differences in internal buffers, which may hinder plotting.
