### ISSUE TITLE
Unnamed arguments to strategy

### ISSUE THREAD

**Issue by parthasrinivasan** [mementum/backtrader#205]
Hi,
I finally upgraded from 1.24.88 to the latest version and an existing program that worked before crashed.
Here is the traceback ..  Any idea why ?

Thanks,
Partha

```
Traceback (most recent call last):
  File "C:\Users\partha\GitHub\PyTrade\nlgen.py", line 280, in <module>
    runstrat()
  File "C:\Users\partha\GitHub\PyTrade\nlgen.py", line 228, in runstrat
    cerebro.run()
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 788, in run
    runstrat = self.runstrategies(iterstrat)
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 850, in runstrategies
    strat = stratcls(*sargs, **skwargs)
  File "C:\Python27\lib\site-packages\backtrader\metabase.py", line 87, in __call__
    _obj, args, kwargs = cls.doinit(_obj, *args, **kwargs)
  File "C:\Python27\lib\site-packages\backtrader\metabase.py", line 77, in doinit
    _obj.__init__(*args, **kwargs)
TypeError: __init__() takes exactly 7 arguments (1 given)
```

**Comment by mementum** [comment]
I guess you mean `1.2.4.88` because there was never a `1.24.88`.

It seems your strategy takes several parameters (`*args`) and they are not being provided.

It's a very random guess, given the lack of sample code.

**Comment by parthasrinivasan** [comment]
Sorry yes 1.2.4.88.  There was no code change - what worked on 1.2.4.88 and 1.2.7.88 now fails.
Let me paste in the calling code for the strategy and the called code that was working ..
--- main cerebro creation and strategy addition
        # Create a cerebro entity
        cerebro = bt.Cerebro(stdstats=False)

        cerebro.addstrategy(ACD_IND_STRAT, sym, None, dump_start_date, args.outfile, args.mode, args.period)
----  Strategy class snippet with the init declaration ..
class ACD_IND_STRAT(bt.Strategy):
    def log(self, txt, dt=None):
        ''' Logging function fot this strategy'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self, sym_name, exchange, dump_start, dump_file, dump_mode, dump_period):
        self.dump_start_date    = dump_start
        self.dump_file          = dump_file
        self.dump_mode          = dump_mode
        self.dump_period        = dump_period
------
Thanks.

**Comment by mementum** [comment]
This sample, which uses 2 unnamed arguments for the strategy works perfectly with the latest version:

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse
import datetime

import backtrader as bt


class St(bt.Strategy):
    params = (
        ('period', 30),
    )

    def __init__(self, arg1, arg2):
        print('arg1:', arg1)
        print('arg2:', arg2)


def runstrat(args=None):
    args = parse_args(args)

    cerebro = bt.Cerebro()
    dkwargs = dict()
    if args.fromdate is not None:
        fromdate = datetime.datetime.strptime(args.fromdate, '%Y-%m-%d')
        dkwargs['fromdate'] = fromdate

    if args.todate is not None:
        todate = datetime.datetime.strptime(args.todate, '%Y-%m-%d')
        dkwargs['todate'] = todate

    data0 = bt.feeds.BacktraderCSVData(dataname=args.data, **dkwargs)
    cerebro.adddata(data0)

    cerebro.addstrategy(St, 1, 2, **(eval('dict(' + args.strat + ')')))
    cerebro.run()

    if args.plot:
        cerebro.plot(**(eval('dict(' + args.plot + ')')))


def parse_args(pargs=None):

    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='Sample to test multi argument')

    parser.add_argument('--data', required=False,
                        default='../../datas/2006-day-001.txt',
                        help='Data to read in')

    parser.add_argument('--fromdate', required=False, default='2011-01-01',
                        help='Ending date in YYYY-MM-DD format')

    parser.add_argument('--todate', required=False, default='2012-12-31',
                        help='Ending date in YYYY-MM-DD format')

    parser.add_argument('--strat', required=False, action='store', default='',
                        help=('Arguments for the strategy'))

    parser.add_argument('--plot', '-p', nargs='?', required=False,
                        metavar='kwargs', const='{}',
                        help=('Plot the read data applying any kwargs passed\n'
                              '\n'
                              'For example:\n'
                              '\n'
                              '  --plot style="candle" (to plot candles)\n'))

    return parser.parse_args(pargs)


if __name__ == '__main__':
    runstrat()
```

And outputs:

```
arg1: 1
arg2: 2
```

both under Python 2.7 and 3.5

**Comment by parthasrinivasan** [comment]
Thanks.  I will play around.  At least I know its soemthign to do with the strategy arguments now.
One of them is always None and maybe I will try without setting stdstats to False in Cerebro etc.
I noticed one thing.  You have 2 arguments to the init class - but when you call it - there is an extra **(eval()) ... in mine - there was nothing.
In my example - the init call takes 6 arguments + self and when I addstrategy - I add the class name and 6 arguments.  The exception is saying - 7 arguments expected (which is correct) - but only one passed.
In my example - do I have to pass something else after the last of my arguments ?  Like you did in your example with the **eval(). 
cerebro.addstrategy(St, 1, 2, **(eval('dict(' + args.strat + ')')))

**Comment by parthasrinivasan** [comment]
Ok - so I have tried several experiments.  Its some weird interaction with the new code.
I have 2 other programs that use unnamed arguments - that all work cleanly.
Only this one fails and I instrument the metbase.py - as follows:
    def doinit(cls, _obj, *args, **kwargs):
        print ('-->',str(cls.__name__), args, kwargs)
        _obj.__init__(*args, **kwargs)
        return _obj, args, kwargs

When I do that - here the output from a working program:
--> PandasData () {}
--> LineBuffer () {}
--> FixedSize () {}
--> ER_IND_STRAT ('AAPL', None, datetime.date(2016, 9, 1), <open file 'NLout.csv', mode 'w' at 0x04A867B0>, 'csv') {}
--> LineBuffer () {}

and here is the non-working program 👍 --> LineBuffer () {}
--> LineSeriesStub (<backtrader.linebuffer._LineDelay object at 0x071A9530>,) {'slave': False}
--> FixedSize () {}
--> ACD_IND_STRAT () {}
TypeError in Cerebro Run:  __init__() takes exactly 7 arguments (1 given)

The working one prints out the argument cleanly, the non working - some how is called with no arguments (other than self).

Any thoughts - on which direction I should look ?  Seems like a binding problem some how that I am causing.

I will try to whittle down the non-working one to standalone version if possible and upload it ...

**Comment by parthasrinivasan** [comment]
Daniel,
Here is a standalone test program that reproduces the issue.  If you feed both streams - 5min and daily bars - the program exhibits the issue.  Comment out either of the feeds and its fine.
testgen.py, AAPL_5min.csv and AAPL_daily.csv enclosed in the zip file.  Unzip and just run it.
Output:
C:\Users\partha\GitHub\PyTrade>.\testgen.py
TypeError in Cerebro Run:  __init__() takes exactly 7 arguments (1 given)


[testgen.zip](https://github.com/mementum/backtrader/files/622798/testgen.zip)

**Comment by parthasrinivasan** [comment]
Ok - some more data.  If I use named variables to call the strategy - everything works - even with two data feeds.  If I just use positional - it crashes with two feeds.  Can do this experiment with the example I provied
