### ISSUE TITLE
Problems with PyFolio analyzer when using two data feeds

### ISSUE THREAD

**Issue by wappler99** [mementum/backtrader#209]
Hi,
First off: Thank you so much for putting Backtrader out there as open source, it is truly awesome!

One issue that I have encountered is with using the PyFolio Analyzer with 2 data feeds.  Since I wasn't sure if my code was causing it, I simply took your test strategy from the documentation (Quickstart->Do not only buy... but SELL) and was able to replicate the error:  Initially the code including PyFolio works just fine, but as soon as I add another data feed with 'cerebro.adddata(data)' (even if the second data feed is not used at all!), pyfolio.get_pf_Items() crashes with the following traceback:

```
Traceback (most recent call last):
  File "C:/Users/wappler/Backtest/pftest2.py", line 112, in <module>
    returns, positions, transactions, gross_lev = pyfolio.get_pf_items()
  File "C:\Anaconda2\lib\site-packages\backtrader\analyzers\pyfolio.py", line 132, in get_pf_items
    positions = DF.from_records(ps, index=cols[0], columns=cols)
  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1023, in from_records
    coerce_float=coerce_float)
  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5530, in _to_arrays
    dtype=dtype)
  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5609, in _list_to_arrays
    coerce_float=coerce_float)
  File "C:\Anaconda2\lib\site-packages\pandas\core\frame.py", line 5668, in _convert_object_array
    'columns' % (len(columns), len(content)))
AssertionError: 3 columns passed, passed data had 4 columns
```

**Comment by mementum** [comment]
An educated guess is that you are not assigning names to the data feeds. The code interfacing with `pandas` sends an array of names, in which all names happen to be the empty name and assimilates them into a single column name. Hence the missing column in the error: `AssertionError: 3 columns passed, passed data had 4 columns`

Use

```
cerebro.addata(mydata, name="nameX")
```

**Comment by wappler99** [comment]
Daniel,

Thanks, your educated guess was exactly that!  Pyfolio.get_pf_items() is now working.  PyFolio is also running (at least 95% of it, at the very end it crashes), so now it’s time to familiarize myself with the PyFolio documentation.  Thanks so much for your help!

 

Regards,

Uli
