### ISSUE TITLE
Forex

### ISSUE THREAD

**Issue by crazy25000** [mementum/backtrader#21]
Hey, would you post sample code and CSV file to test currency strategy?

**Comment by mementum** [comment]
The source contains sample data under "datas" and there is even a SMA_CrossOver sample strategy included in the package.

There are additional samples under: "samples"

  - commission-schemes already includes a working strategy
  - multidata-strategy contains a strategy which operates with multiple datas
  - order-execution shows a strategy using different types of execution
  - writer-test contains a long-short strategy to test the writer

These and others are available in posts with additional comments in the blog: www.backtrader.com
