### ISSUE TITLE
linear regression and std

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#211]
Hi,

Could you include in the next release both linear regression and standard deviation? I think these indicators  help people to calculate ratios over the time series.

```
S1= timeseries close
S2= timeseries close
rolling_beta = pd.ols(y=S1, x=S2, window_type='rolling', window=30)
spread = S2 - rolling_beta.beta['x'] * S1
std_30 = pd.Series.rolling(spread,window=30,center=False).std()
```

Rgds,
JJ

**Comment by mementum** [comment]
To be followed here https://community.backtrader.com/topic/5/linear-regression-and-std-211
