### ISSUE TITLE
Change BuySell to "trade arrows" in charts

### ISSUE THREAD

**Issue by kizzx2** [mementum/backtrader#213]
[Example](http://bl.ocks.org/andredumas/3c0eefdd77a6380b1a35)

This style of buy/sell annotation is much more common in literature then the current one implemented, which often gets overlapped by candlesticks and become difficult to see.

So basically it's just a matter of moving the arrows "out of the way" to not get overlapped by the candle bars.

**Comment by mementum** [comment]
https://www.backtrader.com/docu/observers-reference.html?highlight=buysell#backtrader.observers.BuySell

Adjust the `bardist` parameter to move the arrows further away.

You can also change the matplotlib markers to draw any arrow you like.

```python
    plotlines = dict(
        buy=dict(marker='^', markersize=8.0, color='lime',
                 fillstyle='full', ls=''),
        sell=dict(marker='v', markersize=8.0, color='red',
                  fillstyle='full', ls='')
    )
```

**Comment by mementum** [comment]
https://community.backtrader.com/topic/8/change-buysell-to-trade-arrows-in-charts-213
