### ISSUE TITLE
Trading multiple instruments?

### ISSUE THREAD

**Issue by kvdveer** [mementum/backtrader#214]
I'm looking into backtrader to backtest my strategy, but my strategy trades over multiple instruments. The documentation only seems to point to single instrument examples, and I can't seem to find a way to provide  price data for multiple instruments, or specify an instrument for an order.

Does backtrader support multiple instruments? In that case, could you add an example to the documentation? If no, is this feature planned any time soon?

**Comment by mementum** [comment]
The documentation/blog has several examples with multiple instruments, be it with resampling of the same data or with different datas. Some examples:

  - https://www.backtrader.com/docu/data-multitimeframe/data-multitimeframe.html

  - https://www.backtrader.com/blog/posts/2015-09-03-multidata-strategy/multidata-strategy.html?highlight=correlated

  - https://www.backtrader.com/blog/posts/2016-08-15-stock-screening/stock-screening.html?highlight=tsla

You simply have to tell the platform form which instrument to buy/sell.

**Comment by mementum** [comment]
https://community.backtrader.com/topic/4/trading-multiple-instruments-214
