### ISSUE TITLE
Problem connecting to IB

### ISSUE THREAD

**Issue by rastegar527** [mementum/backtrader#217]
I ran ibtest.py example to connect to IB realtime. But I'm running to issues even though I have TWS running with the right configuration (I am able to run ibpy and get data).

Here is what I get when I run ibtest.py. Can you please help me?
```
Reza:ibtest reza$ python ibtest.py --data0 AAPL --timeframe Minutes --port 7496 --host 0.0.0.127 --clientId 1
--------------------------------------------------
Strategy Created
--------------------------------------------------
Datetime, Open, High, Low, Close, Volume, OpenInterest, SMA
***** STORE NOTIF: <error id=-1, errorCode=502, errorMsg=Couldn't connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.>
***** STORE NOTIF: <error id=-1, errorCode=502, errorMsg=Couldn't connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.>
***** STORE NOTIF: <error id=-1, errorCode=502, errorMsg=Couldn't connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.>
***** STORE NOTIF: <error id=-1, errorCode=502, errorMsg=Couldn't connect to TWS.  Confirm that "Enable ActiveX and Socket Clients" is enabled on the TWS "Configure->API" menu.>
```

**Comment by mementum** [comment]
`0.0.0.127` seems like a very strange IP address ... and in case the demo is running the default port is `7497`

**Comment by rastegar527** [comment]
I tested it with HOST ip and 7497 initially and didn't work. Then I changed the port on TWS to 7496. But I had the same problem. Any suggestion?

**Comment by rastegar527** [comment]
I tried 

python ibtest.py --port 7496 --data0 AAPL --timeframe Minutes --compression 2

as suggested in #164. It works. But still don't see what I was doing wrong previously.

**Comment by mementum** [comment]
Since it seems `0.0.0.127` was actually what you were using, it also seems your knowledge about IP addressing is rather limited (everyone has started from zero at some point in time)

What you use is the standard configuration in which the default IP address is `127.0.0.1` aka `localhost`.

This should make it very obvious what's totally wrong with your 1st attempt. Even reversing your input doesn't make it a valid IP address, it is a network address.
