### ISSUE TITLE
Question Ichimoku?

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#218]
hI,

I am checking Ichimoku, but i don´t know if the values are well calculated because I always got that chikou_span is Nan.

cerebro = bt.Cerebro(runonce=False,oldsync=True)  

Chikou Span
Closing price
**Shifted 26 periods back**

self.l.senkou_span_b = senkou_span_b(-self.p.senkou_lead)
self.l.chikou_span = self.data.close(**self.p.chikou**)

Should self.p.chikou have negative sign?
self.l.chikou_span = self.data.close(**-self.p.chikou**)

if i change runonce=False by runonce=True, i get the values of self.l.chikou_span

Rgds,
JJ

**Comment by mementum** [comment]
https://community.backtrader.com/topic/7/question-ichimoku-218
