### ISSUE TITLE
Importing orders

### ISSUE THREAD

**Issue by Richterr** [mementum/backtrader#219]
Hello,
Is there a way to import orders from an array? I have them in an array that looks like [0,0,1,0,0,-1,-1...], length of this array is the same as the length of the data(one signal for each timeframe). 
This is for backtesting only, the calculations are done outside of the testing script.

**Comment by Richterr** [comment]
Or simpler, signals are save in a csv with lines like this
2016-01-09;100200;-1
2016-01-09;110200;1
etc

**Comment by mementum** [comment]
https://community.backtrader.com/topic/3/importing-orders-219
