### ISSUE TITLE
Bar filling code worked in 1.2.7.88 - failing in 1.9.19.105

### ISSUE THREAD

**Issue by parthasrinivasan** [mementum/backtrader#226]
Hi,
[BarFiller Bug.zip](https://github.com/mementum/backtrader/files/659153/BarFiller.Bug.zip)

I have enclosed a test program and two data files.
The data in the 5min bars file is sparse ie. could be missing.  In a previous version - you helped me write a Bar copy routine to fill in the spare data - This routine
```python
class MySessionFiller(btfilters.SessionFiller):
    def _fillbar(self, data, dtime):
        # Copy the previous bar
        bar = [data.lines[i][-1] for i in range(data.size())]
        bar[data.DateTime] = date2num(dtime)  # Fill datetime
        # Add to the stack of bars to save
        data._add2stack(bar)           
        return True
```
works in 1.2.7.88 - but fails now in 1.9.19
unzip file and just run testgen.py - and you will see a printout.  Comment out the MyFiller filter to verify its the filter thats causing the issue and not the original data.

Are you in the new data handling architecture - automatically doing this by default ie. filling in sparse data by copying ?

Thanks.

**Comment by mementum** [comment]
Not an issue per se. Moved to https://community.backtrader.com/topic/21/bar-filling-code-worked-in-1-2-7-88-failing-in-1-9-19-105-226
