### ISSUE TITLE
Q: trading multiple-strategy multiple-asset multi-currency

### ISSUE THREAD

**Issue by xnox** [mementum/backtrader#229]
Hello,

I'd like to backtest two strategies simultaneously to see how the portfolio performs. It's two futures contracts, one is traded in GBP the other in USD. My commission and broker cash account are in GBP. Is it possible to provide a feed for the GBP/USD exchange rate and e.g. mangle the USD asset multiplier back into GBP to get realistic returns from the backtest? At the moment, i'm converting multiplier from USD -> GBP, eg. 20.36 GBP instead of 25 USD; but that would not be historically accurate.  I guess I could process my data feed and include both "GBP" and "USD" price, and trade "GBP" price whilst using signals from the "USD" one. Is there any more elegant way of handling this? (there is 0.3% markup on currency conversion too....)

Regards,

Dimitri.

**Comment by mementum** [comment]
Not an issue. Please use: https://community.backtrader.com
