### ISSUE TITLE
Relative volume indicator

### ISSUE THREAD

**Issue by willhoyle** [mementum/backtrader#23]
Hi,
I'm wondering if you could point me in the right direction on how to develop an indicator like the one in this link: https://www.bigmiketrading.com/download/ninjatrader-7/indicators/632-download.html?view
I would like to know if it is even possible with the architecture of the system?

**Comment by mementum** [comment]
Seeing the information nothing speaks against implementing such an indicator in the system.

The only problem being that there seems to be no clear standard definition of "Relative Volume Indicator" even looking at the different code implementations.

Have you an idea as to how you'd like it to look like?

**Comment by mementum** [comment]
One of the approaches mentioned in the bigmiketrading forum is as simple as comparing the volume against the volume of X periods before.

The code (where the moving average to apply can be changed) would be

````
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import backtrader as bt
import backtrader.indicators as btind


class RelativeVolume(bt.Indicator):
    alias = ('RVI',)
    lines = ('rvi',)

    params = (
        ('period', 20),
        ('movav', btind.MovAv.SMA),
    )

    def __init__(self):
        volav = self.p.movav(self.data.volume, period=self.p.period)
        self.lines.rvi = self.data.volume / volav

        # Done after calc to ensure coop inheritance and composition work
        super(RelativeVolume, self).__init__()
````

**Comment by willhoyle** [comment]
Exactly. How I would like it to work is say, for example, that we're backtesting a 1 minute time frame. 

Time (HH:MM:SS) | Previous Volume | Current Volume | Ratio
------------ | ------------- | ------------- | ------------- |
09:30:00 | 1000 | 2000 | 2 
09:31:00 | 300 | 900 | 3
... | | |
04:00:00 | 300 | 300 | 1  

Our line would hold the ratio values for every minute. In a trading day, there's 6.5 hours * 60 minutes = 390 minutes. So for 1 minute charts you would need a period of 390 in order to 'align' both days.

Maybe something like this:
```python
class RelativeVolume(bt.Indicator):
    alias = ('RVI',)
    lines = ('rvi',)

    params = (
        ('period', 390),
    )

    def __init__(self):
       #not sure if this is the right way to slice data within your framework
       previousvol = self.data.volume[:self.p.period] 
       currentvol = self.data.volume[self.p.period:]
       self.lines.rvi = currentvol/previousvol

        # Done after calc to ensure coop inheritance and composition work
        super(RelativeVolume, self).__init__()
```
The other thing is the period=390 is hard coded to the 1 minute time frame. A time frame of 1 second will yield 23400 candles. At runtime, can the indicator have knowledge of what time frame is being used? Something like:
```python
    timeframe = get_timeframe()
    _adjusted_period = (... calculations to get the approriate period)
    params = (
        ('period', _adjusted_period),
    )
```

There's other problems that might make the logic more complicated than the code above:
 * my data feed might have premarket data, which would cause the lines to not align
 * tick data would cause the same issue since there's a variable number of candles. We could maybe re-sample tick data to an arbitrarily small sampling rate like 0.1 s.

Anyways, this post is getting longer than I thought. Let me know what you think!

**Comment by mementum** [comment]
Let me first try to summarize my understanding:

  - Intraday bars (either minutes or seconds)
  - The volume of the current bar is compared to the volume of the previous bar with the same "time" (obviously ... not the same date)

  - Pre-market data (and maybe post) exists and has varying length (hence your comment about the alignment of the bars)

Be it so, my first idea would be

  - A Data Source which accepts another data source and filters any pre/post market data, delivering to the strategy/indicators only the "market" data

The alternative is to keep a mark of when the 1st bar of the previous day "market" data took place to understand how far away (distance) in the past the to be compared bar is.

The second idea is implemented below. There is a convenience "time2num" function to avoid comparing objects and rather compare float values.

Because the conditions of the "pre"market data is unknown to me I have added a "session_prestart" time which allows the period to be extended. Instead of a "time" it could be a factor to increase the session bars by.

As you see below, the "data" carries the timeframe and compression informatino and can be accessed by the indicator.

````
def time2num(tm):
    """
    Convert :mod:`time` to the to the preserving hours, minutes, seconds
    and microseconds.  Return value is a :func:`float`.
    """
    HOURS_PER_DAY = 24.0
    MINUTES_PER_HOUR = 60.0
    SECONDS_PER_MINUTE = 60.0
    MUSECONDS_PER_SECOND = 1e6
    MINUTES_PER_DAY = MINUTES_PER_HOUR * HOURS_PER_DAY
    SECONDS_PER_DAY = SECONDS_PER_MINUTE * MINUTES_PER_DAY
    MUSECONDS_PER_DAY = MUSECONDS_PER_SECOND * SECONDS_PER_DAY

    tm_num = (tm.hour / HOURS_PER_DAY +
              tm.minute / MINUTES_PER_DAY +
              tm.second / SECONDS_PER_DAY +
              tm.microsecond / MUSECONDS_PER_DAY)

    return tm_num


class RelativeBarVolume(bt.Indicator):
    lines = ('rbv',)

    params = (
        ('session_prestart', datetime.time(6, 30)),
        ('session_start', datetime.time(9, 30)),
        ('session_end', datetime.time(16, 00)),
    )

    def __init__(self):
        self._setperiod()

        # Convert to numbers to speed up comparisons
        self.session_start = time2num(self.p.session_start)
        self.session_end = time2num(self.p.session_end)

        # Initialize the mark
        self._mark = 0

    def _setperiod(self):
        # Period calculation
        minend = self.p.session_end.hour * 60 + self.p.session_end.minute
        # minstart = session_start.hour * 60 + session_start.minute
        # use prestart to account for market_data
        minstart = self.p.session_prestart.hour * 60 + \
            self.p.session_prestart.minute

        minutes = minend - minstart

        tframe = self.data._timeframe
        tcomp = self.data._compression

        if tframe == bt.TimeFrame.Seconds:
            minperiod = (minutes * 60)

        minperiod = (minperiod // tcomp) + tcomp

        # Inform the platform about the minimum period needs
        self.addminperiod(minperiod)

    def _setmark(self):
        # Get the time part from datetime
        tm, _ = math.modf(self.data.datetime[0])

        if tm == self.session.start:
            # Record the start of the session
            self._dist = self._mark - len(self)
            self._mark = len(self)

    def prenext(self):
        self._setmark()

    def next(self):
        self._setmark()

        if self.session_start <= tm <= self.session_end:
            # Calculate relative bar volume only within session limits
            pvol = self.data.volume[self._dist]
            self.lines.rbv[0] = self.data.volume[0] / pvol
````

**Comment by mementum** [comment]
The other alternative as mentioned is a datafilter

````python
import backtrader.feed as btfeed


class SessionFilter(object):
    start = datetime.time(9, 30)
    end = datetime.time(16, 0)

    def __init__(self):
        self.start = time2num(SessionFilter.start)
        self.end = time2num(SessionFilter.end)

    def __call__(self, data):
        tm, _ = math.modf(data.datetime[0])

        return self.start <= tm < self.end


class DataFilter(btfeed.DataBase):
    params = ((funcfilter, None),)  # actually any "callable"

    def __init__(self):
        # Direct access to parameters
        self.funcfilter = self.p.funcfilter
        self.dataname = self.p.dataname

    def _load(self):
        # Tell underlying source to get next data
        while self.dataname.next():
            # Try to load the data from the underlying source
            if self._load_data():
                return True  # loaded ... say so

            # else go back to the beginning of the loop

        return False  # no more data from underlying source

    def _load_data(self):
        if not self.funcfilter(self.dataname):
            return False  # funcfilter doesn't like the data

        # Data is allowed - Copy and confirm with return
        for i in self.dataname.size():  # size is "number of lines"
            self.lines[i][0] = self.dataname.lines[i][0]

        return True
````


You would do something like:

````python

my data = btfeeds.MyDataSource(xxxxxx)

filtered_data = DataFilter(dataname=my_data, funcfilter=SessionFilter())

cerebro.adddata(filtered_data)
````

In this case only the in-session data bars would be available, making synchronization of bars (period lookback) a child's play.

**Comment by mementum** [comment]
Further thoughts about your "indicator" gave me a push to "develop" it and post it here:

  - http://www.backtrader.com/posts/2015-10-04-bar-synchronization/bar-synchronization/

Your synchronization problem would be solved with the approach.

**Comment by mementum** [comment]
Closing the issue (but not locking it in case further comments would be needed)

**Comment by willhoyle** [comment]
Thanks, I don't think I would have been able to program it myself. I definitely need to go through the backtrader code and all your blog posts in order to understand a bit more what's going on here.

**Comment by mementum** [comment]
I know a couple of Open Source and Commercial Platforms and the problem would still be "synchronization", given that minute (and smaller periods) bars can be missing from the data feed and hence a fix lookback period would target the wrong bars (and the different in synchronization distance would grow with each missing bar.

The only other approach is to insert dummy data (volume 0 and last closing price) where a bar is missing (probably due to the lack of negotiation during the brief period of time)

**Comment by willhoyle** [comment]
For an indicator like this one, inserting dummy data is probably good enough for what I'll be using it for. In the past, when writing my own (primitive, a lot of hardcoding shaped to my data) backtester I would fill in missing/low volume bars (<100 shares) with a volume of 100 to avoid division by zero. A side effect of this is I got less "abnormal" candles where you have say 10000 shares divided by 1 share. 

But that's just one way of doing things, I know that this "indicator" isn't really officially defined and different implementations will yield different results.

**Comment by mementum** [comment]
After much ado and with some delay after things were implemented, your synchronization problem can be "easily" solved in backtrader.

  - http://www.backtrader.com/posts/2015-11-21-data-filters/data-filling-filtering/

Should I manage to add live feed/live trading you could apply the indicator. But beware, my code has always bugs
