### ISSUE TITLE
Multiple Datafeed Standardization

### ISSUE THREAD

**Issue by Lex2016** [mementum/backtrader#231]
Hi, 2 Data Issues here, maybe they have been solved elsewhere & I couldn't find it.

1) I am pulling several datas individually through an API. They have different counts of dates & this is causing the backtest to crash (i.e. currencies trade 24/7 whilst stocks only 5 days a week). I know zipline automatically solves this problem by backfilling data per day (i.e. if you pass a monthly & daily data, it will auto-reconfigure the monthly into a daily sample for all days available). I have looked at the documentation regarding the 'filler' which is quite easy to do in a pandas dataframe, but how would you do this for multiple datas? (i.e. 1st with 200 days, 2nd with 190 days, 3rd with 210 days).

2) With regards to a table data where the first column is a date & the other 3 columns are equity prices, how do you extract each individual price for each security whilst still referencing the date in the first column?
```
	IBM US EQUITY	CSCO US EQUITY	MSFT US EQUITY
date			
2014-01-02	185.53	22.000	37.16
2014-01-03	186.64	21.980	36.91
2014-01-06	186.00	22.010	36.13
2014-01-07	189.71	22.310	36.41
2014-01-08	187.97	22.293	35.76
```

Apologies again if this has been covered somewhere, I have looked around the documentation.

Kind Regards
Lex

**Comment by mementum** [comment]
This is not strictly an issue and therefore it is politely askes (top of the README) to post these things to the community for discussion (the content is also markdown based, so you can simply port it)

 - https://community.backtrader.com
