### ISSUE TITLE
Oanda REST-V20 API support

### ISSUE THREAD

**Issue by 0x74-0x62** [mementum/backtrader#232]
Right now, it seems that the Oanda features of backtracker do not work with a new Oanda v20 account. Are there any plans to upgrade to Oanda REST-V20 API? It seems that meanwhile the weaknesses of the v20 API mentioned in #106 and #152, like missing streaming support, have been addressed by Oanda.

**Comment by mementum** [comment]
Not an issue. Please notice the following from the `README´: 

 - Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com
