### ISSUE TITLE
Writer does not support analyzers returning non-str Keys

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#24]
The error message is:
  File "backtrader\writer.py", line 199, in writedict
    self.writedict(val, level=level + 1, recurse=True)
  File "backtrader\writer.py", line 174, in writedict
    kline += key + ':'
TypeError: unsupported operand type(s) for +: 'int' and 'unicode'

This can be fixed in annualreturn.py where the key cur_year is converted to string first.

**Comment by mementum** [comment]
The issue is that the writer had not been tested with analyzers having non-strings as keys in the dictionaries.

Now the dictionary keys are converted to strings in the writer before proceeding with the values

**Comment by mementum** [comment]
Comment in commi above meant for #25

**Comment by mementum** [comment]
Closed with 1.1.13.88
