### ISSUE TITLE
Error while resampling data

### ISSUE THREAD

**Issue by eliclement** [mementum/backtrader#252]
When I try to resample minutes data (taken from the backtrader/datas/ directory), I got the following error:
**code snippet:**
```
datapath = '2006-min-005.txt'
data = bt.feeds.BacktraderCSVData(dataname=datapath)
cerebro.adddata(data)  # First add the original data - smaller timeframe
cerebro.resampledata(data, timeframe=bt.TimeFrame.Days)
```

**Error:**
```
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    cerebro.run()
  File "/usr/local/lib/python2.7/site-packages/backtrader/cerebro.py", line 810, in run
    runstrat = self.runstrategies(iterstrat)
  File "/usr/local/lib/python2.7/site-packages/backtrader/cerebro.py", line 934, in runstrategies
    self._runnext(runstrats)
  File "/usr/local/lib/python2.7/site-packages/backtrader/cerebro.py", line 1186, in _runnext
    dt0 = min((d for i, d in enumerate(dts) if d is not None and i not in rsonly))
ValueError: min() arg is an empty sequence
```

When I try to resample this minute data to "weekly" data, there is no error...
**code snippet (successfully resampled to weekly data):**
```
datapath = '2006-min-005.txt'
data = bt.feeds.BacktraderCSVData(dataname=datapath)
cerebro.adddata(data)  # First add the original data - smaller timeframe
cerebro.resampledata(data, timeframe=bt.TimeFrame.Weeks)
```

Any idea what is going wrong or how to solve this?
Thanks!

**Comment by mementum** [comment]
From the main page of the repository

> Note:
> 
> Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com

Additionally: version numbers and similar things can always happen. The resampling has been recently changed often with the community feedback to synchronize bars on end of session times. You may wish to update.
