### ISSUE TITLE
.resampledata() from faster timeframe of IB data never shows up.

### ISSUE THREAD

**Issue by rterbush** [mementum/backtrader#258]
@mementum not sure if you are looking at this, but have modified your test script to investigate the issue with `.resampledata()` seeming to never become available. End result is that any system attempting to resample from a faster timeframe never gets these bars.

Here is the modified script. It demonstrates that `Data2` is never seen.

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import datetime
import backtrader as bt


class TestStrategy(bt.Strategy):
    def __init__(self):
        self.datastatus = False

    def notify_data(self, data, status, *args, **kwargs):
        print('*' * 5, 'DATA NOTIF: %s' % data._name,
              data._getstatusname(status), *args)

        if status == data.LIVE:
            self.datastatus = True

    def notify_store(self, msg, *args, **kwargs):
        print('*' * 5, 'STORE NOTIF:', msg)

    def prenext(self):
        self.next()

    def next(self):
        if not self.datastatus:
            print("datastatus: %s" % self.datastatus)
            return

        print('-- %004d' % len(self), str(self.datetime.datetime()))
        for i, d in enumerate(di for di in self.datas if len(di)):
            out = ['Data%d' % i, d._name, '%004d' % len(d),
                   str(d.datetime.datetime()), str(d.close[0])]

            print(','.join(out))


if __name__ == '__main__':
    TICKER0, SSEND0, TZ0 = 'ES-201703-GLOBEX-USD', datetime.time(15, 15), 'CST6CDT'
    TICKER1, SSEND1, TZ1 = 'SPY-STK-SMART-USD', datetime.time(16, 0), 'EST5EDT'

    NAME0, NAME1 = TICKER0.split('-')[0], TICKER1.split('-')[0]

    cerebro = bt.Cerebro()

    storekwargs = dict(host='127.0.4.1', port=7465, clientId=93,)
    ibstore = bt.stores.IBStore(**storekwargs)
    data0 = ibstore.getdata(dataname=TICKER0, sessionend=SSEND0, name=NAME0, tz=TZ0)
    cerebro.resampledata(data0, timeframe=bt.TimeFrame.Minutes, compression=1)

    data1 = ibstore.getdata(dataname=TICKER1, sessionend=SSEND1, name=NAME1, tz=TZ1)
    cerebro.resampledata(data1, timeframe=bt.TimeFrame.Days, compression=1)

    # should see the following as Data2
    cerebro.resampledata(data0, timeframe=bt.TimeFrame.Days, compression=1, name='ES-day')

    cerebro.addstrategy(TestStrategy)
    cerebro.run(runonce=False, tradehistory=True, exactbars=0)
```

**Comment by rterbush** [comment]
Actually, after a 10 minute wait, Data2 shows up... Perhaps I have not been patient enough.

**Comment by rterbush** [comment]
Is the count correct though?
```
-- 1252 2017-02-08 15:40:00
Data0,ES,1001,2017-02-08 09:40:00,2284.75
Data1,SPY,0251,2017-02-07 16:00:00,228.83
Data2,ES-day,0001,2017-02-08 09:15:00,2286.0
```

**Comment by mementum** [comment]
`16:00` would be for sure the wrong time because you have said that the closing time for `ES` is `15:15`. The actual time coming out is `09:15`, so it seems that the re-resampled `ES` takes the timezone wrongly (still uses the minute part)

But in the community thread it was mentioned that with the current architecture for `IB`, you'd be better off if you created a 2nd ES IB data feed, rather than re-resampling the existing one.

**Comment by rterbush** [comment]
You are correct. Should be 15:15 CST
I will change approach to creating new feeds from IB and will backfill that daily data. Probably a better solution.

**Comment by mementum** [comment]
`09:15 UTC` is `15:15 CST` (during the winter) It's obvious that for some reason the `DataClone` is not picking up the `timezone`, even if the code seems to do so.

**Comment by rterbush** [comment]
15:15 CST should be 20:15 UTC, yes? :-)

**Comment by mementum** [comment]
Recalling the problem with the current architecture: the 2nd resample of `data0` will modify the timeframe/compression settings of the original data if this data has not been added to the system. That's the reason it won't properly work (regardless of the tz issue, which is probably related)

An update of the architecture will be needed.
