### ISSUE TITLE
TimeFrame Ticks is not contemplated in some functions

### ISSUE THREAD

**Issue by parrondo** [mementum/backtrader#259]
I have tried to reproduce the results from blog entry "Tick Data and Resampling".
After fresh instalation of backtrader and the command:

$ ./resample-tickdata.py

I have got a bunch of errors with the following as last ones:

_...
  File "/home/myuser/anaconda2/envs/backtrader/lib/python3.5/site-packages/backtrader/resamplerfilter.py", line 409, in _adjusttime
    dtnum = self._calcadjtime(greater=greater)

  File "/home/myuser/anaconda2/envs/backtrader/lib/python3.5/site-packages/backtrader/resamplerfilter.py", line 389, in _calcadjtime
    if ph > 23:  # went over midnight:

UnboundLocalError: local variable 'ph' referenced before assignment_

I see the problem is in the method " _calcadjtime()" of the class _BaseResampler, which not contemplates TimeFrame.Ticks:

    __def _calcadjtime(self, greater=False):
        if self._nexteos is None:
            # Session has been exceeded - end of session is the mark
            return self._lastdteos  # utc-like

        dt = self.data.num2date(self.bar.datetime)

        # Get current time
        tm = dt.time()
        # Get the point of the day in the time frame unit (ex: minute 200)
        point, _ = self._gettmpoint(tm)

        # Apply compression to update the point position (comp 5 -> 200 // 5)
        # point = (point // self.p.compression)
        point = point // self.p.compression

        # If rightedge (end of boundary is activated) add it unless recursing
        point += self.p.rightedge

        # Restore point to the timeframe units by de-applying compression
        point *= self.p.compression

        # Get hours, minutes, seconds and microseconds
        extradays = 0
        if self.p.timeframe == TimeFrame.Minutes:
            ph, pm = divmod(point, 60)
            ps = 0
            pus = 0
        elif self.p.timeframe == TimeFrame.Seconds:
            ph, pm = divmod(point, 60 * 60)
            pm, ps = divmod(pm, 60)
            pus = 0
        elif self.p.timeframe == TimeFrame.MicroSeconds:
            ph, pm = divmod(point, 60 * 60 * 1e6)
            pm, psec = divmod(pm, 60 * 1e6)
            ps, pus = divmod(psec, 1e6)
        elif self.p.timeframe == TimeFrame.Days:
            # last resort
            eost = self._nexteos.time()
            ph = eost.hour
            pm = eost.minute
            ps = eost.second
            pus = eost.microsecond

        if ph > 23:  # went over midnight:
            extradays = ph // 24
            ph %= 24_

I hope this could help you to improve your great job. Also thank you for open source your invaluable code.

**Comment by mementum** [comment]
The resampling code has been constantly under revision lately ...
