### ISSUE TITLE
multitrades PnL issue

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#26]
Sometimes the respective PnL numbers for multi-trades are missed up. Specifically, say, I open a short position in trade 0 with execution price 80, and then I open another short position in trade 1 with execution price 100. Then the execution price in trade 0 is changed to 90 (the average of 80 and 100). Subsequently the PnL for trade 0 is wrong, and the same for trade 1.

**Comment by mementum** [comment]
I guess I am not able to fully comprehend the problem and therefore I created a sample test (see below)

It runs agains the regular data samples in the source distribution. The strategy restricts itself to creating 2 orders with 2 different ids for the trade and prints out the details of the notified orders and the details of the notified trades.

The output ins printed out during execution and on "stop" and the details remain unchanged.

Let me know if there is anything else to look into.

Output
```
--------------------------------------------------
order tradeid 0 / price 0.00 / size 0
--------------------------------------------------
order tradeid 0 / price 0.00 / size 0
--------------------------------------------------
order tradeid 0 / price 3643.35 / size 1
--------------------------------------------------
trade tradeid 0 / price 3643.35 / size 1
--------------------------------------------------
order tradeid 1 / price 0.00 / size 0
--------------------------------------------------
order tradeid 1 / price 0.00 / size 0
--------------------------------------------------
order tradeid 1 / price 3725.18 / size 1
--------------------------------------------------
trade tradeid 1 / price 3725.18 / size 1
--------------------------------------------------
tradeid 0 / price 3643.35 / size 1
--------------------------------------------------
tradeid 1 / price 3725.18 / size 1
``` 

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.indicators as btind
from backtrader.utils import flushfile


class SMAStrategy(bt.Strategy):
    params = (
        ('period', 10),
    )

    def notify_order(self, order):
        print('-' * 50)
        print('order tradeid %d / price %.2f / size %d' %
              (order.tradeid, order.executed.price, order.executed.size))

    def notify_trade(self, trade):
        print('-' * 50)
        print('trade tradeid %d / price %.2f / size %d' %
              (trade.tradeid, trade.price, trade.size))

        self.trades[trade.tradeid] = trade

    def __init__(self):
        self.trades = dict()
        sma = btind.SMA(self.data, period=self.p.period)
        self.sig = btind.CrossOver(self.data.close, sma)
        self.tradeid = 0

    def next(self):
        if self.position.size < 2 and self.sig > 0:
            self.buy(tradeid=self.tradeid % 2)
            self.tradeid += 1

    def stop(self):
        for tradeid in sorted(self.trades):
            trade = self.trades[tradeid]
            print('-' * 50)
            print('tradeid %d / price %.2f / size %d' %
                  (trade.tradeid, trade.price, trade.size))


def runstrat():
    args = parse_args()

    # Create a cerebro entity
    cerebro = bt.Cerebro()

    # Add a strategy
    cerebro.addstrategy(SMAStrategy, period=args.period)

    # Load the Data
    data = btfeeds.BacktraderCSVData(dataname=args.dataname)

    # First add the original data - smaller timeframe
    cerebro.adddata(data)

    cerebro.broker.setcash(10000000)

    # Run over everything
    cerebro.run()

    # Plot the result
    cerebro.plot(style='bar')


def parse_args():
    parser = argparse.ArgumentParser(description='Trade Id Test')

    parser.add_argument('--dataname', required=False,
                        default='../../datas/2006-day-001.txt',
                        help='File Data to Load')

    parser.add_argument('--period', default=10, required=False, type=int,
                        help='Period to apply to indicator')

    return parser.parse_args()


if __name__ == '__main__':
    runstrat()
```

**Comment by zhanjing** [comment]
What I mean is that the respective PnL number for each trade is wrong. See the PnL numbers at the end of the output:
--------------------------------------------------
order tradeid 0 / price 0.00 / size 0
--------------------------------------------------
order tradeid 0 / price 0.00 / size 0
--------------------------------------------------
order tradeid 0 / price 3643.35 / size -1
--------------------------------------------------
trade tradeid 0 / price 3643.35 / size -1
--------------------------------------------------
order tradeid 1 / price 0.00 / size 0
--------------------------------------------------
order tradeid 1 / price 0.00 / size 0
--------------------------------------------------
order tradeid 1 / price 3725.18 / size -1
--------------------------------------------------
trade tradeid 1 / price 3725.18 / size -1
--------------------------------------------------
order tradeid 0 / price 0.00 / size 0
--------------------------------------------------
order tradeid 1 / price 0.00 / size 0
--------------------------------------------------
order tradeid 0 / price 0.00 / size 0
--------------------------------------------------
order tradeid 1 / price 0.00 / size 0
--------------------------------------------------
order tradeid 0 / price 3696.09 / size 1
--------------------------------------------------
order tradeid 1 / price 3696.09 / size 1
--------------------------------------------------
trade tradeid 0 / price 3643.35 / size 0
--------------------------------------------------
trade tradeid 1 / price 3725.18 / size 0
--------------------------------------------------
tradeid 0 / price 3643.35 / size 0
OPERATION PROFIT GROSS -11.83 NET -11.83 EQUITY 10000023.65
--------------------------------------------------
tradeid 1 / price 3725.18 / size 0
OPERATION PROFIT GROSS -11.83 NET -11.83 EQUITY 10000023.65

----------------------------------------------------------------------------------------------
class SMAStrategy(bt.Strategy):
    params = (
        ('period', 10),
    )

    def notify_order(self, order):
        print('-' * 50)
        print('order tradeid %d / price %.2f / size %d' %
              (order.tradeid, order.executed.price, order.executed.size))

    def notify_trade(self, trade):
        print('-' * 50)
        print('trade tradeid %d / price %.2f / size %d' %
              (trade.tradeid, trade.price, trade.size))

        self.trades[trade.tradeid] = trade

    def __init__(self):
        self.trades = dict()
        sma = btind.SMA(self.data, period=self.p.period)
        self.sig = btind.CrossOver(self.data.close, sma)
        self.tradeid = 0
    def next(self):
        if self.tradeid > 1 and (self.position.size == -2):
            self.buy(tradeid=0)
            self.buy(tradeid=1)
        elif self.tradeid < 2 and self.sig > 0:
            self.sell(tradeid=self.tradeid % 2)
            self.tradeid += 1
        
    def stop(self):
        for tradeid in sorted(self.trades):
            trade = self.trades[tradeid]
            print('-' * 50)
            print('tradeid %d / price %.2f / size %d' %
                  (trade.tradeid, trade.price, trade.size))

            print('OPERATION PROFIT GROSS %.2f NET %.2f EQUITY %.2f' %
                     (trade.pnl, trade.pnlcomm, self.broker.getvalue()))

**Comment by mementum** [comment]
I fear that my implementation of the tradeid to differentiate trades was not so deep to keep the separate PnL accounts. In this case because the broker holds a "single" position for each data, the average price of the position changes with the 2nd order and that's why the cancellation of the position (which takes place at the same time) generates the same PnL figure for both.

Having perused my own code for the broker I think adding the tradeid is feasible without breaking anything and having therefore separate positions in the broker.

**Comment by mementum** [comment]
Release 1.1.14.88 contains code to address the issue.

The final output of the reworked strategy you posted above

```
--------------------------------------------------
tradeid 0 / price 3643.35 / size 0
OPERATION PROFIT GROSS -52.74 NET -52.74 EQUITY 9999976.35
--------------------------------------------------
tradeid 1 / price 3725.18 / size 0
OPERATION PROFIT GROSS 29.09 NET 29.09 EQUITY 9999976.35
```

The equity change: 9999976.35 - 10000000 = -23.65
 
And -52.74 + 29.09 = -23.65
