### ISSUE TITLE
Sell is not excuted. Are there any program misses in my code?

### ISSUE THREAD

**Issue by InouReo** [mementum/backtrader#260]
Thank you for your attention. I write the simple code to refer to Quick start. I feed my yahoo csv data to load ^NI225 csv data in local. And I define the duration from 2014/10/01 to 2014/12/31, and run my program, and I can not create SELL EXECUTED. Are there any misses to write my code . 
It is shown my code and csv file below.

my enviroment 
python3.5
windows7 

code https://gist.github.com/InouReo/964c9a1a154d32ce81a189dc9f76b29b
^NI225 csv file https://gist.github.com/InouReo/2067ebd99cc88ce88076de893a711845

**Comment by InouReo** [comment]
I solve my problems. If I load my file line "***_***.csv", it can not work property. So I should change my file name. Thank you.

**Comment by mementum** [comment]
In any case and quoting from the main page of the repository:

> Note:

> > Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com
