### ISSUE TITLE
Adding tz= to GenericCSVData feed definition errors out with NoMethod error for tz.localize

### ISSUE THREAD

**Issue by rterbush** [mementum/backtrader#262]
Errors out with the following error, Python2 and Python3
```
  File "/home/inmate/.virtualenvs/backtrader2/lib/python2.7/site-packages/backtrader/feed.py", line 204, in _gettz
    return bt.utils.date.Localizer(self.p.tz)
  File "/home/inmate/.virtualenvs/backtrader2/lib/python2.7/site-packages/backtrader/utils/dateintern.py", line 48, in Localizer
    tz.localize = types.MethodType(localize, tz)
AttributeError: 'unicode' object has no attribute 'localize'
```

**Comment by rterbush** [comment]
Just to add another observation here, if I set different sessionend= for the two different instruments I am importing (ES and SPY), there is no context of timezone without setting `tz=`. I am also not clear on how the system handles this when backfilling or if it even uses it.

I've noticed this when in backtest and trying to backtest with different sessionend set. The result is multiple passes through next.

**Comment by mementum** [comment]
This is documented here:

[Docs - DateTime Management](https://www.backtrader.com/docu/timemgmt.html)

> The end user can override and determine the actual timezone for the output

>  - Providing a tz parameter to the data source. This must be an object compatible with the datetime.tzinfo interface. Most likely the user will provide a pytz.timezone instance

This was extended in the case of `IBData` because the platform provides timezone information and 
`IBData` makes every possible effort to create a *timezone* object even locally importing `pytz`.

In the case of the `GenericCSVData` the expectation is to pass a `pytz` compatible object.

**Comment by mementum** [comment]
> Just to add another observation here, if I set different sessionend= for the two different instruments I am importing (ES and SPY), there is no context of timezone without setting tz=. I am also not clear on how the system handles this when backfilling or if it even uses it.

The `backfill_from` source is only used to fill the initial data until the source is exhausted. By the time the `datetime` timestamp gets to the actual data, the timestamp is already in `UTC`-like format (either because a `timezone` instance has been used to transform it or because it is taken at face value when no timezone is present) and simply stored as it is.

> I've noticed this when in backtest and trying to backtest with different sessionend set. The result is multiple passes through next.

This is a design decision. For each tick you get a call to `next`. Regardless of the number of data sources and how many of them have actually produced a tick. Imagine the case in which a trader wants to trade the `DJI` and the `DAX`. The `DAX` has more trading days and those extra days, the trader may still want to access the last value of the data source and that of the associated indicators. If one waited until the `DJI` was ticking again, some of the ticks of the `DAX` would be lost.

**Comment by rterbush** [comment]
Ok, makes sense.

Even after setting a pytz object and using `tz=` to set the appropriate timezone for each `GenericCSVData` feed, I get the same error:
```
   tz.localize = types.MethodType(localize, tz)
AttributeError: 'unicode' object has no attribute 'localize'
```

I've done:
```
EST = pytz.timezone('US/Eastern')
CST = pytz.timezone('US/Central')
```

and in case of the SPY feed

```
tz='EST'
```

**Comment by mementum** [comment]
The error indicates that a string is still being passed to `GenericCSVData`. The code for initial timezone paris is generic for all data feeds (unless overriden like in the case of `IBData`)

See this code with a `pytz` object with `Europe/Berlin` and produces two different timezones. The one from the `Strategy` is `UTC` and the other has a 1 or 2 hours offset (winter/summer)

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)


import argparse
import datetime

import pytz

import backtrader as bt


class St(bt.Strategy):
    params = (
    )

    def __init__(self):
        pass

    def next(self):
        print('--', ','.join(map(str, [len(self), self.datetime.datetime()])))
        d = self.data0
        print(','.join(str(x) for x in
                       [len(self), self.datetime.datetime(),
                        len(d), d.datetime.datetime(), d.close[0]]))


def runstrat(args=None):
    args = parse_args(args)
    cerebro = bt.Cerebro()

    mytz = pytz.timezone('Europe/Berlin')
    print('MYTZ is:', mytz)
    # Data feed kwargs
    kwargs = dict(
        # sessionend=datetime.time(23, 59, 59),
        tz=mytz,
    )

    # Parse from/to-date
    dtfmt, tmfmt = '%Y-%m-%d', 'T%H:%M:%S'
    for a, d in ((getattr(args, x), x) for x in ['fromdate', 'todate']):
        if a:
            strpfmt = dtfmt + tmfmt * ('T' in a)
            kwargs[d] = datetime.datetime.strptime(a, strpfmt)

    # Data feed
    data0 = bt.feeds.GenericCSVData(dataname=args.data0,
                                    dtformat='%Y-%m-%d',
                                    **kwargs)
    # cerebro.adddata(data0)
    cerebro.resampledata(data0, timeframe=bt.TimeFrame.Days, compression=1)

    # Broker
    cerebro.broker = bt.brokers.BackBroker(**eval('dict(' + args.broker + ')'))

    # Sizer
    cerebro.addsizer(bt.sizers.FixedSize, **eval('dict(' + args.sizer + ')'))

    # Strategy
    cerebro.addstrategy(St, **eval('dict(' + args.strat + ')'))

    # Execute
    cerebro.run(**eval('dict(' + args.cerebro + ')'))

    if args.plot:  # Plot if requested to
        cerebro.plot(**eval('dict(' + args.plot + ')'))


def parse_args(pargs=None):
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description=(
            'Sample Skeleton'
        )
    )

    parser.add_argument('--data0', default='../../datas/2005-2006-day-001.txt',
                        required=False, help='Data to read in')

    # Defaults for dates
    parser.add_argument('--fromdate', required=False, default='',
                        help='Date[time] in YYYY-MM-DD[THH:MM:SS] format')

    parser.add_argument('--todate', required=False, default='',
                        help='Date[time] in YYYY-MM-DD[THH:MM:SS] format')

    parser.add_argument('--cerebro', required=False, default='',
                        metavar='kwargs', help='kwargs in key=value format')

    parser.add_argument('--broker', required=False, default='',
                        metavar='kwargs', help='kwargs in key=value format')

    parser.add_argument('--sizer', required=False, default='',
                        metavar='kwargs', help='kwargs in key=value format')

    parser.add_argument('--strat', required=False, default='',
                        metavar='kwargs', help='kwargs in key=value format')

    parser.add_argument('--plot', required=False, default='',
                        nargs='?', const='{}',
                        metavar='kwargs', help='kwargs in key=value format')

    return parser.parse_args(pargs)


if __name__ == '__main__':
    runstrat()
```

```
MYTZ is: Europe/Berlin
-- 1,2005-01-04 23:59:59.999989
1,2005-01-04 23:59:59.999989,1,2005-01-05 00:59:59.999989,2971.12
-- 2,2005-01-06 23:59:59.999989
2,2005-01-06 23:59:59.999989,2,2005-01-07 00:59:59.999989,2966.24
-- 3,2005-01-08 23:59:59.999989
3,2005-01-08 23:59:59.999989,3,2005-01-09 00:59:59.999989,2979.82
-- 4,2005-01-12 23:59:59.999989
...
252,2006-12-15 23:59:59.999989,252,2006-12-16 00:59:59.999989,4140.66
-- 253,2006-12-19 23:59:59.999989
253,2006-12-19 23:59:59.999989,253,2006-12-20 00:59:59.999989,4100.48
-- 254,2006-12-21 23:59:59.999989
254,2006-12-21 23:59:59.999989,254,2006-12-22 00:59:59.999989,4112.1
-- 255,2006-12-23 23:59:59.999989
255,2006-12-23 23:59:59.999989,255,2006-12-24 00:59:59.999989,4073.5
-- 256,2006-12-29 23:59:59.999989
256,2006-12-29 23:59:59.999989,256,2006-12-30 00:59:59.999989,4119.94
```

**Comment by rterbush** [comment]
because I was quoting the pytz object as a string... :man_facepalming:

**Comment by rterbush** [comment]
@mementum reopening this briefly for a point of clarification.

I notice that on the ibstore.getdata() calls I am passing a quoted string to the `tz=` parameter which may be part of my confusing here. Apparently that is acceptable there? Does that change with your commit above somehow?

Also, (possibly unrelated), noted today when starting the daily system that on every start, it was still showing most recent daily data from last Friday 2/10/17. Changing these `tz=` parameters several times and restarting, sometime after about the third start, after commenting out `tz=` in the static data feeds, yesterday's date (2/13/17) was seen. I changed back to include the `tz=` statements for the static feed to see if I could recreate but it had no effect on that test.

So not sure what is causing this behavior but am continue to see this on occasion.

**Comment by mementum** [comment]
Following this commit ab3563c7b0240cca15c196795d037d4284b30918 you can use `CST` and it will be internally translated to `CST6CDT`.

`IBData` has always accepted strings and tried to create `pytz` *timezones* using the strings. This code has been moved up the hierarchy to have all data feeds accepting *strings*.

You can freely choose whether to pass a string (the easiest probably) or a `pytz` instance.

The other thing is something which cannot for sure be diagnosed remotely.
