### ISSUE TITLE
Tick Data and Resampling not working

### ISSUE THREAD

**Issue by parrondo** [mementum/backtrader#263]
Again following the blog entry "Tick Data and Resampling" after command:

$ ./resample-tickdata.py

I get errors  with the folowing as last ones:

```
  File "/home/myuser/anaconda2/envs/backtrader/lib/python3.5/site-packages/matplotlib/dates.py", line 983, in __call__
    self.refresh()
  File "/home/myuser/anaconda2/envs/backtrader/lib/python3.5/site-packages/matplotlib/dates.py", line 1004, in refresh
    self._locator = self.get_locator(dmin, dmax)
  File "/home/myuser/anaconda2/envs/backtrader/lib/python3.5/site-packages/backtrader/plot/locator.py", line 219, in get_locator
    locator = MicrosecondLocator(interval, tz=self.tz)
UnboundLocalError: local variable 'interval' referenced before assignment_
```
Thank you and Good luck.

**Comment by mementum** [comment]
Resampling works or else the error wouldn't be the one it is.

The plotting code was changed to adapt indices to the (not so straight) datetime management from `matplotlib`. Not many people plot *ticks* and apparently these was never tested.

**Comment by parrondo** [comment]
Ok, so you mean now it is not possible to get the following plotting (it is from your blog), is this right?, if so why not?:
![tickdata-default1](https://cloud.githubusercontent.com/assets/10158607/22996712/01e851c2-f3d0-11e6-91a5-ee0662fba9ea.png)

**Comment by mementum** [comment]
The sample was old and didn't specify the ticks timeframe following old (very ambitions conventions) The code could still have failed due to int/float conversions for time adjustment. Use the commit that references this item.

It will be merged in the next release.
