### ISSUE TITLE
Resampling for intraday data sets the datetime of last bar to sessionend

### ISSUE THREAD

**Issue by dimitar-petrov** [mementum/backtrader#264]
Scenario is resampling 5 minute OHLC to 1 hour OHLC.

After 7b0577af6e5d173eebcbf6e79a31e8febabd67c9 the last bar datetime of the day changed from last hour data to the sessionend.

```8c8
< 13,6,1983-03-02 23:59:59.999989,152.18,152.23,152.02,152.03,,152.03,Strategy,6,723971.9999999999
---
> 13,6,1983-03-02 15:00:00,152.18,152.23,152.02,152.03,,152.03,Strategy,6,723971.625
15c15
< 13,13,1983-03-03 23:59:59.999989,153.38,153.48,153.38,153.48,,153.48,Strategy,13,723972.9999999999
---
> 13,13,1983-03-03 16:00:00,153.38,153.48,153.38,153.48,,153.48,Strategy,13,723972.6666666666
```

Was this requested behaviour?

**Comment by mementum** [comment]
See here: https://community.backtrader.com/topic/200/time-in-bar-s-datetime-is-not-correct-in-version-1-9-29-108-comparing-to-1-9-14-102
