### ISSUE TITLE
No execution on order_target_value and order_target_percent happens if open price of the bar is different from close price of the previous bar

### ISSUE THREAD

**Issue by ab-trader** [mementum/backtrader#270]
Currently size of the position for `order_target_value` and `order_target_percent` is calculated based on the close of the bar at which order is issued. By default this order is executed at the open of the next bar. If this open is higher (for long signals) than previous close, then position can be skipped totally due to lack of funds. Such behavior was observed with targets of 95-100% of the broker value.

**Comment by mementum** [comment]
Not an issue: https://community.backtrader.com/topic/217/order_target_percent-calculation-problems/4
