### ISSUE TITLE
daily return and Sharpe ratio with daily return

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#28]
Given that backtrader supports tick data and minute bar data, I think it will make sense to add supports for calculations of daily returns and Sharpe ratio based on daily returns.

**Comment by mementum** [comment]
It would indeed make sense. Probably making the next release.

**Comment by mementum** [comment]
In the works, configurable with a timeframe "parameter" for a "Returns" analyzer.

The SharpeRatio analyzer already had this param although it was so far unused and will be used to pass it over to "Returns"

**Comment by mementum** [comment]
The development branch contains the implementation (following all internal tests, it seems to be working). Commit: fc4046b219ed4c6bccf7918d2c3cdea993770e9c.

If you install it with python setup.py you can give it a try.

The sample analyzer-annualreturn has been updated to support the new TimeReturn analyzer, which (unless an error has been made) analyzes Returns for the given TimeFrame/Compression.

Although compression probably only makes sense in sub-day environments to say 60 minutes compression for the returns in 1 hour periods (whether measuring that is reasonable or not, that's another discussion)

The SharpeRatio analyzer has been also changed to use the TimeReturn, supporting with it timeframe and compression parameters.

If SharpeRatio gets a parameter "legacyannual" set to True, it will still use the previous AnnualReturn analyzer which will of course only work in a yearly timeframe

**Comment by mementum** [comment]
Pushed 1.1.19.88 with the above added
