### ISSUE TITLE
_clk_update() often doesn't find any datas with len() > 0 in startup

### ISSUE THREAD

**Issue by rterbush** [mementum/backtrader#282]
I see this issue almost every time I start a system. The system has 3 live feeds and 2 static backfill feeds and connects to IB for live data. After looking at the code in _clk_update(), I'll give `oldsync` a try to see if that may resolve this. If so, we may want to default to this for at least all IB connections? I suspect that at least the first time or two is caused by the IB interface being a bit slow to respond after being unused overnight, but just a guess.

The code:
```python
    def _clk_update(self):
        if self._oldsync:
            clk_len = super(Strategy, self)._clk_update()
            self.lines.datetime[0] = max(d.datetime[0]
                                         for d in self.datas if len(d))
            return clk_len

        newdlens = [len(d) for d in self.datas]
        if any(nl > l for l, nl in zip(self._dlens, newdlens)):
            self.forward()

        self.lines.datetime[0] = max(d.datetime[0]
                                     for d in self.datas if len(d))
        self._dlens = newdlens

        return len(self)
```

The error:
```
  File "python3.6/site-packages/backtrader/lineiterator.py", line 240, in _next
    clock_len = self._clk_update()
  File "python3.6/site-packages/backtrader/strategy.py", line 285, in _clk_update
    newdlens = [len(d) for d in self.datas]
  File "python3.6/site-packages/backtrader/strategy.py", line 285, in <listcomp>
    newdlens = [len(d) for d in self.datas]
  File "python3.6/site-packages/backtrader/lineseries.py", line 432, in __len__
    return len(self.lines)
  File "python3.6/site-packages/backtrader/lineseries.py", line 199, in __len__
    return len(self.lines[0])
ValueError: __len__() should return >= 0
```

**Comment by rterbush** [comment]
Setting `oldsync` has effect of causing the system to block after loading the first data feed, so that appears to not be a solution. Will report more as I learn more.

**Comment by mementum** [comment]
`ValueError: __len__() should return >= 0`

This is the key. It means that one line has been pushed backwards simply too much during resampling or replaying (the latter being more often the culprit). The actual code shown above is only where the problem manifests.

Will only be cured when the rework of resampling/replaying takes place as expressed here: [Community - v1.x -Quick Roadmap](https://community.backtrader.com/topic/195/v1-x-quick-roadmap/)

**Comment by mementum** [comment]
Cannot be fixed in current versions
