### ISSUE TITLE
On IB data feeds, reconnect=-1 is not working as expected

### ISSUE THREAD

**Issue by rterbush** [mementum/backtrader#283]
I'll report more info as I collect it but wanted to put it on our radar here.

I've set `reconnect=-1` and `timeout=10` for connections to IB API. Reliably, every night when API data goes away for some period of time, they system fails to reconnect.

My connection to IB is through IBcontroller managing IBgateway connection. The IB API is available with restart of the BT system the next morning, so IBcontroller is properly reestablishing the connection to IB when it comes back online.

**Comment by jaikumarm** [comment]
+1

**Comment by mementum** [comment]
```python
        retries = self.p.reconnect
        if retries >= 0:
            retries += firstconnect

        while retries < 0 or retries:
            if not firstconnect:
                time.sleep(self.p.timeout)

            firstconnect = False

            if self.conn.connect():
                if not fromstart or resub:
                    self.startdatas()
                return True  # connection successful

            if retries > 0:
                retries -= 1
```

What exactly is happening isn't clear. But the code above is the one that takes `self.p.reconnect` into account. If the value is `-1` the loop will run forever because of the condition: `while retries < 0 or ...`.

And the value of `retries` (which is taken from `self.p.reconnect`) is always `< 0` and remains untouched at the end of the loop.

**Comment by rterbush** [comment]
Looking at ibPY, and not being fully clear how python would handle this:
https://github.com/blampe/IbPy/blob/master/ib/opt/connection.py#L62

If an exception is returned, will that evaluate false at the `if self.conn.connect()`

Should there be a try: there instead?

**Comment by rterbush** [comment]
I put some prints in the code above and am finding that when BT loses data source, it does not see this code. Actually appears that BT is unaware that it is not getting data.

**Comment by mementum** [comment]
https://community.backtrader.com/topic/281/next-not-generated-anymore-after-ib-and-trader-workstation-connectivity-lost/

This may be related. If it is so, `-1` is not meant for that connectivity. It is meant for the local connectivity to `TWS`. If `TWS` is alive, connectivity from the point of view of the data feed is still there. Data is simply not coming in. The data feed, in any case, knows that the data is in delayed mode.
