### ISSUE TITLE
pandas dataframe backtest errors on the pyfoliotest.py example(pyfolio 0.6.0 version old runable)

### ISSUE THREAD

**Issue by EYcab** [mementum/backtrader#285]
I have checked the process step by step and find my data loading process is perfectly fine. self.datas has my data in a proper form. I have got the following in a long sequence. But the result look wrong in the summary table. What have I done wrong?Or there is a bug in the backtrader codes I don't know.Please let me know. (Note:I used the 0.6.0.Pyfolio which works fine with the txt sample you had in pyfoliotest.py)
...
...
5
4.67
TTTTTTTTTTThere 0
1
Hellllllllllllllllllllllllllo
5.53
TTTTTTTTTTThere 0
5
10.21
TTTTTTTTTTThere 0
7
Entire data start date: 2012-07-02
Entire data end date: 2016-12-30

Out-of-Sample Months: 50
Backtest Months: 2
Performance statistics   All history  Backtest  Out of sample
cum_returns_final               0.00      0.00           0.00
annual_return                   0.00      0.00           0.00
annual_volatility               0.00      0.00           0.00
sharpe_ratio                     nan       nan            nan
calmar_ratio                     nan       nan            nan
stability_of_timeseries         0.00      0.00           0.00
max_drawdown                    0.00      0.00           0.00
omega_ratio                      nan       nan            nan
sortino_ratio                    nan       nan            nan
skew                            0.00      0.00           0.00
kurtosis                       -3.00     -3.00          -3.00
tail_ratio                       nan       nan            nan
common_sense_ratio               nan       nan            nan
information_ratio              -0.07     -0.12          -0.07
alpha                           0.00      0.00           0.00
beta                            0.00      0.00           0.00
Worst Drawdown Periods net drawdown in %  peak date valley date recovery date  \
0                                   0.00 2012-07-02  2012-07-02    2012-07-02   
1                                   0.00 2012-07-02  2012-07-02    2012-07-02   
2                                   0.00 2012-07-02  2012-07-02    2012-07-02   
3                                   0.00 2012-07-02  2012-07-02    2012-07-02   
4                                   0.00 2012-07-02  2012-07-02    2012-07-02   

Worst Drawdown Periods duration  
0                             1  
1                             1  
2                             1  
3                             1  
4                             1  

[ 0.  0.]

##---------------------------------------------------------------------
My codes is listed as below:
###--------------------------

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)
import pandas as pd
import numpy as np
from alpha101_factors import *
import warnings

warnings.filterwarnings('ignore')
import MySQLdb

conn = MySQLdb.connect(host="localhost", user="rt", passwd="123", db="securities", charset="utf8")
# SEC = "Select * from hs300_sectors"
hs300 = "SELECT ticker,tradeDate,accumAdjFactor,open,high,low,close,vwap,volume " \
        "FROM securities.hs_ffill_data where tradeDate>'2012-07-01  00:00:00'and ticker " \
        "in('600000','600271','600266','600598','600256','000680','000921');"

# sec_data = pd.read_sql(SEC,conn)
hs300_data = pd.read_sql(hs300, conn)
hs300_data = hs300_data.rename(index=str, columns={"tradeDate": 'Date'})
conn.close()
hs300_data['Date']=pd.to_datetime(hs300_data['Date'])
#==============================================================================
items = ['accumAdjFactor','open','high','low','close','vwap','volume']
#==============================================================================
#items = ['open','high','low','close','volume']
fin_panel = pd.Panel(dict(zip(items, [hs300_data.pivot(index='Date', columns='ticker', values=i) for i in items])))
#==============================================================================
# from alpha101_factors import *
# fin_panel['alpha38']=Alphas(fin_panel).alpha038()
#==============================================================================
fin_panel['open']=fin_panel['open']/fin_panel['accumAdjFactor']
fin_panel['high']=fin_panel['high']/fin_panel['accumAdjFactor']
fin_panel['low']=fin_panel['low']/fin_panel['accumAdjFactor']
fin_panel['Adj Close']=fin_panel['close']
fin_panel['close']=fin_panel['close']/fin_panel['accumAdjFactor']
fin_panel = fin_panel.transpose(2,1,0)

#print(fin_panel['600000'][['open','high','low','close','volume']])
import argparse
import datetime
import random
import backtrader as bt
import pandas

class St(bt.Strategy):
    params = (
        ('printout', False),
        ('stake', 100000),
    )

    def __init__(self):
        pass

    def start(self):
        if self.p.printout:
            txtfields = list()
            txtfields.append('Len')
            txtfields.append('Datetime')
            txtfields.append('Open')
            txtfields.append('High')
            txtfields.append('Low')
            txtfields.append('Close')
            txtfields.append('Volume')
            txtfields.append('OpenInterest')
            print(','.join(txtfields))

    def next(self):
        if self.p.printout:
            # Print only 1st data ... is just a check that things are running
            txtfields = list()
            txtfields.append('%04d' % len(self))
            txtfields.append(self.data.datetime.datetime(0).isoformat())
            txtfields.append('%.2f' % self.data0.open[0])
            txtfields.append('%.2f' % self.data0.high[0])
            txtfields.append('%.2f' % self.data0.low[0])
            txtfields.append('%.2f' % self.data0.close[0])
            txtfields.append('%.2f' % self.data0.volume[0])
            txtfields.append('%.2f' % self.data0.openinterest[0])
            print(','.join(txtfields))

        # Data 0
        for d in self.datas:
            print(d.close[0])
            toss = random.randint(1, 10)
            curpos = self.getposition(d)
            print("TTTTTTTTTTThere",curpos.size)
            print(toss)
            if curpos.size:
                print("here",curpos.size)
                if toss > 5:
                    size = curpos.size // 2
                    self.sell(data=d, size=size)
                    if self.p.printout:
                        print('SELL {} @%{}'.format(size, d.close[0]))

            elif toss < 5:
                print('Hellllllllllllllllllllllllllo')
                self.buy(data=d, size=self.p.stake)
                if self.p.printout:
                    print('BUY  {} @%{}'.format(self.p.stake, d.close[0]))

def runstrat(args=None):
    args = parse_args(args)
    cerebro = bt.Cerebro()
    cerebro.broker.set_cash(args.cash)
    dkwargs = dict()
    if args.fromdate:
        fromdate = datetime.datetime.strptime(args.fromdate, '%Y-%m-%d')
        dkwargs['fromdate'] = fromdate

    if args.todate:
        todate = datetime.datetime.strptime(args.todate, '%Y-%m-%d')
        dkwargs['todate'] = todate

    # Add a strategy
    for i in ['600000','600271','600266','600598','600256','000680','000921']:
        dataframe = fin_panel[i][['open','high','low','close','volume','Adj Close']]
        # Pass it to the backtrader datafeed and add it to the cerebro
        data = bt.feeds.PandasData(dataname=dataframe)
        cerebro.adddata(data,name=i)

    # Run over everything
    cerebro.addstrategy(St, printout=args.printout)
    if not args.no_pyfolio:
        cerebro.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio')
    results = cerebro.run()
    # Plot the result
    if not args.no_pyfolio:
        strat = results[0]
        pyfoliozer = strat.analyzers.getbyname('pyfolio')

        returns, positions, transactions, gross_lev = pyfoliozer.get_pf_items()
        if args.printout:
            print('-- RETURNS')
            print(returns)
            print('-- POSITIONS')
            print(positions)
            print('-- TRANSACTIONS')
            print(transactions)
            print('-- GROSS LEVERAGE')
            print(gross_lev)

        import pyfolio as pf
        pf.create_full_tear_sheet(
            returns,
            positions=positions,
            transactions=transactions,
            gross_lev=gross_lev,
            live_start_date='2012-09-01',
            round_trips=True)

    if args.plot:
        cerebro.plot(style=args.plot_style)
def parse_args(args=None):

    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description='Sample for pivot point and cross plotting')

    parser.add_argument('--fromdate', required=False,
                        default='2012-09-01',
                        help='Starting date in YYYY-MM-DD format')

    parser.add_argument('--todate', required=False,
                        default='2016-12-31',
                        help='Ending date in YYYY-MM-DD format')

    parser.add_argument('--printout', required=False, action='store_true',
                        help=('Print data lines'))

    parser.add_argument('--cash', required=False, action='store',
                        type=float, default=50000,
                        help=('Cash to start with'))

    parser.add_argument('--plot', required=False, action='store_true',
                        help=('Plot the result'))

    parser.add_argument('--plot-style', required=False, action='store',
                        default='bar', choices=['bar', 'candle', 'line'],
                        help=('Plot style'))

    parser.add_argument('--no-pyfolio', required=False, action='store_true',
                        help=('Do not do pyfolio things'))
    import sys
    aargs = args if args is not None else sys.argv[1:]
    return parser.parse_args(aargs)

if __name__ == '__main__':
    runstrat()

**Comment by mementum** [comment]
As stated in the README

> Note:

> > Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com
