### ISSUE TITLE
start date larger than end date when get pyfolio analzyer for multi-timeframe strategy

### ISSUE THREAD

**Issue by zhuoqiang** [mementum/backtrader#286]
If using multi-timeframe strategy, 5min and 1day data for example (pass lower timeframe first as doc says), then after run, when get pyfolio analyzer, the `position` dataframe's start date larger than end data, as following:

```
                                   cash
Datetime                                
2017-02-28 00:00:00+00:00  0.0    2092.0
2017-01-06 00:00:00+00:00  0.0  100000.0
2017-01-09 00:00:00+00:00  0.0  100000.0
 ...

2017-02-23 00:00:00+00:00  0.0    2092.0
2017-02-24 00:00:00+00:00  0.0    2092.0
2017-02-27 00:00:00+00:00  0.0    2092.0
```

notice the first date is `2017-02-28` and last is `2017-02-27`

Also since we are using 5min data, however the datetime only shows date without time informaiton.

The graphic cerebro plot is problem as well:

![bug](https://cloud.githubusercontent.com/assets/639099/24034548/a32ddda4-0b2c-11e7-9449-e040840380ce.png)

Notice the lower part of the graphic is compressed a lot.

**Comment by mementum** [comment]
The information is clearly insufficient to understand if there is an issue. The chart even shows that the data feed at the top is `1-day` and not `5-minutes` (or this information has not been given to the platform)

Should you have more information, please add it to the ticket.
