### ISSUE TITLE
suggest using enum instead of int for status defination

### ISSUE THREAD

**Issue by zhuoqiang** [mementum/backtrader#287]
There are lots of constant status definiation in backtest, for example:

bt.Order.Submitted, however they are simply integer. How about using enum instead. 

the prons are:

- the enum value are truely constant, prevent people from change it by mistake
- the enum value could give meaningful string represent when print, instead of `1` we get `order.Submitted`

The API could stay compatible after the change and python2.7 could also be supported with third party [enum](https://pypi.python.org/pypi/enum) library.

**Comment by mementum** [comment]
As stated in the front page of the repository in the `README`

> Note:

> > Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com
