### ISSUE TITLE
line info lost during resampling

### ISSUE THREAD

**Issue by JohnShiuHK** [mementum/backtrader#288]
Hi,
I start using backtrader recently and have nice experience with it. This is the best package I found so far for doing backtest.
However, I have got a problem when using the `Cerebro.resampledata`

First of all, I wrote a customized pandasdata class, in which I added a field "code", to fit the data format in my database:
```
class PandasData_Customize(feeds.PandasData):
    params = (("code", "code"), )
    lines = ("code", )
    datafields = [............., "code"]

```
The "code" would be something like ES, DX, etc.... It is supposed to be unique for an asset, i.e. data.code is unique for each data in self.datas

It has been working well (daily data) with `Cerebro.adddata(PandasData_Customize(dataname=df))`
The data.code from the `output = Cerebro.run()` are correct.

Recently, I am trying to backtest using monthly time frame, with:
`Cerebro.resampledata(PandasData_Customize(dataname=df), timeframe=TimeFrame.Months)`
But the data.code is always NaN

I tried to find hints from the "Resampling" session in the doc, but it seems the case for customized datafeeds is not mentioned yet. 
I also read some source codes from the cerebro.py and resamplerfilter.py, but still not sure which part I should modify for getting the correct resampling of the custom line I added.
Any hints/idea?

Thanks

**Comment by mementum** [comment]
As stated in the front page of the repository in the `README`

> Note:

> > Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com
