### ISSUE TITLE
percentage commissions and margins for futures products

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#29]
some global commodity futures products have percentage commissions and margins. I think it will be more convenient to be able to specify whether we need cash-based or percentage-based commissions/margins for futures products. I guess an extra input should do the job in comminfo?

**Comment by mementum** [comment]
The default CommissionInfo class is meant to support the 2 major types of trading (that I know of)

And specifying how the broker creates a commission scheme out of this with a single call.

The broker support additionally a 2nd call to add user-specified CommissionInfo objects, which may instances of the existing class with specific parameters or others with different functionality as long as they provide the same set of methods.

Other possible commission schemes (not that uncommon) are % based but with a cap at a given level or used a step based approach in which the % is decreased by going over certain amounts of turnover.

I will give it a though to try to see if a simple extension (if possible) of the existing class may be fit for the purpose or actually adding new subclasses of CommissionInfo may be more appropriate.

**Comment by mementum** [comment]
Most of the work is done to accomodate one parameter and also allow for easy addition of new Commission Schemes. With some testing and a post to document it still to be done.

Probably coming out on Friday/Saturday.

**Comment by mementum** [comment]
Released 1.1.17.88.

First post for the topic at: http://www.backtrader.com/posts/2015-11-05-commission-schemes-extended/commission-schemes-extended/

Another one to come in the next couple days
