### ISSUE TITLE
Error when using optstrategy with Pyfolio/SharpRatio analyer

### ISSUE THREAD

**Issue by zhuoqiang** [mementum/backtrader#291]
while optimize strategy with `Cerebro.optstrategy()` API, if `PyFolio` or `SharpRatio` analyzer added, there will be exception:

```py
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<backtrader.cerebro.OptReturn object at 0x11220feb8>]'. Reason: 'KeyError('__getstate__',)'
```

The following test reproduct this error:

```py

import backtrader as bt
import backtrader.feeds as btfeeds
import pandas as pd

class S(bt.Strategy):
    def __init__(self):
        self.order = None

    def next(self):
        if not self.order:
            self.order = self.buy()

def test_bug_optimize_with_special_analyzer():
    c = bt.Cerebro()
    c.optstrategy(S)

    c.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio')
    c.addanalyzer(bt.analyzers.SharpeRatio, _name='sharp_ratio')

    class SimplePandasData(btfeeds.PandasData):
        params = dict(
            high=None,
            low=None,
            open=None,
            volume=None,
            openinterest=None,
        )
    index = pd.date_range('2017-01-01',
                          '2017-01-04',
                          freq='1 D')

    data = pd.DataFrame({'close':range(10000, 10000+len(index))},
                           index=index)

    c.adddata(SimplePandasData(data))
    c.run()
```

It seems there's unpickable object in the result if PyFolio/SharpRatio analyzer are included.

Besides the above tests are OK in old backtrader version. Maybe some recent code changes caused this bug.

**Comment by yangnw** [comment]
I second this bug. My backtrader version is 1.9.37.116.

Previously I've used 1.9.29.108 in which optimization works fine, but multi-timeframe backtesting was broken, for which reason I've just upgraded. So I will take the wild guess here that the rewritten data feeding process breaks the old pyfolio analyzer code.

**Comment by mementum** [comment]
The test from above was executed under Python 2.7 and Python 3.5 producing a grand total of 0 errors.

Should there be any further information of something being wrong please add it **TO THIS** issue.

**Comment by mementum** [comment]
Fix for #294 actually

**Comment by zhuoqiang** [comment]
Hi, the original test case passed, however, the following test case are still failed with following error message:

```sh
Traceback (most recent call last):
  File "a.py", line 44, in <module>
    c.run()
  File "/python3.5/site-packages/backtrader/cerebro.py", line 807, in run
    for r in pool.imap(self, iterstrats):
  File "/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<backtrader.cerebro.OptReturn object at 0x1060ac080>]'. Reason: 'KeyError('__getstate__',)'
```

```py
import backtrader as bt
import backtrader.feeds as btfeeds
import pandas as pd


def create_simple_data():
    data = pd.DataFrame(
        {'close': [100, 200, 300, 400]},
        index=pd.date_range('2017-01-01',
                            '2017-01-04',
                            freq='1 D')
    )
    return btfeeds.PandasData(
        dataname=data,
        high=None,
        low=None,
        open=None,
        volume=None,
        openinterest=None,
        close=-1,
    )

class S(bt.Strategy):
    def __init__(self):
        self.order = None

    def next(self):
        if not self.order:
            self.order = self.buy()



c = bt.Cerebro()
c.optstrategy(S)

# these 2 analyzer caused the exception
c.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio')
c.addanalyzer(bt.analyzers.SharpeRatio, _name='sharp_ratio')

data = create_simple_data()

c.adddata(data)
c.run()
```

BTW, I could not reopen this issue. Would you help re-open this issue and close the issue only after the confirmation?

**Comment by yangnw** [comment]
I'd also like to add that simply adding `cerebro.addanalyzer(bt.analyzers.PyFolio)` to backtrader/samples/optimization/optimization.py right before `cerebro.run()`, and running the script in a pyenv virtualenv, produces the same error, under both 3.6.0 and 3.5.3.

```
Traceback (most recent call last):
  File "optimization.py", line 199, in <module>
    runstrat()
  File "optimization.py", line 90, in runstrat
    stratruns = cerebro.run()
  File "/usr/local/pyenv/versions/cornucopia/lib/python3.6/site-packages/backtrader/cerebro.py", line 807, in run
    for r in pool.imap(self, iterstrats):
  File "/usr/local/pyenv/versions/3.6.0/lib/python3.6/multiprocessing/pool.py", line 699, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<backtrader.cerebro.OptReturn object at 0x7f9a10c7c4a8>]'. Reason: 'KeyError('__getstate__',)'
```

**Comment by mementum** [comment]
It is highly unlikely that the test script from above has been used to reproduce this or any other bug.

0. Without invoking the function nothing happens
1. Even if the function were to be called the invocation of `SimplePandasData` is wrong
2. And if the function were to be called, Python pickling rules dictate that which are not defined at root level within module are not pickable

**Comment by zhuoqiang** [comment]
Have you tried the above test script? It reproduce exactly this bug in my environment.

I'm afraid none of your statement is corret. The `SimplePandasData` is OK, actually I used it in lots of other tests. And even this test was passed in old backtrader version. It only breaks due to recent backtrader changes. 

Now in case you are lazy, here's another script to reproduce this bug without any suspicious problems you listed:

```py
import backtrader as bt
import datetime

class S(bt.Strategy):
    def __init__(self):
        self.order = None

    def next(self):
        if not self.order:
            self.order = self.buy()


if __name__ == '__main__':
    c = bt.Cerebro()
    c.optstrategy(S)

    c.addanalyzer(bt.analyzers.PyFolio, _name='pyfolio')
    c.addanalyzer(bt.analyzers.SharpeRatio, _name='sharp_ratio')

    data = bt.feeds.YahooFinanceData(
        dataname='YHOO',
        fromdate=datetime.datetime(2016, 12, 1),
        todate=datetime.datetime(2016, 12, 31),
        reverse=False)

    c.adddata(data)
    c.run()
```

This script do not need to invoke a test function, just run it and you will get the exception:

```sh
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<backtrader.cerebro.OptReturn object at 0x10710e240>]'. Reason: 'KeyError('__getstate__',)'
```

If you need further information I will provide you, but please do not close the issue while it is not fixed yet.

**Comment by mementum** [comment]
> Have you tried the above test script? It reproduce exactly this bug in my environment.

You must have a magic environment then and what's more you expect other people to do your homework.

> I'm afraid none of your statement is corret. The SimplePandasData is OK, actually I used it in lots of other tests. And even this test was passed in old backtrader version. It only breaks due to recent backtrader changes.

**Statement 0**

You even provided a 2nd script adding the invocation of the function. The statement is **CORRECT**. You provide scripts which do nothing and expect someone else to add things to get it running.

**Statement 1**
You ``SimplePandasData** is invoked as ``SimplePandasData(data)`` which if it really works is miraculously. Because the right invocation syntax is: `SimplePandasData(dataname=data)`. This statement is **CORRECT** too and reaffirms the point: your environment is special

**Statement 2**. 

  - For Pyhton 2.7: https://docs.python.org/2/library/pickle.html#what-can-be-pickled-and-unpickled
  - For Python 3.6.1 (for all Python 3.x): https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

In both links you may read the following:

  > - classes that are defined at the top level of a module

Your `SimplePandasData` is **NOT** defined at the top level of a module and cannot be pickled and therefore the script cannot run with it. This statement is also **CORRECT** and your environment is special again.

**3 OUT OF 3 Statements ARE CORRECT**. The question if the script has been **tried** is one you should be asking yourself before sending the script as proof of anything.

All of the above is reinforced by the fact that you now:

  0. Send a script which already invokes the code
  1. Has a data feed with the parameter `dataname=xxxx`
  2. Defines all things to be pickled at the top level of the module

It may seem like the 3 statements were **CORRECT**

An issue with **WRONG INFORMATION** can only be closed.

Furthermore: this is an open source project and there is no need to oblige anything.

**Comment by mementum** [comment]
And yes the new script has been tried (why the script has `reverse=False` is a mystery). And because it **runs** just fine ... one has to add a `print` line (the handyman's tool for real debugging) as in

```
    def next(self):
        print('%s: %.2f' % (self.datetime.date(), self.data.close[0]))
        if not self.order:
            self.order = self.buy()
```

Which produces the following output under both Python 2.7 and 3.5

```
2016-12-30: 38.67
2016-12-29: 38.64
2016-12-28: 38.73
2016-12-27: 38.92
2016-12-23: 38.66
2016-12-22: 38.50
2016-12-21: 39.15
2016-12-20: 39.16
2016-12-19: 38.42
2016-12-16: 38.61
2016-12-15: 38.41
2016-12-14: 40.91
2016-12-13: 41.47
2016-12-12: 41.30
2016-12-09: 41.76
2016-12-08: 41.41
2016-12-07: 40.52
2016-12-06: 39.97
2016-12-05: 40.20
2016-12-02: 40.07
2016-12-01: 39.63
```

Yes, with `reverse=False` the values go from the future to the past. It's not an error.

**Comment by mementum** [comment]
Which concludes that if in your environment your non-executable script with `SimplePandasData` was producing the same error, it's down your environment.

The `MaybeEncodingError` should also provide a good hint in that direction.

**Comment by zhuoqiang** [comment]
I get the following errors in python3.5 backtrader 1.9.39.116 with both new and old test script (with or without `reverse=False`)

```py
Traceback (most recent call last):
  File "a.py", line 29, in <module>
    c.run()
  File "/python3.5/site-packages/backtrader/cerebro.py", line 807, in run
    for r in pool.imap(self, iterstrats):
  File "/python3.5/multiprocessing/pool.py", line 695, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[<backtrader.cerebro.OptReturn object at 0x1034bc9b0>]'. Reason: 'KeyError('__getstate__',)'
```

And once the `addanalyer` statement removed, both the old and new test script run succesfully.

I'm not sure why you could not reproduce this bug. 

And from the comment, at least yangnw also suffer from the same issue.

**Comment by yangnw** [comment]
@mementum @zhuoqiang I think I've found the bug. It was introduced by commit a403a8, backtrader/lineiterator.py line 96-98. Commenting said lines suppresses the error. Maybe something ought to be added along with __getattr__() to make it pickle-friendly. To quote https://docs.python.org/3/library/pickle.html:

> Note At unpickling time, some methods like __getattr__(), __getattribute__(), or __setattr__() may be called upon the instance. In case those methods rely on some internal invariant being true, the type should implement __getnewargs__() or __getnewargs_ex__() to establish such an invariant; otherwise, neither __new__() nor __init__() will be called.
