### ISSUE TITLE
Yahoo Finance Data not loading.

### ISSUE THREAD

**Issue by romansemko** [mementum/backtrader#296]
I installed backtrader and wanted to try the quickstart examples. However, I am running into problems when reading yahoo finance data, online and offline. 

Online, this small example already fails:

```python
import backtrader as bt

bt.feeds.YahooFinanceData(dataname='goog').preload()
```
Error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-1aaa302f6996> in <module>()
      1 import backtrader as bt
----> 2 bt.feeds.YahooFinanceData(dataname='goog').preload()

/home/semkor/Envs/m/local/lib/python2.7/site-packages/backtrader/feed.pyc in preload(self)
    659 
    660         # preloaded - no need to keep the object around - breaks multip in 3.x
--> 661         self.f.close()
    662         self.f = None
    663 

AttributeError: 'NoneType' object has no attribute 'close'
```

Am I doing something wrong?

An offline example. I have a feed downloaded from yahoo manually and saved under `data/goog.csv`.
The structure of the file looks like this:

```
Date,Open,High,Low,Close,Volume,Adj Close
2017-04-19,839.789978,842.219971,836.289978,838.210022,954200,838.210022
2017-04-18,834.219971,838.929993,832.710022,836.820007,835300,836.820007
2017-04-17,825.01001,837.75,824.469971,837.169983,892300,837.169983
2017-04-13,822.140015,826.380005,821.440002,823.559998,1112500,823.559998
2017-04-12,821.929993,826.659973,821.02002,824.320007,894600,824.320007
2017-04-11,824.710022,827.427002,817.02002,823.349976,1076500,823.349976
2017-04-10,825.390015,829.349976,823.77002,824.72998,952900,824.72998
2017-04-07,827.960022,828.484985,820.513,824.669983,1053300,824.669983
2017-04-06,832.400024,836.390015,826.460022,827.880005,1251600,827.880005
...
```

I copy-paste the example from https://www.backtrader.com/docu/quickstart/quickstart.html#our-first-strategy, just replacing the datapath with:

```python
datapath = os.path.join(os.getcwd(), 'data/goog.csv')
```

The code seems to run through without errors, but there is no output from the `next()` call. The only thing that gets logged is:

```
Starting Portfolio Value: 100000.00
Final Portfolio Value: 100000.00
```

What am I doing wrong?

**Comment by romansemko** [comment]
Ok. Got the offline problem figured: I was not doing "reverse=True" **and** I was trying to get the data for GOOG for year 2000, which rendered an empty list, obviously.

The online issue still persists.

```
bt.feeds.YahooFinanceData(dataname='YHOO', fromdate=datetime.datetime(2011, 1, 1),todate=datetime.datetime(2012, 12, 31)).preload()
# FAIL
```

**Comment by mementum** [comment]
As stated in the front page of the repository in the `README`

> Note:

> > Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com
