### ISSUE TITLE
Feature Request: Save plot to file

### ISSUE THREAD

**Issue by cgi1** [mementum/backtrader#298]
It would be a nice feature to add an `file_path` option to `cerebro.plot(..)` which saves the generated plot to a file.

Side node for the first issue: 
You did some awesome work here! I was working with MT4 for a few years and right know I port some of my code to backtrader running a test setup of approx. 100 symbols periodically. After a test cycle has been finished I would love to iterate over the plots quickly. Keep up doing the good work.

**Comment by xnox** [comment]
Something like this:

https://github.com/mementum/backtrader/pull/297 ?

E.g. with that I can use `--plot savefig=True` and get PDF figures saved on disk from disk trader.

**Comment by cgi1** [comment]
Exactly! Thanks!
