### ISSUE TITLE
backtrader quickfix integration

### ISSUE THREAD

**Issue by baisjuan** [mementum/backtrader#299]
Hello mementum, how are you. 

I just wanted to ask, do you think it's possible to create a quickfix connection to receive live market data and transform it into a backtrader live feed? 

In addition, do you think it's possible to use backtrader to trade via a quickfix connection?

Thanks, regards! 

Juan

**Comment by baisjuan** [comment]
I'm new on this. Right now I'm trying to put the data I receive thought quickifx in a Panda dataframe and use that dataFrame as cerebro feed ....

**Comment by mementum** [comment]
As stated in the front page of the repository in the `README`

> Note:

> > Unless it is really an issue, please post feedback/questions and other things to https://community.backtrader.com
