### ISSUE TITLE
 cerebro.broker.setcash() doesn't work?

### ISSUE THREAD

**Issue by xingjianpan** [mementum/backtrader#3]
Hello, 

It looks  cerebro.broker.setcash() doesn't work as expected. 

I'd expect 'Final Portfolio Value' to be 200000.0 in below script, however it looks the result is always 10000.  

```python
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import backtrader as bt

if __name__ == '__main__':
    cerebro = bt.Cerebro()
    cerebro.broker.setcash(200000.0)

    print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())

    cerebro.run()

    print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
````

**Comment by mementum** [comment]
At the time of writing the quickstart the logic to initially set the cash was other.

Because the actual run is empty, cerebro was not executing any initialization of the broker, which prevents the cash from being set.

Corrected in order to set the cash even if no datas are available.

**Comment by xingjianpan** [comment]
Thanks @mementum!
