### ISSUE TITLE
Limit order is not getting executed

### ISSUE THREAD

**Issue by cgi1** [mementum/backtrader#308]
| Problem            	| Bracket Buy order does not get executed                                                                                           	|
|--------------------	|-------------------------------------------------------------------------------------------------------------------------------	|
| Symbol             	| 000001.SS                                                                                                                     	|
| Source Data        	| YahooFinance                                                                                                                  	|
| Backtrader-Version 	| 1.9.47.116                                                                                                                    	|
| Timeframe          	| Daily                                                                                                                         	|
| Date of occurrence 	| 2014-07-23                                                                                                                    	|
| Goal               	| Buy Bracket (Order.Limit) with buy_price over current candle|
| Expected behaviour 	| Buy gets executed and notify_order called if price goes above buy_price (Happens on 2014-07-24)                               	|
| Current behaviour  	| Order is not getting executed                                                                                                 	|

From the [documentation](https://www.backtrader.com/docu/order-creation-execution/order-creation-execution.html#limit) 

> The price set at order creation if the data touches it, starting with the next price bar

So the test scenario looks like the following:

<img width="842" alt="grafik" src="https://cloud.githubusercontent.com/assets/18695252/26065837/588aca5e-3995-11e7-9027-70a4f630204f.png">

The strategy creates a `buy bracket` on 2014-07-23:

<img width="773" alt="grafik" src="https://cloud.githubusercontent.com/assets/18695252/26065532/8f3115fa-3994-11e7-9512-ad557a03fd49.png">

2014-07-24 openes higher but the order is not getting executed:

<img width="787" alt="grafik" src="https://cloud.githubusercontent.com/assets/18695252/26065933/aa1cf450-3995-11e7-9b87-eda815586a09.png">

Nothing changed on 2014-07-25:

<img width="804" alt="grafik" src="https://cloud.githubusercontent.com/assets/18695252/26065975/c8b74550-3995-11e7-8aab-b27b348f4306.png">

**Comment by cgi1** [comment]
Oh damn.. `buy_bracket` is using a `limit` (not `stop`) order to get into the trade... 

So maybe it would be a good idea to have a `buy_bracket` `option` which sets the `main trade` to `OrdType` `Stop`?

**Comment by paduel** [comment]
Hello cg1.

Did you try _**buy_bracket(..., exectype=bt.Order.Stop, ...)**_   ?

**Comment by mementum** [comment]
https://www.backtrader.com/docu/order-creation-execution/bracket/bracket.html

The orders can be even created manually (and bound together) with full freedom to choose the order types (even if the combination wouldn't make sense)
