### ISSUE TITLE
Yahoo Finance data error

### ISSUE THREAD

**Issue by colehertz** [mementum/backtrader#309]
Hello,

Is anyone else having an issue loading data with the Yahoo Finance data feed?

Even this snippet from the examples, which was working a few days, is now not working. In the console, there is an error stating that 'NoneType' object has no attribute 'close'.
`data0 = bt.feeds.YahooFinanceData(dataname='YHOO', fromdate=datetime(2011, 1, 1),
                                  todate=datetime(2012, 12, 31))`

I suspect that Yahoo has changed the url for retrieving historical data. Has anyone encountered this issue and figured out an optimal solution?

Thank you!

**Comment by femtotrader** [comment]
Similar issue with pandas-datareader
https://github.com/pydata/pandas-datareader/issues/315
https://github.com/pydata/pandas-datareader/issues/330
https://github.com/pydata/pandas-datareader/issues/332
https://github.com/pydata/pandas-datareader/issues/333

This PR may be a workaround https://github.com/pydata/pandas-datareader/pull/331
