### ISSUE TITLE
Ichimoku: Not able to get line data with bar_shift>0 using resampled data

### ISSUE THREAD

**Issue by cgi1** [mementum/backtrader#312]
After switching from Yahoo finance API (#311) I now use hourly data from [Tickstory](https://tickstory.com). 
To use the daily timeframe the data is getting resampled:

```

data = bt.feeds.GenericCSVData(dataname=path_to_history_csv,
                           dtformat='%Y.%m.%d',
                           tmformat='%H:%M:%S',
                           datetime=0,
                           time=1,
                           open=2,
                           high=3,
                           low=4,
                           close=5,
                           volume=6,
                           openinterest=-1,
                           params={'1': 1,})

tframes = dict(daily=bt.TimeFrame.Days, weekly=bt.TimeFrame.Weeks,
                                   monthly=bt.TimeFrame.Months)

# --resample_to_timeframe daily --compression 1

cerebro.resampledata(data, timeframe=tframes[args.resample_to_timeframe],compression=compression)
```

The problem is, that checking the future cloud now gets an `IndexError`, because the line array is only filled in interval `[-already_proceed_bars,current_bar]` where `current_bar` is obv `0`.

```
self.ikh = bt.indicators.Ichimoku()
future_span_a = self.ikh.senkou_span_a[26]
[...]
IndexError: array index out of range
```

- A check of the future cloud using `self.ikh.senkou_span_a[26]` was possible using `bt.feeds.YahooFinanceData` in before. I see no reason why this happens depending of the feed?

- It works using the hourly data directly (without re-sampling)

**Comment by mementum** [comment]
Note:

  Unless it is really an issue, please post feedback/questions and other
  things to https://community.backtrader.com

**Comment by mementum** [comment]
The stream is clearly loaded without any timeframe indication.

**Comment by cgi1** [comment]
Thats a specific issue, not a general feedback or question.

**Comment by mementum** [comment]
No sample data is provided. No complete script is provided and the following question is asked:

>   - A check of the future cloud using self.ikh.senkou_span_a[26] was possible using bt.feeds.YahooFinanceData in before. I see no reason why this happens depending of the feed?

A very general question. The following is formulated:

> It works using the hourly data directly (without re-sampling)

And the subsequent comment is ignored:

> ... without any timeframe indication

Because it is answered with:

> ... If the data would be clearly loaded the indi could calculate future values.

Which clearly indicates that the key word **timeframe** was ignored (or overseen if your prefer)

This *issue* tracker is kept for reporting something which is a bug and can be proven as a bug (or at least has a high probability of being one with the behavior shown by data and snippets)

You may not like posting in the community. It's fair: don't do it. There is no absolutely no obligation to do it.

**Comment by cgi1** [comment]
Sample-data: [EURUSD_H1.csv.zip](https://github.com/mementum/backtrader/files/1021581/EURUSD_H1.csv.zip)

**issue312_strategy.py**
```
from backtrader import num2date
from datetime import datetime
import backtrader as bt

class Issue312Strategy(bt.Strategy):
    params = (
        ('fromdate_trading', datetime(2007, 1, 1)),
    )


    def __init__(self):

        self.ikh = bt.indicators.Ichimoku()


    def next(self):

        current_bar_time = num2date(self.datas[0].datetime[0])
        if current_bar_time < self.p.fromdate_trading:
            return

        self.ikh.senkou_span_a[26]
```

**issue_312.py**
```
import backtrader as bt
from issue312.issue312_strategy import Issue312Strategy
from datetime import datetime

cerebro = bt.Cerebro()
cerebro.broker.setcommission(commission=0.002)
cerebro.broker.setcash(100000)

path_to_history_csv = 'EURUSD_H1.csv'
data = bt.feeds.GenericCSVData(dataname=path_to_history_csv,
                                           dtformat='%Y.%m.%d',
                                           tmformat='%H:%M:%S',
                                           datetime=0,
                                           time=1,
                                           open=2,
                                           high=3,
                                           low=4,
                                           close=5,
                                           volume=6,
                                           openinterest=-1,
                                           params={'1': 1,})

tframes = dict(daily=bt.TimeFrame.Days, weekly=bt.TimeFrame.Weeks,
                               monthly=bt.TimeFrame.Months)

cerebro.resampledata(data, timeframe=bt.TimeFrame.Days,compression=1)


cerebro.addstrategy(Issue312Strategy,fromdate_trading=datetime(2008,10,3))

result = cerebro.run(tradehistory=True)
```

**Error in file** `issue312_strategy.py` **line** `self.ikh.senkou_span_a[26]`:

![no_senkou_span_a_future](https://cloud.githubusercontent.com/assets/18695252/26348126/ffe73fc8-3fab-11e7-9443-760599ea03d2.png)

**Comment by cgi1** [comment]
Changing **issue_312.py** from `resampledata` to **not-resample** data (hourly data):

```

#cerebro.resampledata(data, timeframe=bt.TimeFrame.Days,compression=1)
cerebro.adddata(data=data)
```

![ichimoku_working_not_resample](https://cloud.githubusercontent.com/assets/18695252/26348369/d1683e58-3fac-11e7-809e-dd2db9b59c5c.png)
