### ISSUE TITLE
Commission is not working properly for stocks

### ISSUE THREAD

**Issue by pmunin** [mementum/backtrader#314]
For Fidelity for stock transaction they charge $4.95 per transaction, regardless of the size of transaction
So I write the code:
`
 cerebro.broker.setcommission(commission=4.95, commtype = bt.CommInfoBase.COMM_FIXED, mult=0.0, stocklike=True)
`
However what I see in the log is:
`
BUY EXECUTED, Price: 67.30, Cost: 1009.50, Size: 15.00, Comm 74.25
`
So it calculates commission 4.95*15, which is incorrect. 

How to make is calculate correctly?

**Comment by mementum** [comment]
Not an issue.

From the front page of the repository:

> For **feedback/questions/issues** use the [Community](https://community.backtrader.com)
