### ISSUE TITLE
get universe / data names

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#34]
It will be nice to have a function to return a list of data names, something like self.getdatanames() from multiple data.

**Comment by mementum** [comment]
Not a big deal. Before the next release you can internally access the surrounding environment in a strategy using the built-in attribute "env" (stands for environment)

```
datanames = list(self.env.datasbyname.keys())
```

The "list" part being there to cope with the different Py2/Py3 behavior of the "keys" method.
