### ISSUE TITLE
historical trade records

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#40]
It's nice to be able to retrieve the historical trade records for trade level analysis. The following information are very useful.
- barlen / holding period
- name, datetime, price, size, orderid to open the position
- name, datetime, price, size, orderid to close the position
- pnl, pnlcomm, (pnl percentage ?) of the trade
- capable for user to add custom fields of the trade records (e.g. I would like to know the weighting factor I used in each trade).

**Comment by mementum** [comment]
I feel some extra elaboration is needed. Trades already provide:
  - barlen
  - pnl (gross profit and loss)
  - pnlcomm (net pnl i.e: including commission)

#42 has a commit fcb42e3 which includes:
  - opening datetime
  - closing datetime

As for:
  - name (is part of the data part in the trade in `trade.data._name`

Not in the trades:
  - price, size, orderid to open/close the position
    Can be done, because trade information comes from the orders used to create/update them.

  - Custom fields
    The problem here: a trade is an artifact defined as a position being != 0 and coming back to 0 (or crossing the boundary)

    You do not create the trade.

    Addition of custom fields to an order would be different, because the order is a "reality" (as much as it can be in the platform) created by you and managed by the broker.

    In that sense, what's probably needed is a copy of custom fields which may been added to the orders.

**Comment by tomcpli** [comment]
Does it make sense if trade can retrieve the orders (e.g. trades.orders) ?

**Comment by mementum** [comment]
It has to be taken into account that a single order could be listed in 2 different Trades, which is the case for a reversal order.
