### ISSUE TITLE
Question about self.getpositions()

### ISSUE THREAD

**Issue by tomcpli** [mementum/backtrader#41]
The self.getpositionbyname() returns class 'backtrader.position.Position'
But the self.getpositions() returns a collection of class 'backtrader.feeds.yahoo.YahooFinanceCSVData'

Should the self.getpositions() returns a collection of  class 'backtrader.position.Position' ? Thanks

    from __future__ import (absolute_import, division, print_function,
                            unicode_literals)
    
    import backtrader as bt
    import backtrader.feeds as btfeeds

    
    class TestStrategy(bt.Strategy):
        def __init__(self):
            self.i = 0
        
        def next(self):
            self.i += 1        
            if self.i == 1:
                self.buy('orcl', size=3)
                self.sell('nvda', size=10)
            elif self.i == 2:
                positions = self.getpositions()
                print(type(positions))
                
                for p in positions:
                    print(type(p))
                    
                print(type(self.getpositionbyname('orcl')))
    
    if __name__ == '__main__':
        cerebro = bt.Cerebro()
        cerebro.addstrategy(TestStrategy)
        
        datafile0 = r'./test-data/orcl-2014.txt'
        data0 = btfeeds.YahooFinanceCSVData(dataname=datafile0, 
                                            name='orcl')  
        cerebro.adddata(data0, name='orcl')
        
        datafile1 = r'./test-data/nvda-2014.txt'
        data1 = btfeeds.YahooFinanceCSVData(dataname=datafile1, name='nvda') 
        cerebro.adddata(data1, name='nvda')
            
        thestrats = cerebro.run()    

    OUTPUT:
    <type 'collections.defaultdict'>
    <class 'backtrader.feeds.yahoo.YahooFinanceCSVData'>
    <class 'backtrader.feeds.yahoo.YahooFinanceCSVData'>
    <class 'backtrader.position.Position'>

**Comment by mementum** [comment]
It returns the positions by data ordered as inserted in the system (using a `collections.OrderedDict`). Because you are iterating over the dictionary, you get the keys (the datas).

The rationale behind is that you can iterate over the "items" and do something with the information given to you by the position understanting to which data the position is referring.

``` python
    def getpositions(self, broker=None):
        '''
        Returns the current by data positions directly from the broker

        If the given ``broker`` is None, the default broker will be used

        A property ``positions`` is also available
        '''
```

The same applies to `getpositionsbyname` in which you also get a `collections.OrderedDict`, but this time having the names as keys in the dictionary.

**Comment by tomcpli** [comment]
Cool. Thanks.
