### ISSUE TITLE
Template strategy with a set of entry/exit rules

### ISSUE THREAD

**Issue by zhanjing** [mementum/backtrader#44]
With the current code structure of the "Strategy" class, I wonder whether it is easy to develop a strategy template and work with a set of entry/exit rules. Specifically, let's say I want to test a trend-following strategy, and I have written a set of different entry/exit rules for trend-following, for example, let's say the following three 
(a) SMA(5) > SMA(25) for long, SMA(5) < SMA(25) for short
(b) RSI cross 30 for long, RSI cross 70 for short
(c)  Close(0) > Close(7) for long, Close(0) < Close(7) for short

Ideally I don't have to code up three respective strategies with the above three rules. I could just code up one master strategy and specify the entry/exit rule to be used.  

I just wonder how much efforts it will take to add this to the current backtrader framework. Thank you.

**Comment by mementum** [comment]
This is in the backlog of things to implement. The introduction of such rules has to be coupled with what in the platform is named as "sizer", which is an object in the strategy capable of automatically sizing the operation. The only available sizer is a fixed stake sizer.

**Comment by zhanjing** [comment]
Thank you for the reply. Sound like this feature needs some efforts. When are you planning to do it? Thanks again.

**Comment by mementum** [comment]
Not in the very short term as I am looking rather at the integration of a live data feed as the major task (probably followed by the integration of the broker which provides that data feed)

**Comment by zhanjing** [comment]
Sounds very interesting. Does this mean the backtrader will be able to do paper trading (or even better, real trading) with live market data feed?

**Comment by mementum** [comment]
Yes. Initially paper trading and then live trading.

**Comment by zhanjing** [comment]
Actually now I am very much looking forward to the integration of a live data feed and the broker. Do you have a rough idea when they could be available?

**Comment by mementum** [comment]
Christmas is coming around and with it some time to "think" on a good integration model.

It will be there but cannot commit to a deadline of 1 or 2 weeks

**Comment by junajo10** [comment]
Hi,

https://github.com/mdeverdelhan/ta4j Can help you to integrate entry/exit rules.

**Comment by mementum** [comment]
Hi,

I had been thinking about this topic and also had a look at the link provided. The ideas I had were not that far away from those implemented there, but I always end up in the same corner:

  - Deciding/Specifiying if a rule is meant for entering `long`, `short` or valid for both 

Imagine a custom indicator is used as an entry rule:

```python

class SMACloseRule(bt.Indicator):
    lines = ('smaclose',)
    params = (('period', 15),)

    def __init__(self):
        sma = btind.SMA(self.data, period=self.p.period)
        self.lines.smaclose = self.data - self.sma
```

This will deliver 3 *ranges* of values, *positive*, *zero*, *negative*. And one could argue that *positive* means to enter `long` and `negative` means to exit the `long`.

But on exiting the `long` a `short` could also be opened. Not usual for *stocks* but common for *futures*. And that's where one of the keys for the definition of the *API* is.

In any case I will keep on pondering about this.

**Comment by mementum** [comment]
zhanjing commented above about the wish for "live trading". At the moment I have a working live data feed class for Interactive Brokers. Look into Issue #69. There is the class and a working script.

**Comment by zhanjing** [comment]
very interesting! will take a look at the example. Thank you.

**Comment by mementum** [comment]
Release 1.5.0.92 has been released with Live Data Feed and Live Trading.

Handle with extreme care

**Comment by junajo10** [comment]
Hi,

I have reviewed the new release, i am trying to use with this example, but i don´t know if it is posible to create 4 rules, i usually work with signals for buying and selling together.

entryLong  = "And(indicator.CrossDown(Close, s1),stochk > constantValue)"
exitLong  = "CrossUp(Low, p)"
entryShort  = "And(indicator.CrossUp(Low, r1),stochk < (100-constantValue))"
exitShort  = "CrossDown(Open, p)"
#exit=p,s1,s2,r1,r2->pivot point
constantValue=10


Rgds,
JJ

**Comment by mementum** [comment]
That's the theory behind the *signals* approach:

  - The `entryLong` is the only of the four that signals to go long. The code to go long:

    ```
    if size == 0:
        if ls_long or l_enter:
            self.buy()  
    ```

    In this case there is no `LONGSHORT` and `ls_short` is `False`

    `l_enter` depends entirely on the `LONG` *signal`, which in this case is `entryLong`

  - To close/reverse a *long*, the logic is:

    ```
    elif size > 0:  # current long position
        if ls_short or l_exit or l_rev or l_leave:
            self.close()

        if ls_short or l_rev:
            self.sell()
    ```

    Again `ls_short` is `False` due to the absence of a `LONGSHORT` signal

    `l_exit` depends on `exitLong`

    And `l_leave` is `False` because you have added an exit *signal*  for long. After calculating `l_leave` it goes a last round like this:

    ```
    l_leave = not self._longexit and l_leave
    ```

   It can only be ``True`` if you have not added an *exit signal* for long.

The same logic applies (but obviously reversed) to the *short* side of the equation.
