### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Cerebro'

### ISSUE THREAD

**Issue by miguelfg** [mementum/backtrader#5]
Hi,

First basic example doesn't work to me, it seems an import issue, that i'm not sure why it doesn't find submodules... (http://backtrader.readthedocs.org/en/latest/quickstart.html#basic-setup)

Error is: 
Traceback (most recent call last):
  File "/home/miguelfg/workspace/projects/python/data-playground/data_playground/backtrader.py", line 29, in <module>
    main(None)
  File "/home/miguelfg/workspace/projects/python/data-playground/data_playground/backtrader.py", line 21, in main
    cerebro = bt.Cerebro()
AttributeError: 'module' object has no attribute 'Cerebro'

By just doing:
...
    
    import backtrader as bt
    
    def main(argv):
        if argv is None:
            argv = sys.argv
        cerebro = bt.Cerebro()
    
        print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())
        cerebro.run()
        print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
    
    
    if __name__ == "__main__":
        main(None)

**Comment by mementum** [comment]
How have you installed it?

Which version you have? try printin out "backtrader.__version__"

**Comment by miguelfg** [comment]
In a virtualenv =>
(data-playground)miguelfg@portatil-biz:~/workspace/projects/python$ pip freeze | grep trader
backtrader==1.1.0.88

Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import backtrader
>>> backtrader.__version__
u'1.1.0.88'

I use Pycharme as IDE, but it's not an IDE config thing, just simply running the my script from the console as: > python backtrader.py 
Traceback (most recent call last):
  File "backtrader.py", line 29, in <module>
    main(None)
  File "backtrader.py", line 21, in main
    cerebro = bt.Cerebro()
AttributeError: 'module' object has no attribute 'Cerebro'


:-(

**Comment by mementum** [comment]
It may be a long shot ... but what if you change the name of your script from "backtrader" to something else?

Moreover the test your performed for \_\_version\_\_ is invalid because you didn't do it from inside the script and the import is not even the same as the one inside the script.

**Comment by miguelfg** [comment]
Shit, i feel so stupid, xD. Your shot wasn't long at all, now it works ;-) 
Thanks, first time falling in this, but i'll remember!, hehe
