### ISSUE TITLE
BtFeeds.YahooFinanceData() error

### ISSUE THREAD

**Issue by syntaxc** [mementum/backtrader#55]
I am receiving an error when attempting to download feed data directly from Yahoo.

```
In [1]: import backtrader as bt

In [2]: import backtrader.feeds as btfeeds

In [3]: cerebo = bt.Cerebro()

In [4]: cerebo.broker.setcash(100000)

In [5]: data = btfeeds.YahooFinanceData(dataname='AAPL', name='AAPL')

In [6]: cerebo.adddata(data)

In [7]: cerebo.run()
Traceback (most recent call last):

  File "<ipython-input-7-08709df9b726>", line 1, in <module>
    cerebo.run()

  File "/usr/local/lib/python2.7/dist-packages/backtrader/cerebro.py", line 385, in run
    runstrat = self.runstrategies(iterstrat)

  File "/usr/local/lib/python2.7/dist-packages/backtrader/cerebro.py", line 454, in runstrategies
    data.start()

  File "/usr/local/lib/python2.7/dist-packages/backtrader/feeds/yahoo.py", line 155, in start
    url += 's=%s' % self.params.ticker

AttributeError: 'AutoInfoClass_LineRoot_LineMultiple_LineSeries_Dat' object has no attribute 'ticker'
```

Is this the correct way to downloading price data directly from Yahoo?

Excuse me if I missed it, but of all the documentation I went through, every example loaded data from a csv.

**Comment by mementum** [comment]
This is a blatant bug caused by making the online downloader feed a subclass of the Yahoo Data CSV reader. ``ticker`` was the original name of the downloader, but it must be ``dataname`` now following the convention of all other data feeds.

Long time no test because I always rely on csv sources.

Making a release to correct it.

**Comment by mementum** [comment]
Added also a sample in the samples directory ``yahoo-test`` which allows to download, plot, csv-print the data directly from yahoo
