### ISSUE TITLE
question: about the indicator parameters

### ISSUE THREAD

**Issue by hackerwei** [mementum/backtrader#56]
In the adding an indicator  part of the QuickStart doc, there are codes:
        # Add a MovingAverageSimple indicator
        self.sma = bt.indicators.SimpleMovingAverage(
            self.datas[0], period=self.params.maperiod)
it calls which class's __init__ func? If it's the __init__() in the LineSeries, it seems that super(LineSeries, self).__init() has no parameters send in. What's the logic of this part?

**Comment by mementum** [comment]
Sorry, but I may be failing to understand the question. In OOP it's customary to call the base class overriden method.

``SMA`` is an alias for ``MovingAverageSimple`` and its ``__init__`` method is being called, which in turns uses ``super`` (to enable cooperative inheritance if needed be) to call its base class ``__init__`` method.

```python
class MovingAverageSimple(MovingAverageBase):
    '''
    Non-weighted average of the last n periods

    Formula:
      - movav = Sum(data, period) / period

    See also:
      - http://en.wikipedia.org/wiki/Moving_average#Simple_moving_average
    '''
    alias = ('SMA', 'SimpleMovingAverage',)
    lines = ('sma',)

    def __init__(self):
        # Before super to ensure mixins (right-hand side in subclassing)
        # can see the assignment operation and operate on the line
        self.lines[0] = Average(self.data, period=self.p.period)

        super(MovingAverageSimple, self).__init__()
```

**Comment by hackerwei** [comment]
but the (self.datas[0], period=self.params.maperiod) is not send in for the base class? since the base is __init__(), no input params?

**Comment by hackerwei** [comment]
I mean that we call bt.indicators.SimpleMovingAverage() with two params as input, but the init() func of of  the class SimpleMovingAverage seems needs no input params:
    
def __init__(self):
        # Before super to ensure mixins (right-hand side in subclassing)
        # can see the assignment operation and operate on the line
        self.lines[0] = Average(self.data, period=self.p.period)

        super(MovingAverageSimple, self).__init__()

**Comment by mementum** [comment]
That's the point of the platform. The metaclass machinery removes the arguments before they hit the ``__init__`` method and processes them properly by assigning them as datas or as parameters, so it can later be used in the code with no need to care about what's being passed around.

**Comment by hackerwei** [comment]
I traced  up to  the init() func of LineSeries, and got lost... anyway, thx for kindly reply.

**Comment by mementum** [comment]
By the time the ``__init__`` methods get called, the ``args`` and ``kwargs`` have been processed.

For ``LineIterator`` classes (like ``Indicator`` derived classes) which take ``datas`` as input this happens when creating the object

```python
class MetaLineIterator(LineSeries.__class__):
    def donew(cls, *args, **kwargs):
        _obj, args, kwargs = \
            super(MetaLineIterator, cls).donew(*args, **kwargs)

        # Scan args for datas ... if none are found,
        # use the _owner (to have a clock)
        _obj.datas = \
            [LineSeriesMaker(x) for x in args if isinstance(x, LineRoot)]
   ...
```

``donew`` is invoked by the metaclass machinery when creating the instance.

The ``kwargs`` are actually processed in different parts of the platform. This is because many of the classes are subclasses of MetaParams, but some of the params are parsed later for plotting purposes. The concept is the same. For example for regular params defined with the ``params`` idiom

```python
class MetaParams(MetaBase):
...

    def donew(cls, *args, **kwargs):
        # Create params and set the values from the kwargs
        params = cls.params()
        for pname, pdef in cls.params._getitems():
            setattr(params, pname, kwargs.pop(pname, pdef))
```

But the concept is the same and by the time ``__init__` is called no ``datas`` or ``kwargs`` which match defined ``params`` are left for the instance to consume.

**Comment by hackerwei** [comment]
very clear now! Thx very much!!!
