### ISSUE TITLE
Support for high-frequency data

### ISSUE THREAD

**Issue by fccoelho** [mementum/backtrader#60]
It seems that Backtrader supports only OHLC type of series. I Am trading in bitcoins and I would like to work on continuous price series. Bitcoin nevers stops, it trades 24/7. So far, I am faking OHLC, but it would be nice to have support to raw list of prices and volumes as well as ASKs and BIDs...

Any plans to support this?

**Comment by mementum** [comment]
Hi,

`backtrader` has built-in support for `OHLC` but can accept any type of data you accept. In Issue #9 a very similar question was asked. The user wanted to extend the feed with `P/E` values.

There is a complete post about how to extend the data feed:

  - http://www.backtrader.com/posts/2015-08-07/extending-a-datafeed/

If you have an example which is somehow standard-like I have no problem in making it a standard part of `backtrader`.

**Comment by fccoelho** [comment]
Great, I'll take a look at the example.

**Comment by mementum** [comment]
Release 1.2.1.88 contains support to allow end-users to override the entire line hierarchy and remove OHLC, without having to resort to extending the hierarchy from the mid of the chain.

Have a look at the new sample in the sources *data-bid-ask*. I will also be adding a new blog post about it. By using `linesoverride=True` and defining the lines (in the sample `bid`, `ask` and `datetime`) the file is loaded and the sample shows that the lines are accessible.

Of course, the standard indicators like "Stochastic" are expecting data feeds with `close`, `high` and `low` prices and are therefore not directly applicable to such a feed.

Other indicators like Moving Averages can be directly applied.

**Comment by mementum** [comment]
The longer post: http://www.backtrader.com/posts/2016-03-08-escape-from-ohlc-land/escape-from-ohlc-land/

**Comment by fccoelho** [comment]
Thanks!

On Mon, Mar 7, 2016 at 8:07 PM, DRo <notifications@github.com> wrote:

> Release 1.2.1.88 contains support to allow end-users to override the
> entire line hierarchy and remove OHLC, without having to resort to
> extending the hierarchy from the mid of the chain.
>
> Have a look at the new sample in the sources *data-bid-ask*. I will also
> be adding a new blog post about it. By using linesoverride=True and
> defining the lines (in the sample bid, ask and datetime) the file is
> loaded and the sample shows that the lines are accessible.
>
> Of course, the standard indicators like "Stochastic" are expecting data
> feeds with close, high and low prices and are therefore not directly
> applicable to such a feed.
>
> Other indicators like Moving Averages can be directly applied.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mementum/backtrader/issues/60#issuecomment-193496612>.
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil
