### ISSUE TITLE
MIssing bars on 5min - Question

### ISSUE THREAD

**Issue by parthasrinivasan** [mementum/backtrader#63]
Daniel,
The dataset I shared - has missing data bars - sometimes half the bars in a 1 hr period are missing due to sparse trading in certain time periods.
I presume - that neither pandas nor the backtrader line handler - fills in any data.
Could you confirm that this is the case ?
What would you recommend as the fill method ?  Use DataFiller ?
I looked in the docs - can I find a usage example for DataFiller somewhere ?
I used the code below - and when I add it to cerebro - cerebro never returns - it keeps running.
Whereas if I add datai - (the unfilled data) - it runs cleanly
```python
        datai  = bt.feeds.PandasData(dataname=df, timeframe=bt.TimeFrame.Minutes)
        data1 = bt.feeds.PandasData(dataname=df1, timeframe=bt.TimeFrame.Days)
        data    = bt.filters.DataFiller(dataname=datai, fill_vol=1, fill_oi=1, 
                    sessionstart=datetime.time(4,0,0), sessionend = datetime.time(13,15,0) )
```
Thanks,

**Comment by mementum** [comment]
Hi,

In November `backtrader` received `filters` as a new functionality. Due to ticket #23 which also had missing bars with intraday data and this prevented synchronizing the same minute across days to compare the volume on a minute basis over days.

There is a post documenting a `SessionFilter` and a `SessionFiller` here: http://www.backtrader.com/posts/2015-11-21-data-filters/data-filling-filtering/

But it's not a panacea. Filling in missing data is a decision about *what to fill in*. And the answer depends on your specific scenario. This is something I haven't faced myself: my trading markets are so liquid that even during the quietest hours some trading takes place.

> In looking at this issue I found an issue with `SessionFiller` (the bar under evaluation could be moved too early into the stack) and have issued version 1.2.2.88 to correct it.

The sample from ticket #61 extended with a `SessionFiller`:

```python
from __future__ import (absolute_import, division, print_function,)
#                        unicode_literals)

import datetime

import backtrader as bt
import backtrader.feeds as btfeeds
import backtrader.filters as btfilters


class St(bt.Strategy):
    def next(self):
        dt00 = self.data0.datetime.datetime().isoformat()
        dt10 = self.data1.datetime.datetime().isoformat()
        print('%d: Intraday: %s - Day %s' % (len(self), dt00, dt10))


if __name__ == '__main__':
    cerebro = bt.Cerebro()

    cerebro.addstrategy(St)

    data0 = btfeeds.GenericCSVData(
        dataname='dump-5min.csv',
        timeframe=bt.TimeFrame.Minutes,
        compression=5,
        sessionstart=datetime.datetime(1, 1, 1, 0, 0),  # only time is used
        sessionend=datetime.datetime(1, 1, 1, 23, 59),  # only time is used
    )
    data0.addfilter(btfilters.SessionFiller, fill_vol=0.0, fill_oi=0.0)

    data1 = btfeeds.GenericCSVData(dataname='dump-1day.csv',
                                   timeframe=bt.TimeFrame.Days)   

    cerebro.adddata(data0)
    cerebro.adddata(data1)

    cerebro.run()
```

If we look at the initial minutes of your data on 2015-01-02:

```
2015-01-02 00:10:00,-0.006,-0.005,-0.006,-0.005,871,17
2015-01-02 00:15:00,-0.005,-0.004,-0.006,-0.004,888,17
2015-01-02 00:20:00,-0.004,-0.004,-0.005,-0.004,897,9
2015-01-02 00:25:00,-0.005,-0.003,-0.005,-0.003,922,25
2015-01-02 00:30:00,-0.003,-0.003,-0.005,-0.004,947,25
2015-01-02 00:35:00,-0.004,-0.003,-0.004,-0.003,952,5
2015-01-02 00:40:00,-0.003,-0.003,-0.004,-0.003,968,16
2015-01-02 00:45:00,-0.003,-0.003,-0.004,-0.003,998,30
2015-01-02 00:50:00,-0.003,-0.003,-0.004,-0.004,1000,2
2015-01-02 00:55:00,-0.004,-0.003,-0.004,-0.004,1011,11
2015-01-02 01:00:00,-0.004,-0.003,-0.004,-0.003,1015,4
2015-01-02 01:05:00,-0.002,-0.001,-0.002,-0.001,1050,35
2015-01-02 01:10:00,-0.001,-0.001,-0.003,-0.003,1078,28
2015-01-02 01:15:00,-0.003,-0.002,-0.003,-0.002,1087,9
2015-01-02 01:25:00,-0.003,-0.003,-0.003,-0.003,1094,7
2015-01-02 01:30:00,-0.003,-0.003,-0.004,-0.004,1096,2
2015-01-02 01:35:00,-0.003,-0.003,-0.003,-0.003,1097,1
2015-01-02 01:40:00,-0.003,-0.003,-0.003,-0.003,1113,16
2015-01-02 01:45:00,-0.002,-0.002,-0.002,-0.002,1114,1
2015-01-02 01:50:00,-0.001,-0.001,-0.003,-0.003,1116,2
2015-01-02 01:55:00,-0.001,-0.001,-0.003,-0.003,1121,5
2015-01-02 02:00:00,-0.001,-0.001,-0.001,-0.001,1122,1
2015-01-02 02:15:00,-0.003,-0.003,-0.003,-0.003,1124,2
2015-01-02 02:20:00,-0.003,-0.001,-0.003,-0.002,1146,22
2015-01-02 02:25:00,-0.003,-0.002,-0.003,-0.002,1167,21
2015-01-02 02:35:00,-0.003,-0.002,-0.003,-0.003,1176,9
```

There are missing bars (at least with my no longer sharp eyes, the following)

  - 00:00, 00:05, 01:20, 02:05, 02:10, 02:30

Running the script and looking at the same period the output is as follows

```
108: Intraday: 2015-01-02T00:00:00 - Day 2015-01-02T00:00:00
109: Intraday: 2015-01-02T00:05:00 - Day 2015-01-02T00:00:00
110: Intraday: 2015-01-02T00:10:00 - Day 2015-01-02T00:00:00
111: Intraday: 2015-01-02T00:15:00 - Day 2015-01-02T00:00:00
112: Intraday: 2015-01-02T00:20:00 - Day 2015-01-02T00:00:00
113: Intraday: 2015-01-02T00:25:00 - Day 2015-01-02T00:00:00
114: Intraday: 2015-01-02T00:30:00 - Day 2015-01-02T00:00:00
115: Intraday: 2015-01-02T00:35:00 - Day 2015-01-02T00:00:00
116: Intraday: 2015-01-02T00:40:00 - Day 2015-01-02T00:00:00
117: Intraday: 2015-01-02T00:45:00 - Day 2015-01-02T00:00:00
118: Intraday: 2015-01-02T00:50:00 - Day 2015-01-02T00:00:00
119: Intraday: 2015-01-02T00:55:00 - Day 2015-01-02T00:00:00
120: Intraday: 2015-01-02T01:00:00 - Day 2015-01-02T00:00:00
121: Intraday: 2015-01-02T01:05:00 - Day 2015-01-02T00:00:00
122: Intraday: 2015-01-02T01:10:00 - Day 2015-01-02T00:00:00
123: Intraday: 2015-01-02T01:15:00 - Day 2015-01-02T00:00:00
124: Intraday: 2015-01-02T01:20:00 - Day 2015-01-02T00:00:00
125: Intraday: 2015-01-02T01:25:00 - Day 2015-01-02T00:00:00
126: Intraday: 2015-01-02T01:30:00 - Day 2015-01-02T00:00:00
127: Intraday: 2015-01-02T01:35:00 - Day 2015-01-02T00:00:00
128: Intraday: 2015-01-02T01:40:00 - Day 2015-01-02T00:00:00
129: Intraday: 2015-01-02T01:45:00 - Day 2015-01-02T00:00:00
130: Intraday: 2015-01-02T01:50:00 - Day 2015-01-02T00:00:00
131: Intraday: 2015-01-02T01:55:00 - Day 2015-01-02T00:00:00
132: Intraday: 2015-01-02T02:00:00 - Day 2015-01-02T00:00:00
133: Intraday: 2015-01-02T02:05:00 - Day 2015-01-02T00:00:00
134: Intraday: 2015-01-02T02:10:00 - Day 2015-01-02T00:00:00
135: Intraday: 2015-01-02T02:15:00 - Day 2015-01-02T00:00:00
136: Intraday: 2015-01-02T02:20:00 - Day 2015-01-02T00:00:00
137: Intraday: 2015-01-02T02:25:00 - Day 2015-01-02T00:00:00
138: Intraday: 2015-01-02T02:30:00 - Day 2015-01-02T00:00:00
139: Intraday: 2015-01-02T02:35:00 - Day 2015-01-02T00:00:00
```

**Now the missing bars are there**

Note: As you may have noticed I dumped your dataset to *csv* files to make my life easier.

**Comment by parthasrinivasan** [comment]
Thanks.  You are right - knowing what to fill in is very market/application dependent.
I do know what I want filled in - I just want to use the last real valid bar - replicated till the next valid bar - OHLC and all.
I will look at the examples and maybe derive something from your filler and try to overload it to get what I want.

**Comment by mementum** [comment]
This should do the trick:

```python
class MySessionFiller(btfilters.SessionFiller):
    def _fillbar(self, data, dtime):
        # Copy the previous bar
        bar = [data.lines[i][-1] for i in range(data.size())]
        bar[data.DateTime] = date2num(dtime)  # Fill datetime
        return True
```

By specfiying `-1` you get the value of the line corresponding to the last delvered bar

**Comment by parthasrinivasan** [comment]
Wow - thanks for the speedy response ... I will try this later today after pulling your latest release and will update you.
Again Thanks.!

**Comment by parthasrinivasan** [comment]
# Add to the stack of bars to save
        data._add2stack(bar)     
need to be added to the MySessionFiller to be complete:
class MySessionFiller(btfilters.SessionFiller):
    def _fillbar(self, data, dtime):
        # Copy the previous bar
        bar = [data.lines[i][-1] for i in range(data.size())]
        bar[data.DateTime] = date2num(dtime)  # Fill datetime
        # Add to the stack of bars to save
        data._add2stack(bar)     
        return True

**Comment by mementum** [comment]
Indeed (the reason I said *should*, because it was quickly typed)

Happy to know you have it working.

**Comment by parthasrinivasan** [comment]
This part which was my test mule is working - but my main program that uses DataResampler (now deprecated) and changed to resampledata - just crashes (Issue #65)- on existing dataset that worked.
Once I have that sorted out - I can add this part to ti.

**Comment by mementum** [comment]
I guess you mean #64. Let me know in that issue if the `data.clone` method solves your problem
