### ISSUE TITLE
Extending the PandasDataFeed

### ISSUE THREAD

**Issue by ericbrown** [mementum/backtrader#65]
I just found backtrader. Nice work.

I do all my work in pandas and was happy to see that you have a pandas datafeed. I"m trying to follow the examples given for extending datafeeds but I am running into an issue.

Example with CSV: http://backtrader.readthedocs.org/en/latest/extending-a-datafeed.html

My code following the example:

```python
class AddDataFieldsPandas(PandasData):

	lines = ('optix_close','optix_pess', 'optix_opt',)
	params = (
		('optix_close', -1),
		('optix_pess', -1),
		('optix_opt', -1),
	)

	linefields = PandasData.datafields + ['optix_close', 'optix_pess', 'optix_opt']

```
I've tried a few permutations of this, including:

```python
class AddDataFieldsPandas(PandasData):

	lines = ('optix_close','optix_pess', 'optix_opt',)
	params = (
		('optix_close', -1),
		('optix_pess', -1),
		('optix_opt', -1),
	)

	datafields = PandasData.datafields + ['optix_close', 'optix_pess', 'optix_opt']

```
and

```python
class AddDataFieldsPandas(PandasData):

	lines = ('optix_close','optix_pess', 'optix_opt',)
	params = (
		('optix_close', -1),
		('optix_pess', -1),
		('optix_opt', -1),
	)

	PandasData.datafields = PandasData.datafields + ['optix_close', 'optix_pess', 'optix_opt']

```

None of these add the extra params. When i run my strat, I get the following error:

> AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_Abst' object has no attribute 'optix_close'

If I run your sample [MyTest strat](http://backtrader.readthedocs.org/en/latest/automated-bt-run/automated-bt-run.html#applying-a-user-defined-strategy) and try to add one of the extra params to the log i get the same error, so its not my strat causing the issue...I'm just not getting the extra params/lines into the pandas data definition.

**Comment by mementum** [comment]
Hi Eric,

Your 2nd *permutation* must/should work. This is what I did right now in the `data-pandas/data-pandas.py` sample (present in the sources)

```python
class PandasDataOptix(btfeeds.PandasData):

    lines = ('optix_close', 'optix_pess', 'optix_opt',)
    params = (('optix_close', -1),
              ('optix_pess', -1),
              ('optix_opt', -1))

    datafields = btfeeds.PandasData.datafields + (
        ['optix_close', 'optix_pess', 'optix_opt'])
```

Added a small strategy which prints the `opt_` fields during each `next` invocation:

```python
class StrategyOptix(bt.Strategy):

    def next(self):
        print('%03d %f %f, %f' % (
            len(self),
            self.data.optix_close[0],
            self.data.lines.optix_pess[0],
            self.data.optix_opt[0],))

```

And I modified the `2006-day-001.txt` data sample to contain 3 additional fields:

```
Date,Open,High,Low,Close,Volume,OpenInterest,Optix_Close,Optix_Pess,Optix_Opt
2006-01-02,3578.73,3605.95,3578.73,3604.33,0,0,1.1,2.2,3.3
2006-01-03,3604.08,3638.42,3601.84,3614.34,0,0,1.1,2.2,3.3
2006-01-04,3615.23,3652.46,3615.23,3652.46,0,0,1.1,2.2,3.3
...
...
2006-12-27,4079.70,4134.86,4079.70,4134.86,0,0,1.1,2.2,3.3
2006-12-28,4137.44,4142.06,4125.14,4130.66,0,0,1.1,2.2,3.3
2006-12-29,4130.12,4142.01,4119.94,4119.94,0,0,1.1,2.2,3.3
```

Running the script modified to (also avoid plotting) and using the above datafeed, strategy and dataset, the output is as follows:

```
001 1.100000 2.200000, 3.300000
002 1.100000 2.200000, 3.300000
003 1.100000 2.200000, 3.300000
004 1.100000 2.200000, 3.300000
005 1.100000 2.200000, 3.300000
...
...
251 1.100000 2.200000, 3.300000
252 1.100000 2.200000, 3.300000
253 1.100000 2.200000, 3.300000
254 1.100000 2.200000, 3.300000
255 1.100000 2.200000, 3.300000
```

The entire test script for your reference. Let me know if we can further dig into what's causing your issue

```python
#!/usr/bin/env python
# -*- coding: utf-8; py-indent-offset:4 -*-

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import argparse

import backtrader as bt
import backtrader.feeds as btfeeds

import pandas


class PandasDataOptix(btfeeds.PandasData):

    lines = ('optix_close', 'optix_pess', 'optix_opt',)
    params = (('optix_close', -1),
              ('optix_pess', -1),
              ('optix_opt', -1))

    datafields = btfeeds.PandasData.datafields + (
        ['optix_close', 'optix_pess', 'optix_opt'])


class StrategyOptix(bt.Strategy):

    def next(self):
        print('%03d %f %f, %f' % (
            len(self),
            self.data.optix_close[0],
            self.data.lines.optix_pess[0],
            self.data.optix_opt[0],))


def runstrat():
    args = parse_args()

    # Create a cerebro entity
    cerebro = bt.Cerebro(stdstats=False)

    # Add a strategy
    cerebro.addstrategy(StrategyOptix)

    # Get a pandas dataframe
    datapath = ('../../datas/2006-day-001-optix.txt')

    # Simulate the header row isn't there if noheaders requested
    skiprows = 1 if args.noheaders else 0
    header = None if args.noheaders else 0

    dataframe = pandas.read_csv(datapath,
                                skiprows=skiprows,
                                header=header,
                                parse_dates=True,
                                index_col=0)

    if not args.noprint:
        print('--------------------------------------------------')
        print(dataframe)
        print('--------------------------------------------------')

    # Pass it to the backtrader datafeed and add it to the cerebro
    data = PandasDataOptix(dataname=dataframe)

    cerebro.adddata(data)

    # Run over everything
    cerebro.run()

    # Plot the result
    if not args.noplot:
        cerebro.plot(style='bar')


def parse_args():
    parser = argparse.ArgumentParser(
        description='Pandas test script')

    parser.add_argument('--noheaders', action='store_true', default=False,
                        required=False,
                        help='Do not use header rows')

    parser.add_argument('--noprint', action='store_true', default=False,
                        help='Print the dataframe')

    parser.add_argument('--noplot', action='store_true', default=False,
                        help='Do not plot the chart')

    return parser.parse_args()


if __name__ == '__main__':
    runstrat()
```

**Comment by ericbrown** [comment]
Thanks. I'm still seeing the same error here with your code.  Copy/Pasted it and am seeing the same issue. I should note that I"m not running this through args, but that shouldn't matter.
 
Full traceback shows it is throwing an error when I try access 'self.data.optix_close[0],'

> Traceback (most recent call last):
  File "Backtrader_sample.py", line 97, in <module>
    thestrats = cerebro.run()
  File "/Users/eric/Dropbox/WebDev/MarketStrategyFramework/env/lib/python2.7/site-packages/backtrader/cerebro.py", line 360, in run
    runstrat = self.runstrategies(iterstrat)
  File "/Users/eric/Dropbox/WebDev/MarketStrategyFramework/env/lib/python2.7/site-packages/backtrader/cerebro.py", line 437, in runstrategies
    self._runonce(runstrats)
  File "/Users/eric/Dropbox/WebDev/MarketStrategyFramework/env/lib/python2.7/site-packages/backtrader/cerebro.py", line 535, in _runonce
    strat._oncepost()
  File "/Users/eric/Dropbox/WebDev/MarketStrategyFramework/env/lib/python2.7/site-packages/backtrader/strategy.py", line 211, in _oncepost
    self.nextstart()  # only called for the 1st value
  File "/Users/eric/Dropbox/WebDev/MarketStrategyFramework/env/lib/python2.7/site-packages/backtrader/lineiterator.py", line 298, in nextstart
    self.next()
  File "Backtrader_sample.py", line 19, in next
    self.data.optix_close[0],
  File "/Users/eric/Dropbox/WebDev/MarketStrategyFramework/env/lib/python2.7/site-packages/backtrader/lineseries.py", line 424, in __getattr__
    return getattr(self.lines, name)
AttributeError: 'Lines_LineSeries_DataSeries_OHLC_OHLCDateTime_Abst' object has no attribute 'optix_close'

My code:

```python

import backtrader as bt
import backtrader.indicators as btind
import backtrader.analyzers as btanalyzers
import backtrader.feeds as btfeeds
from backtrader.feeds import PandasData

import backtrader.strategies as btstrats
from data_scripts import get_model_data, get_price_data, get_meta, get_optix_data
symbol = 'SPY'
optix_symbol='etf_spy'

class StrategyOptix(bt.Strategy):

    def next(self):
        print('%03d %f %f, %f' % (
            len(self),
            self.data.optix_close[0],
            self.data.lines.optix_pess[0],
            self.data.optix_opt[0],))



class AddDataFieldsPandas(PandasData):

	lines = ('optix_close', 'optix_pess', 'optix_opt',)
	params = (('optix_close', -1),
	          ('optix_pess', -1),
	          ('optix_opt', -1))

	datafields = btfeeds.PandasData.datafields + (['optix_close', 'optix_pess', 'optix_opt'])




if __name__ == '__main__':
	print "gettting data"
#this gets the data from a database...data is in following format
	df=setup_data()

	data = bt.feeds.PandasData(dataname=df)
	
	cerebro = bt.Cerebro()
	# Set our desired cash start
	cerebro.broker.setcash(100000.0)
	  # Add a strategy
	cerebro.addstrategy(StrategyOptix)

	# # Add the Data Feed to Cerebro

	cerebro.adddata(data)

	# # Run over everything
	thestrats = cerebro.run()

All the data points exist in the dataframe (attached csv for data example).

[sample.csv.zip](https://github.com/mementum/backtrader/files/171287/sample.csv.zip)

**Comment by mementum** [comment]
Your code has this

```python
data = bt.feeds.PandasData(dataname=df)
```

But should instead have this

```python
data = AddDataFieldsPandas(dataname=df)
```

The `lines` you add are getting added to your own derived class not to the parent class and that's the reason the code fails, because `PandasData` has no line named `optix_close`

**Comment by ericbrown** [comment]
That did it. I was assuming it was something silly like that.  Thanks!

**Comment by pysecuser** [comment]
Hi,

I am trying to pull data from database, when I tail() the dataframe, it shows me the output, however, trying to plot it throws below error:

AttributeErrorTraceback (most recent call last)
<ipython-input-59-eec14fbbcb79> in <module>()
     78 if __name__ == '__main__':
     79     sym_ticker = 'GOOG'
---> 80     runstrat(sym_ticker)

<ipython-input-59-eec14fbbcb79> in runstrat(sym_ticker)
     74 
     75     # Plot the result
---> 76     cerebro.plot(style='candle')
     77 
     78 if __name__ == '__main__':

../lib/python2.7/site-packages/backtrader/cerebro.pyc in plot(self, plotter, numfigs, iplot, useplotly, **kwargs)
    653                 figs.append(rfig)
    654 
--> 655             plotter.show()
    656         return figs
    657 

../lib/python2.7/site-packages/backtrader/plot/plot.pyc in show(self)
    641 
    642     def show(self):
--> 643         self.mpyplot.show()
    644 
    645     def sortdataindicators(self, strategy):

AttributeError: 'Plot_OldSync' object has no attribute 'mpyplot'



The program is as below:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

import backtrader as bt
import backtrader.feeds as btfeeds
import pandas as pd
import MySQLdb as mdb

def get_data():
    # Get variables for Database : db_name etc

    con = mdb.connect(db_host, db_user, db_pass, db_name)
    
    #Date, Open, High, Low, Close, Volume
sql = """SELECT Date,Open,High,Low,Close,Volume from eodprice_load ORDER BY Date ASC;"""
    
    dataframe = pd.read_sql_query(sql, con=con, index_col='price_date', parse_dates=True)
    return dataframe

def runstrat():

    # Create a cerebro entity
    cerebro = bt.Cerebro(stdstats=False)

    # Add a strategy
    cerebro.addstrategy(bt.Strategy)
    
    dataframe = get_data()

    # Pass it to the backtrader datafeed and add it to the cerebro
    data = PandasData(dataname=dataframe)
    cerebro.adddata(data)

    # Run over everything
    cerebro.run()
    
    # Plot the result
    cerebro.plot(style='candle')

if __name__ == '__main__':
    runstrat()
