### ISSUE TITLE
Portfolio backtest

### ISSUE THREAD

**Issue by JulienNic0las** [mementum/backtrader#67]
Hi,

First, I would like to say that you are making an incredible job with backtrader. Really. 

I'm playing with it for some days, and manage to reproduce most of the basic strategies I know. Now I'm wondering how to define a strategy for several assets at once, i.e. a portfolio. The strategy should be able to call a buy position of one or several assets, but share the same cash amount. Ideally, recurrent income could be added as well as automatic reallocation.

I've just started to think of a way to do that with the current version of backtrader, without any real success.

Do you have in mind such implementation for the future?

Ciao ciao

**Comment by mementum** [comment]
Hi,

I don't think if I fully understand what you want.

> define a strategy for several assets at once, i.e. a portfolio

The platform supports several datas at the same time, with different timeframes if needed. Obviously The datas need to be synchronized in time . There is even a full post about a multi-data strategy:

  - http://www.backtrader.com/posts/2015-09-03-multidata-strategy/multidata-strategy/

In the post the strategy buys/sells only for the 1st data in the system (with the default parameters: `ORCL`) but nothing prevents buying from any other of the datas or from all of them. The `Strategy.buy` method is defined as:

```python
    def buy(self, data=None,
            size=None, price=None, plimit=None,
            exectype=None, valid=None, tradeid=0, **kwargs):
```

If you provide a `data` it will operate on it. If `None` is provided (default) it operates on `self.data0` (the 1st data in the system)

> The strategy should be able to call a buy position of one or several assets, but share the same cash amount

The cash is already shared because there is a single `broker` in the system.

Adding/Removing `cash` to the broker at anytime is possible. For example within the strategy:

```python
self.broker.cash += 10000
```

> automatic reallocation.

Some extra elaboration is needed as to what `automatic reallocation` comprises.

**Comment by JulienNic0las** [comment]
Hi Daniel,

Thanks for the reply. I have to confess that I totally missed the possibility to add several data at once in a single Strategy. My bad. Now the title of this post should be changed, if possible.

I deeply studied the example you provided above for multi-data strategy (I missed also..), and tried to modify it to suit my need. I'm planning to test several widely spread trading strategies based on trend following (or so called momentum). 

I came up the code below (not polished, I'm a poor programmer, as my no-ability to format the code below can state):

    # Import the backtrader platform
    import backtrader as bt
    import backtrader.feeds as btfeeds
    import backtrader.indicators as btind
    
    
    # Create Ivy Portfolio Strategy 
    class IvyPortfolio(bt.Strategy):
        """
        This strategy operates on several datas. It aims at testing the 
        implementation of the popular Ivy Portfolio proposed by Mebane Faber.
        
        Strategy based on:
            - Buy if not in the market and the price is above the moving
              average
            - Sell if in the market and the price is below the moving average
            - Check portfolio only one time per month to avoid whipsaws
    
        """
        
        params = dict(
            # Simple Moving Average period
            period=200,
            # Define the trading frequency (monthly, weekly or daily)
            trading_freq='M',
            # List of symbols in the portfolio
            symbols=None,
            # Weights of each symbol in the portfolio
            weights=None,
            # If True print out operations
            printout=True
        )
    
        def log(self, txt, dt=None):
            if self.p.printout:
                dt = dt or self.data.datetime[0]
                dt = bt.num2date(dt)
                print('%s, %s' % (dt.isoformat(), txt))
    
        def notify_order(self, order):
            if order.status in [bt.Order.Submitted, bt.Order.Accepted]:
                return  # Await further notifications
    
            if order.status == order.Completed:
                if order.isbuy():
                    buytxt = 'BUY COMPLETE, %.2f' % order.executed.price
                    self.log(buytxt, order.executed.dt)
                else:
                    selltxt = 'SELL COMPLETE, %.2f' % order.executed.price
                    self.log(selltxt, order.executed.dt)
    
            elif order.status in [order.Expired, order.Canceled, order.Margin]:
                self.log('%s ,' % order.Status[order.status])
                pass  # Simply log
    
            # Allow new orders
            self.orderid = None
    
        def __init__(self):
            
            # Check parameters
            assert self.params.trading_freq in ('D', 'W', 'M')
            
            # To control operation entries
            self.orderid = None
            
            # Keep track of the last trading date (to manage different 
            # frequency trading - daily, weekly or monthly)
            self.last_trading_date = None
            
            # Define a signal (buy or sell) for each symbol based on a simple
            # moving average indicator
            self.signals = {}
            for symbol in self.params.symbols:
                data = self.getdatabyname(symbol)
                sma = btind.SMA(data, period=self.params.period)
                signal = btind.CrossOver(data.close, sma)
                self.signals[symbol] = signal
            
        def next(self):
            
            # if an order is active, no new orders are allowed
            if self.orderid:
                return  
    
            # Check if today is a trading day
            if self._is_trading_day():
                self.trade()
        
        def _is_trading_day(self):
            """Check if today is a trading day"""
            
            today = self.data.datetime.date(0)
            
            if not self.last_trading_date:
                self.last_trading_date = today
                return True 
                
            deltatime = today - self.last_trading_date
            
            # Daily trading
            if self.params.trading_freq == 'D':
                self.last_trading_date = today 
                return True
                
            # Weekly trading
            elif self.params.trading_freq == 'W' and deltatime.days / 7 > 1:
                self.last_trading_date = today
                return True
            
            # Monthly trading. TODO: improve this
            elif self.params.trading_freq == 'M' and deltatime.days / 30 > 1:
                self.last_trading_date = today
                return True
    
            return False
                   
        def trade(self):
            
            for symbol, signal in self.signals.iteritems():
                
                data = self.getdatabyname(symbol) 
                position = self.getpositionbyname(symbol)
                
                # If not already in the market and signal flashs green, BUY!
                if not position and signal > 0:
                    
                    # Get total available cash and portfolio value
                    cash = self.broker.getcash()
                    value = self.broker.getvalue()
                    
                    # Get weight of the asset in the portfolio
                    weight = self.params.weights[self.params.symbols.index(symbol)]
                    
                    # Determine how many shares to buy (constrains: cash,
                    # weight in portfolio)
                    shares = min(cash, weight * value) / data.close[0]
                    
                    # Create buy order
                    self.log('BUY CREATE. SYMBOL: %s. VALUE: %.2f. '
                        'SHARES: %.2f' % (symbol, data.close[0], shares))
                    self.buy(data=data, size=shares)
                    
                # If already in the market and signal flashs red, short
                # position (sell all)
                elif position and signal < 0:
                    
                    # Get number of shares currently hold
                    own_shares = position.size
                    
                    # Determine how many shares to sell 
                    shares = own_shares
                    
                    # Create sell order
                    self.log('SELL CREATE. SYMBOL: %s. VALUE: %.2f. '
                        'SHARES: %.2f' % (symbol, data.close[0], shares))
                    self.sell(data=data, size=shares)
            
        def stop(self):
            # Executed when the backtest is finished
            pass
    
    
    def backtest(symbols, strategy, fromdate, todate, initcash=1000,
                 commission=0.0, trading_freq='M', plot=True):
        """ """
        
        # Create a cerebro entity
        cerebro = bt.Cerebro()
    
        # Add a strategy
        cerebro.addstrategy(
            strategy,
            trading_freq=trading_freq,
            symbols=symbols,
            weights=[1/len(symbols) for s in symbols])
        
        # Add the Data Feed to Cerebro
        for symbol in symbols:
            
            # Get data
            data = btfeeds.YahooFinanceData(
                dataname=symbol,
                name=symbol,
                fromdate=fromdate,
                todate=todate)
            
            # Add to cerebro
            cerebro.adddata(data)
    
        # Set desired cash start
        cerebro.broker.setcash(initcash)
    
        # Set the commission
        cerebro.broker.setcommission(commission=commission)
    
        # Print out the starting conditions
        print('Starting Portfolio Value: %.2f' % cerebro.broker.getvalue())
    
        # Run over everything
        cerebro.run()
    
        # Print out the final result
        print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())
    
        if plot:
            # Plot the result
            cerebro.plot()
        
    
    if __name__ == '__main__':
        
        # Build a portfolio with Yahoo and Oracle tickers
        symbols = ['VTI', 'VEU', 'BND', 'VNQ', 'DBC']
        
        # Define the strategy for the backtest
        strategy = IvyPortfolio
        
        # Rune backtest
        backtest(
            symbols,
            strategy,
            fromdate=datetime.datetime(2008, 1, 1),
            todate=datetime.datetime(2015, 12, 31),
            initcash=100000.0,
            trading_freq='M')
 
When I plot the results, it seems that only the first ticker have markers showing buy/sell orders. I'm wondering now if I correctly use the `buy()` method. 

Thanks for your time.

Subsidiary questions:
1. I see that the buy and sell methods have a price argument in addition to the size. Does it mean that it is possible to buy or sell for a given amount of money? Due to the slippage, an issue can occur if we specify a certain amount of shares to buy corresponding to the totality of the cash amount and if the price slightly increase the next day.  
2. Reading the code I did not see any facility to tune the slippage. Is there a way to set this slippage to another fixed value (let's say two), or a random value?

Bye

J

**Comment by mementum** [comment]
I will have a look at the code a bit later today.

*Price* for `sell` and `buy`: This is the requested `price` for the operation. Of course the price does only make sense if you actually issue a `Limit` order, because `Market` and `Close` will use fixed prices (namely: the next opening price for `Market` and the next possible closing price for `Close`, this being meant for intraday trading)

For the amount of money there is a concept which I have not further developed (yet) in `backtrader` which is a `Sizer`. Every strategy contains a `sizer` instance which is a simple `FixedStake` sizer (with an amount of `1`)

The idea is to develop *Sizers* which can implement different money staking policies (Van K. Tharp has some interesting books on the matter)

*Slippage*: I didn't implement and not because I forgot it. It was a conscious decision. The attempt was to make the broker as realistic as possible and that's why the *limit* orders have different checks in place to try to get the best possible match.

In this area there are 2 potential additions:

  1. Slippage
  2. Using (or not) the price extremes of a bar for a match

It will make it.

**Comment by mementum** [comment]
Not forgotten you and your code. Indeed: the `buy/sell` markers were only displayed for the 1st data in the system.

As easy as putting `True` where a `False` actually is (it should have always been `True`)

The `Buy/Sell` observer, being an overlay and on the same scale, poses no problem when plotting it for all and along the datas. But the `Trades` observer is an entirely different beast: the markers move around the `0` scale (ideally all should be above `0`)

For the moment the `Buy/Sell` will have to do.
