### ISSUE TITLE
Backtesting the Forex y Futuros

### ISSUE THREAD

**Issue by mementum** [mementum/backtrader#70]
Question moved over from e-mail request:

> Estaría interesado en realizar backtesting en forex y futuros. ¿Sería posible poder realizarlo en su aplicación? ¿En que otras aplicaciones sería posible realizar backtesting con forex?, se por ejemplo que en Zipline por ahora no sería posible.
 
which translates to:

> I would be interested in backtesting Forex and Futures. Would it be possible to do it with your platform? With which other platform would it be possible to backtest Forex? For example, I already know it's not possible with `zipline` at the moment

**Comment by mementum** [comment]
`backtrader` makes no distinction between *Forex Pairs*, *Futures*, *Options*, *Stocks*, *ETF*s or other financial instruments.

The platforms accepts a price series as input and the *Strategy* operating on that prices can do whatever it wants, usually:

  - Just long operations (the usual behavior with stocks)
  - Or a mix of long/short operations (usual behaviour with futures and forex pairs)

The key for a (more or less) successful backtesting is the commissions scheme. Futures do usually feature:

  - Fixed price per contract and operation
  - Margin needed to initiated and maintain the operation
  - Multiplier

`backtrader` has some default *Commission Schemes* which can be directly used and if needed be extended. This was covered in a blog post available under:

  - http://www.backtrader.com/posts/2015-11-20-commission-schemes-subclassing/commission-schemes-subclassing/

With the right commission scheme any `broker` can be simulated.

The short answer to the question:

  - Yes: `backtrader` can be used to backtest futures and forex pairs.

What about other platforms:

  - The README.rst of the project (featured on the front github page) lists some platforms

     I had a brief look at `pyalgotrade` and `zipline` in 2014 but I didn't like the API and way things were handled and decided things could be done differently. This doesn't mean they are bad platforms, it simply means they are not my cup of tea and prefer to work differently.

    As such I cannot ascertain whether they are fit or not for testing instruments with long/short operations and the right commission schemes.

**Comment by juancarrepi** [comment]
Thank you for your rapid and very clear reply! I'm going to learn using Backtrader I think this is what I was looking for.

Regards
