### ISSUE TITLE
Custom indicators: write values in a file

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#73]
Hi,

I would like to test my custom inducators. Is there any way to write values in a file?
Example:
File indicator.txt
Indicator1;.....;indicatorN;timestamp
Value1;.....;valueN;tick1
Value1;....;valueN;tick2
.......

Rgds,
Jj

**Comment by mementum** [comment]
``backtrader`` has built-in ``writers`` which do the job.

See:

  - http://www.backtrader.com/posts/2015-09-14-write-it-down/write-it-down/

and

  - http://backtrader.readthedocs.org/en/latest/writer.html

and

  - http://backtrader.readthedocs.org/en/latest/cerebro.html

    The `writer` added by `cerebro` will always print to `stdout` (which you can always redirect to a file). So if you need more control, add the `writer` yourself.

**Comment by junajo10** [comment]
Thanks, it is enought to solve my case
