### ISSUE TITLE
Bid and Ask data: convert to OHLC and Plot

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#78]
Hello,

I have three questions about working with bid/Ask data.
  1. Can i convert bid, ask in OHLC using backtrader?
trades bid or ask
    ```
    01/03/16,23:43:11,EUR/JPY,D,130.520,,1000000, 
    01/03/16,23:43:27,EUR/JPY,D,,130.520,,1000000
    01/03/16,23:49:19,EUR/JPY,D,130.510,,1000000,
    ```

    I want to to convert OHLC 1 min 
      - Open = first line
      - Last= last line

  2. Can we resample bid/Ask data using number lines instead of a timeframe?, for example create OHLC bars each 100 ticks.

  3. How can we plot the example bidask.py?

Rgds,
JJ

**Comment by mementum** [comment]
You can resample the data, but some questions are open:

  - Is the `BID` price the one that serves as a tick (`last seen` price and not `last`in the sense of `close`)?
  - or is it `ASK`?
  - or the average (`MID`)?
  - or something else?

Volume?

**Comment by junajo10** [comment]
hi,

TimeStamp,cross,status ("D"= dealt) (only trades "DEALT"),bid, offer, vol bid, vol offer
01/03/16,23:43:11,EUR/JPY,D,130.520,,1000000, 
01/03/16,23:43:27,EUR/JPY,D,,130.520,,1000000
01/03/16,23:49:19,EUR/JPY,D,130.510,,1000000,

**Comment by mementum** [comment]
Preparing a sample for this found a bug (or potential for improvement) in the resampling code. Corrected. New version to be released in a few minutes along with the sample

**Comment by mementum** [comment]
http://www.backtrader.com/posts/2016-04-14-bidask-data-to-ohlc/bidask-data-to-ohlc/

This is a full post with regards to the sample
