### ISSUE TITLE
Manage order execution logics

### ISSUE THREAD

**Issue by xingjianpan** [mementum/backtrader#8]
Hi @mementum ,

Could you please elaborate on how to manage what orders get executed?It looks currently backtrader will buy at the open price of next bar.  However, in reality this is not always feasible, so is there a way to manage this?

For example.
1) If the price of next bar is more than 10% higher or lower than current price, the order become expired.

2) If the date of next bar is not within 3 days, the order become expired. 

What's the best way to manage this?

Thanks,
Xingjian

**Comment by mementum** [comment]
Thank you for pointing out the obvious: this part is not documented. I will have to get to it.

Quick answer anyhow
  - The default execution type is "Market" which uses the next available price
  - The "bar" (set of open-high-low-close prices at a given point in time) you made the decision at ... has already happened
  - Therefore the "broker" waits for the next "bar" and uses the 1st available price.(the opening price)

In your case you would want to:

  - Issue a "limit" order inside the strategy.

    - order = self.buy(exectype=Order.Limit, price=myprice, valid=datetime.datetime.now() + datetime.timedelta(days=3))

      This will already make sure the order gets cancelled after 3 days if not executed

  - To cancel it if the price has gone too far up ... you have to control the price yourself

    if self.data.close > 1.10 * self.price_at_order_issuing:
        self.broker.cancel(order)

**Comment by xingjianpan** [comment]
Thanks!

**Comment by mementum** [comment]
In the next 2 days or so a full document will follow

**Comment by mementum** [comment]
Check the following post ... documenting everything helped out with ironing out some issues ..

http://www.backtrader.com/posts/2015-08-08/order-creation-execution/

**Comment by xingjianpan** [comment]
Many thanks @mementum !!
