### ISSUE TITLE
Add two feeds with different format

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#80]
Hi,

Is there any way to add two files with different format?
cerebro.adddata(data)
cerebro.adddata(data1) 

data = bt.feeds.GenericCSVA(path1)
data2 = bt.feeds.GenericCSVB(path2)
format1:
**Trades**:Date,Time,Type,Price,Volume
format2:
**quotes**::Date,Time,Type,Bid, Ask, BidVolume, AskVolume

I would like to run  cerebro.run()   and then align trades and quotes based on the union Date+Time

Rgds,

JJ

**Comment by mementum** [comment]
`backtrader` only uses *date/time* to ensure the datas added to the system in the 2nd and posterior positions do not overtake the 1st data added to the system (the `datamaster`) It will not look into the datas to align them. If it did so it would have to make a decision about what to do when one data is missing a datetime and the other isn't.

In that case addressing `[0]` to access price would still give the false impression that both datas are aligned when they are not. Or else return `NaN` for the components of the missing datetime, destroying indicator calculations along the way.

The only options are to add non-common missing bars to achieve alignment. An example from just a couple of days ago:

  - http://www.backtrader.com/posts/2016-04-19-sync-different-markets/sync-different-markets/
