### ISSUE TITLE
Technical Indicator: Pivot Point

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#81]
Hello,

Could you show me any example with Highest , Lowest and OperationN indicators?
I would like to use them to create "pivot point indicator"

```
R2 = P + (H - L) = P + (R1 - S1)
R1 = (P x 2) - L
P = (High + Low + Close) / 3
S1 = (P x 2) - H
S2 = P - (H - L) = P - (R1 - S1)
```

Rgds,

JJ

**Comment by mementum** [comment]
No need for `Highest`, `Lowest` or `OperationN`

  - http://www.backtrader.com/posts/2016-04-28-pivot-point-cross-plotting/pivotpoint-crossplotting/

In any case `Highest` and `Lowest` are documented here:

  - http://backtrader.readthedocs.io/en/latest/indautoref.html

**Comment by junajo10** [comment]
Hi,

Thanks  a lot by the development. I have a problem with the resampling. I always work with Tick Data, so i don´t know if this indicator only work with days and months...
My file is similar to:
ID,Date,Time,Type,Open,High,Low,Last,Volume,Open Interest
EUR/USD,01/03/16,18:01:09,Trade,1.0853,1.0854,1.085,1.085,68000000,0
EUR/USD,01/03/16,18:11:48,Trade,1.085,1.086,1.085,1.0857,18000000,0
EUR/USD,01/03/16,21:10:00,Trade,1.086,1.0866,1.0857,1.0866,13000000,0
EUR/USD,01/03/16,21:13:48,Trade,1.0866,1.0875,1.0865,1.0875,13000000,0
EUR/USD,01/03/16,21:16:58,Trade,1.0875,1.088,1.0875,1.0877,11000000,0
EUR/USD,01/03/16,22:10:16,Trade,1.0877,1.0877,1.0872,1.0872,16000000,0
EUR/USD,01/03/16,22:24:20,Trade,1.0871,1.0871,1.08685,1.0871,10000000,0
EUR/USD,01/03/16,22:32:56,Trade,1.087,1.0871,1.0868,1.087,19000000,0
EUR/USD,01/03/16,22:48:59,Trade,1.0869,1.0869,1.0867,1.0868,17000000,0
EUR/USD,01/03/16,23:00:19,Trade,1.0868,1.0868,1.0866,1.0866,26000000,0
EUR/USD,01/03/16,23:11:12,Trade,1.0865,1.0865,1.0856,1.0856,13000000,0
EUR/USD,01/03/16,23:18:22,Trade,1.0858,1.086,1.0857,1.0857,11000000,0
EUR/USD,01/03/16,23:24:46,Trade,1.0858,1.0858,1.085,1.0852,17000000,0

**Comment by junajo10** [comment]
Besides I have not said that pivot point will be calculated with 240 minutes or 4 hours, so i should resample my tick file with 4hours?

**Comment by mementum** [comment]
The indicator in the sample has no relationship with the timeframe of the original data or the timeframe of the resampled data. The indicator makes simple calculations on `close`, `high` and `low` prices.

Using _days_ and _months_ in the sample follows the guidelines of _StockCharts_. It could have also been _days_ and _weeks_.

Applying 240 minutes or other resampling period to the data is a decision made by the user.

**Comment by junajo10** [comment]
ok, the solution is clear. Thanks for the answer.
I think there is a small bug in  resamplerfilter.py. I am using fx tick data, so i have values such as:
2016-01-03 23:48:33

When i write:
cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=240)

i obtain:

  File "build\bdist.win-amd64\egg\backtrader\feed.py", line 291, in load
  File "build\bdist.win-amd64\egg\backtrader\resamplerfilter.py", line 285, in __call__
  File "build\bdist.win-amd64\egg\backtrader\resamplerfilter.py", line 217, in _adjusttime
ValueError: hour must be in 0..23


Rgds,
JJ

**Comment by junajo10** [comment]
ok, now i have tested Pivot Point indicator and now is working well. 

Thanks a lot
