### ISSUE TITLE
Workaround pivot point and close with different timeframes

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#86]
Hi,

I read your post:
"The problem with CrossDown and any other indicator is that indicators MUST work with objects of same length. Because indicators can take anything which is a lines object as input, for example: other indicators."

From my point of view compare **self.data1.close** with s1(pivot point value) is not correct  . You should compare the original **self.data.close** with s1. 

I have been thinking temporary fix and i would like to know your opinion.

My argument is based on a backtesting process with several currencies and using self.data1.close we don´t catch a lot good signals.

- Once s1 is calculated, change the length of s1, filling gaps with the correct value.So self.data.close and s1 will have the same length, also i can use the rest of indicators CrossDown,CrossUp....

Example: DATA0->6 lines per day
```
ID,Date,Time,Type,Open,High,Low,Last,Volume,Open Interest
USD/JPY,01/06/16,00:00:00,Trade,119.1,119.155,118.35,118.655,6028000000.0,0.0
USD/JPY,01/06/16,04:00:00,Trade,118.65,118.82,118.565,118.74,2389000000.0,0.0
USD/JPY,01/06/16,08:00:00,Trade,118.74,118.75,118.25,118.405,3177000000.0,0.0
USD/JPY,01/06/16,12:00:00,Trade,118.4,118.77,118.3,118.65,4072000000.0,0.0
USD/JPY,01/06/16,16:00:00,Trade,118.65,118.7,118.355,118.355,1584000000.0,0.0
USD/JPY,01/06/16,20:00:00,Trade,118.35,118.65,118.35,118.62,754000000.0,0.0
```

DATA1->Resample Daily -> close1-> 1 line per day
118.62
```
timestamp;p;s1;s2;r1;r2;close1
2016-01-06T20:00:00;118.6750;118.1950;117.7700;119.1000;118.62
```

I need to transform pivot point lines (length = 1 to length = 6), and fixing the values p;s1;s2;r1;r2 during the day.

Rgds,

JJ

**Comment by mementum** [comment]
It is now possible to mix timeframes by coupling and larger timeframe and then feeding it into an indicator.  See: http://www.backtrader.com/posts/2016-05-05-indicators-mixing-timeframes/indicators-mixing-timeframes/
