### ISSUE TITLE
New feature:benchmark

### ISSUE THREAD

**Issue by junajo10** [mementum/backtrader#89]
Hi,

I would like to suggest you include a benchmark. So we can analyze the returns of your algorithm and The returns of the benchmark. In a general sense, you're trying to write an algo that can beat the benchmark. By default you benchmark might be SPY.
 - Set X as the stock to trade in your algo.
- Set Y as the custom benchmark.

Rgds,

JJ

**Comment by mementum** [comment]
This could be an extension of the SharpeRatio analyzer and can make it in a future release

**Comment by junajo10** [comment]
ok, it is a good idea. Thanks a lot

**Comment by mementum** [comment]
Have a look at: http://www.backtrader.com/posts/2016-07-22-benchmarking/benchmarking/
