### ISSUE TITLE
Manage non-pricing data (i.e Fundamentals data) 

### ISSUE THREAD

**Issue by xingjianpan** [mementum/backtrader#9]
Hi @mementum ,

I'd like to use fundamentals ratios (i.e P/E) in my strategy, is it supported in backtrader? 

Thanks,
Xingjian

**Comment by mementum** [comment]
Statistics is something which is getting better (support to easily gather them) has been put in place.

But as far as I do understand 'P/E' this is given by company information and not by price data. Unless I am wrong I can't see how backtrader could provide this information.

**Comment by xingjianpan** [comment]
Hi @mementum,
Thanks for the reply.  

Sorry my question was not clear enough.  I understand it's out of scope for backtrader to proivde fundamentals data.  

What I'd like to understand is, is there anyway to add non-pricing data to the cerebro instance and ues the data? Or is there anyway to add more lines in the data that feed into cerebro instance and use those addtional lines in the strategy?

 It looks ok to replace one line from OHLC with any fundamentals ratio  (i.e,  replace HIGH with P/E, and later one can  write tests against HIGH field).

**Comment by mementum** [comment]
Understood. Actually most the objects in backtrader are fitted with "lines" (I call them "Lines" objects)

You can easily extend a Data Feed (which is based on a DataSeries with the standard datetime/open/high/low/close/volume/openinterest fields)

Hopefully this new entry fully answers your question:

  - http://www.backtrader.com/posts/2015-08-07/extending-a-datafeed/

**Comment by xingjianpan** [comment]
Yes, it fully answer my question, thanks!

**Comment by cgi1** [comment]
[http://www.backtrader.com/posts/2015-08-07/extending-a-datafeed/](Link is broken)
