### ISSUE TITLE
Trade object usage

### ISSUE THREAD

**Issue by kunalpawaskar** [mementum/backtrader#91]
I had a question on the trade object.
I have the following lines:

`import backtrader.trade as bttrade
`
also,
```
    cerebro = bt.Cerebro(stdstats=True, tradehistory=True)

    cerebro.addobserver(bt.observers.Trades)

```

and
```

self.log('Trade ref %s' % bttrade.Trade().history)
        self.log('Trade ref %s' % self._tradespending)
```
in the next(self) part of the strategy

On a trade execution print log I do not get the trade history:

2006-01-12, SELL EXECUTED, Price: 3661.41, Cost: 3661.41, Comm 0.00
2006-01-12, Cash 6354.42, Value 10016.08
2006-01-12, OPERATION PROFIT, GROSS 15.83, NET 15.83
2006-01-12, Cash 6354.42, Value 10016.08
 
2006-01-12, Date: 2006-01-12, Time: 10:00:00
2006-01-12, Trade ref []
2006-01-12, Trade ref [<backtrader.trade.Trade object at 0x03433AD0>, <backtrader.trade.Trade object at 0x0344D230>]

If I try bttrade.Trade it prints a reference to a Trade object.

If I try btttrade.Trade.history, I get the following error:

    self.log('Trade ref %s' % bttrade.Trade.history)
AttributeError: type object 'Trade' has no attribute 'history'

Is there some problem here? Thanks

**Comment by mementum** [comment]
You are looking in the wrong places for the history and may be looking for the wrong history.

From the documentation for the `history` (it's also in the *docstring* of the `Trade` class)

> history (list): holds a list updated with each “update” event containing the resulting status and parameters used in the update

The history contains the changes that each `Trade` accumulated and it's not the historical list of trades.

Looking at your searches:

```python
self.log('Trade ref %s' % bttrade.Trade.history)
```
The class `Trade` is just a class and contains no attribute `history`. This is only present in the instances.

```python
self.log('Trade ref %s' % bttrade.Trade().history)  # 2006-01-12, Trade ref []
self.log('Trade ref %s' % self._tradespending)  # which gives 2006-01-12, Trade ref [, ]
```

`Trade().history` is fresh object and of course its `history`is empty
`self._tradespending` contains the list of `Trades` which have been opened but have not yet been closed. The output in your message shows `2006-01-12, OPERATION PROFIT, GROSS 15.83, NET 15.83` which indicates the `Trade` has been closed and it is the reason for `self._tradespending` to be empty.

Where to find the trades

 - `Strategy` has a `self._trades` which is a `dict`containing a `list`
 - The *keys* are `datas` and for each data the list of trades (even those not closed yet) is there
 - Therefore the list of trades for *data0* in a *strategy* would be gotten as: `trades = self._trades[self.data0]`

Or you can listen for *trade* notifications with `notify_trade` and store them in a list. You will for sure only have the finished ones.

In any case and unless you are doing real-time evaluation of something, I would follow a different approach and that is: using an `Analyzer`. Have a look at the `TradeAnalyzer`, which compiles a list of statistics for the already completed trades. And even with a real-time evaluation using the `Analyzer` abstraction would be my approach.

  - https://github.com/mementum/backtrader/blob/master/backtrader/analyzers/tradeanalyzer.py
  - http://backtrader.readthedocs.io/en/latest/analyzers-reference.html

**Comment by kunalpawaskar** [comment]
Thanks @mementum. I was able to make it work with
`trades = self._trades[self.data0]`
