### ISSUE TITLE
Intraday strategy - Closing position at the end of day - Question

### ISSUE THREAD

**Issue by bransonngai** [mementum/backtrader#95]
Thank you so much for providing such marvelous platform! It's life-saver for me.

I would like to know can backtrader make every day position closing at the end of the day ? (e.g. market close at 4:15pm , i would like to close at 4:10pm) So that I can get rid of the gap-up or gap-down situations of next trading day.

Besides, can backtrader print out the datafeed which added to Cerebo instance ? I extended my datafeed with Pandas Dataframe and would like to observe the data accuracy.

Thanks mementum !

**Comment by mementum** [comment]
`backtrader` doesn't have automatic switches. Those are left for the user to implement.

You can always check the current time during `next` in the strategy. Something like:

```python
def next(self):
    if self.data.datetime.time(0) == datetime.time(4, 10):
        # do something with the position
        pass
```

With regards to printing out the datafeed, I fear I fail to understand the question. Given that you have access to the fields, you can print them out.

```python
def next(self):
    print('Open:', self.data.open[0])
```

If you want to have an automatic printout, check the `Writer`:

  - http://backtrader.readthedocs.io/en/latest/writer.html
  - http://www.backtrader.com/posts/2015-09-14-write-it-down/write-it-down/?highlight=writer

**Comment by bransonngai** [comment]
I think I got what i want.
Thanks for your reply !
