### ISSUE TITLE
Custom indicator (Question)

### ISSUE THREAD

**Issue by fanhi00** [mementum/backtrader#96]
Hi Mementum,
Is it possible to implement a rolling regression on the self.data in custom indicator? For example I want to build a indicator by using a rolling regression coefficient (sample code as below). I get an error message "AttributeError: 'LineBuffer' object has no attribute 'index'". Is it possible to use some Pandas function (such as rolling regression, rolling sum) in the indicator building? Thanks so much.

Hui

```
import backtrader as bt
import pandas as pd
import numpy as np
class TestIndicator_regress(bt.Indicator):
    lines = ('coeffient',)
    params = (('period',10),)
    def __init__(self):
        results = pd.ols(y=self.data.close,x=self.data.open,window=10)
        self.lines.coeffient = results.beta['x']
        super(TestIndicator_regress, self).__init__()
```

**Comment by mementum** [comment]
I may be missing the point. But just in case I am not.

  - An indicator uses data input to generate data output

Even if `backtrader` offers facilities to avoid the user having to iterate over the data, the data has to be iterated over.

Looking at your definition:
```
def __init__(self):
    results = pd.ols(y=self.data.close,x=self.data.open,window=10)
```

`self.data.close` at this point has to be considered *empty*. Of course the platform may have preloaded the data as an optimization to speed up things, but the implementation of an indicator has to consider that the data is empty.

> Because the data could come from any source. For example a database which is queried for each data or from a live feed

The next line:
```
self.lines.coeffient = results.beta['x']
```

This is for sure not going to work. Here you assign a (I guess) standard array to a `line`. The `line` doesn't like arrays, it likes other `line` objects, from which it can read the data when it is produced.

But the real point is the one before this assignment as commented before:

  - You want to calculate the regression of `close` prices on `open` prices when they have not even started to exist.

Your best bet is something like

```python
import backtrader as bt
import pandas as pd
import numpy as np
class TestIndicator_regress(bt.Indicator):
    lines = ('coeffient',)
    params = (('period',10),)

    def next(self):
        results = pd.ols(
            y=self.data.close.get(size=self.p.period),
            x=self.data.open.get(size=self.p.period),
            window=self.p.period)
        # ATTENTION: I don't know what's in results.beta['x']
        # and self.lines.coefficient[0] expects something that can be converted to a float
        self.lines.coefficient[0] = results.beta['x']
```

**Comment by mementum** [comment]
Additionally, since there is nothing in `__init__` to tell how much data you need (the call to `get` could change at anytime) there are two options:

1. Subclass from a handy indicator which is meant for this ... and has a single `param` defined which is named `period`.

```python
class TestIndicator_regress(bt.PeriodN):
...
```

2. Else do the following manually in your `__init__` method

```python
        self.addminperiod(self.p.period)
```
